### ISSUE TITLE
No Snapshots found on Arch Linux

### ISSUE THREAD

**Issue by borgmanJeremy** [Antynea/grub-btrfs#100]
Hello,

After upgrading grub-btrfs on Arch it no longer seems to find my snap shots. I get the following error. I'm happy to help troubleshoot and poke around if you can point me in the right direction.

```
###### - Grub-btrfs: Snapshot detection started - ######
# Info: Separate boot partition detected 
# Info: snapper detected, using config 'root'
# No snapshots found.
# If you think an error has occurred , please file a bug report at " https://github.com/Antynea/grub-btrfs "
# Nothing to do. Abort.
###### - Grub-btrfs: Snapshot detection ended   - ######
```

**Comment by maximbaz** [comment]
Try to add `set -x` on the second line of `41_snapshots-btrfs` file, re-run `grub-mkconfig -o /boot/grub/grub.cfg` and you should see a detailed execution log, maybe it will help you see why the code doesn't enter some branch of code that it is supposed to enter...

**Comment by xantyleonhart** [comment]
I'm debugging it, it is in fact finding the snapshots, but the "snapshot_list()" function is not returning them. This is my output after placing a couple printfs in said function:

`###### - Grub-btrfs: Snapshot detection started - ######
# Info: Separate boot partition not detected 
# Info: snapper detected, using config 'root'
# Info: snapper -> ' 0  / 1  / 2  / 3  / 4  / 5  / 6  / 7  / 8  / 9  /10  /11  /12  /13  /14  /15  /16  /17  /18  /19  /20  /21  /22  /23  /24  /25  /26  /27  ' ' single ' ' curre' 
#Info: btrfssubvolsort -> '--sort=-rootid'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/27/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/26/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/25/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/24/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/23/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/22/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/21/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/20/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/19/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/18/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/17/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/16/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/15/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/14/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/13/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/12/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/11/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/10/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/9/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/8/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/7/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/6/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/5/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/4/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/3/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/2/snapshot'
#Info: snap_path -> '<FS_TREE>/@/.snapshots/1/snapshot'
# No snapshots found in 115bec88-ef9e-4462-b0ab-44b075bf773e .
# If you think an error has occurred , please file a bug report at " https://github.com/Antynea/grub-btrfs "
# Nothing to do. Abort.
`

**Comment by maximbaz** [comment]
Thank you for doing this investigation! It is indeed caused by https://github.com/Antynea/grub-btrfs/commit/9b863f027bc694c764c47dc920c89a4161506695

We need to find a better way to implement that commit, I think it uses a prefix match and we could instead use a full match.

**Comment by xantyleonhart** [comment]
No problem, i was fighting with it in my new arch installation and i so happened to find this issue opened.

**Comment by borgmanJeremy** [comment]
Awesome! Beat me to it

**Comment by Antynea** [comment]
I couldn't provide a fix this week and am not sure if it is possible to do so.

**Comment by maximbaz** [comment]
What do you think about hardcoding `@` directly in code?

```diff
diff --git a/41_snapshots-btrfs b/41_snapshots-btrfs
index 3fa06bb..0700982 100755
--- a/41_snapshots-btrfs
+++ b/41_snapshots-btrfs
@@ -282,6 +282,7 @@ snapshot_list()
 
 		# ignore specific path during run "grub-mkconfig"
 		if [ ! -z "${ignore_specific_path}" ] ; then
+			[[ "${snap_path_name}" == "@" ]] && continue 2;
 			for isp in ${ignore_specific_path[@]} ; do
 				[[ "${snap_path_name}" == "${isp}" || "${snap_path_name}" == "${isp}"/* ]] && continue 2;
 			done
diff --git a/config b/config
index 6525884..f9d6eb2 100644
--- a/config
+++ b/config
@@ -53,7 +53,7 @@
 # You can combine them
 # use : GRUB_BTRFS_IGNORE_SPECIFIC_PATH=("@var/lib/docker" "var/lib/docker")
 # Default: 
-GRUB_BTRFS_IGNORE_SPECIFIC_PATH=("@" "var/lib/docker" "@var/lib/docker")
+GRUB_BTRFS_IGNORE_SPECIFIC_PATH=("var/lib/docker" "@var/lib/docker")
 
 # Snapper's config name to use
 # Default: "root"
```

Alternatively having two configs, `GRUB_BTRFS_IGNORE_SPECIFIC_PATH` and `GRUB_BTRFS_IGNORE_SPECIFIC_PATH_PREFIX` ?

**Comment by Antynea** [comment]
> What do you think about hardcoding @ directly in code?

I'm ok, "@" should be a subvolume not a snapshot.

> Alternatively having two configs

Maybe later

**Comment by maximbaz** [comment]
I would suggest to commit that patch and make a new release, I'll update Arch package asap,  it seems quite a few people have been affected by this bug.
