### ISSUE TITLE
After changing root subvol name, can't boot

### ISSUE THREAD

**Issue by junyixu** [Antynea/grub-btrfs#101]
I changed my root subvol name from "arch_root" to "@", I got 
![image](https://user-images.githubusercontent.com/40481594/92128518-1159da00-ee35-11ea-94ce-cff137817260.png)

I booted into arch live CD, and changed all "arch_root" to "@" in `/boot/grub/grub-btrfs.cfg ` , and reboot.

But when I ` sudo grub-mkconfig -o /boot/grub/grub.cfg`, I got this
```
Generating grub configuration file ...
Found theme: /boot/grub/themes/Griffin/theme.txt
Found linux image: /boot/vmlinuz-linux
Found initrd image: /boot/intel-ucode.img /boot/amd-ucode.img /boot/initramfs-linux.img
Found fallback initrd image(s) in /boot: initramfs-linux-fallback.img
###### - Grub-btrfs: Snapshot detection started - ######
# Info: Separate boot partition not detected 
# Info: snapper detected, using config 'root'
# No snapshots found.
# If you think an error has occurred , please file a bug report at " https://github.com/Antynea/grub-btrfs "
# Nothing to do. Abort.
###### - Grub-btrfs: Snapshot detection ended   - ######
done
```

**Comment by junyixu** [comment]
I try to add `set -x` and `sudo grub-mkconfig -o /boot/grub/grub.cfg |  xclip -selection clipboard -in` again but it doesn't work...

**Comment by maximbaz** [comment]
have a look at  #100
