### ISSUE TITLE
report from a noob: "grub-probe: error: cannot find a GRUB drive for /dev/sda1.  Check your device.map."

### ISSUE THREAD

**Issue by easthvan** [Antynea/grub-btrfs#108]
Hello Dev Team

I am completely new on Linux, and have just installed Manjaro after deleting my Win10 and hopping like 10 distros in these days. I ended up with Manjaro. 

I encountered some seemingly errors after updating may Grub on a clean install and just wanted to report here as per the request within the terminal, so I just followed the instructions there with a link to here. 

My OS is working perfectly and booting so I have no clue is there is any error or not so I just report it here for your information.

![image](https://user-images.githubusercontent.com/71530894/94054984-9d2fa800-fddc-11ea-822b-8838d2d057b4.png)

![image](https://user-images.githubusercontent.com/71530894/94055409-2b0b9300-fddd-11ea-84d7-1fc6237ca74e.png)

LUKS full disk encryption with Btrfs is the active, working setup. 
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
Kernel Version: 5.7.19-2-MANJARO
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-8700K CPU @ 3.70GHz
Memory: 15.6 GiB of RAM
Graphics Processor: GeForce RTX 2070/PCIe/SSE2

**Comment by Antynea** [comment]
Hello,
Thanks for your report.

To make sure the error belongs to `grub-btrfs`:
Can you uninstall `grub-btrfs` package from your distribution and re-run `sudo update-grub`, please.
`grub-btrfs` just add a new menu entry in your Grub menu, it isn't worrying to delete it, Manjaro doesn't need it to boot.
If the error has disappeared, then `grub-btrfs is the cause`, i will try to fix it.
Your screenshots help me understand the problem.
