### ISSUE TITLE
git-latest oddity

### ISSUE THREAD

**Issue by sdothum** [Antynea/grub-btrfs#11]
I have similar Arch installs on several computers. For some reason, pacaur -Sua insists on listing 

grub-btrfs-git-latest

for update on some installs, and not others. I've uninstalled the git package but after reinstallation, the problem persists even though the --devel flag is not enabled.

Any ideas how to track this down or fix the erroneous reporting?

Not a show stopper. I ignore it but it's puzzling.

**Comment by Antynea** [comment]
hi,

i don't have this trouble but i suspect that version in pkgbuild on AUR is incorrect.
2 issues reasonable : 
adopted and upgraded pkgbuild on aur with correct version (delete "-1" at the end)
or
wait another version release on github...

**Comment by sdothum** [comment]
cower -u revealed 

:: grub-btrfs-git v1.7.r6.g4388c33-1 -> v1.7.r6.g4388c33-1-1

Removing the "-1" on the pkgver does not appear to resolve the problem. So I guess I'll need to wait for a version release on github.

**Comment by Antynea** [comment]
i update github to 1.7.1, bug fix.
Enjoy
