### ISSUE TITLE
Adds docker snapshots to grub list, despite being ignored in config

### ISSUE THREAD

**Issue by mruiz42** [Antynea/grub-btrfs#110]
On Arch Linux I am getting an issue where it will include snapshots of docker containers on my machine at
`var/lib/docker/btrfs/subvolumes`
despite it being included in `/etc/default/grub-btrfs/`config here:

`57 GRUB_BTRFS_IGNORE_SPECIFIC_PATH=("var/lib/docker" "@var/lib/docker" "var/lib/docker/btrfs/subvolumes" "@/var/lib/docker/btrfs/subvolumes/")`

Post pac-snap output:

`Found snapshot: 2020-10-01 20:34:38 | @/.snapshots/5/snapshot                                                                                 | pre    | pacman -Syu
Found snapshot: 2020-10-01 16:30:38 | @/.snapshots/1/snapshot                                                                                 | single | timeline
Found snapshot: 2020-09-21 13:56:05 | @/var/lib/docker/btrfs/subvolumes/12ee3841107f6a84f2dd8d27de3add46ac93be3ed05e9c4d38dbb505085b06ea-init
Found snapshot: 2020-09-19 04:48:14 | @/var/lib/docker/btrfs/subvolumes/ca4982dd926876676465206d1ecd78f98af61d1e10cad81abae6e53e161c635c-init
Found snapshot: 2020-09-12 18:31:19 | @/var/lib/docker/btrfs/subvolumes/976ac50fc3e045ba3011ae8409dd156b8e3879304766a2bc422e832ef386baeb
Found snapshot: 2020-09-12 18:31:19 | @/var/lib/docker/btrfs/subvolumes/98a5c0240b308ccb3610459ac48acfcad9afd24a0a77e86c68b9eab5781096af
Found snapshot: 2020-09-12 18:31:19 | @/var/lib/docker/btrfs/subvolumes/9def363859fbba065560c821a0be16b4b16f749d089690f68b8c5e11e9aab4c9
Found snapshot: 2020-09-12 18:31:16 | @/var/lib/docker/btrfs/subvolumes/6000b365c4369b1aea0bc2b38e2333c50f54c44e18da5972bb109867d52e8731
Found snapshot: 2020-09-12 18:12:54 | @/var/lib/docker/btrfs/subvolumes/3ceadc8495ce125b0d9b0c6ba045dc15927d516331ddd3597c350aef2620ceaa
Found snapshot: 2020-09-12 18:12:54 | @/var/lib/docker/btrfs/subvolumes/3ceadc8495ce125b0d9b0c6ba045dc15927d516331ddd3597c350aef2620ceaa-init
Found snapshot: 2020-09-12 02:19:25 | @/var/lib/docker/btrfs/subvolumes/462c1909d14af8d924849922ed4185525dabee22f8b35e17b6c58f951bca4eda
Found snapshot: 2020-09-12 02:19:24 | @/var/lib/docker/btrfs/subvolumes/ac8542243671fcc2a057d21373be0fa8f0df1693b56edfc032595acb97ce360c
Generated 400 total GRUB entries. You might experience issues loading snapshots menu in GRUB.
Found 50 snapshot(s)
done
`

**Comment by maximbaz** [comment]
It's a simple [string prefix comparison](https://github.com/Antynea/grub-btrfs/blob/9a771d9842e47e744a2a54b557a0a6cad16eb4bc/41_snapshots-btrfs#L272), looks like your paths are `@/var/lib/docker` so that's the exact string that should be in your configuration 😉

**Comment by Antynea** [comment]
I didn't have the idea to add this syntax by default
I will.
`@/var/lib/docker`
