### ISSUE TITLE
snapshot not in grub menu please help antynea

### ISSUE THREAD

**Issue by nmars-cloud** [Antynea/grub-btrfs#114]
please help my subvolumes are 
```
ID 294 gen 6830 top level 5 path @home
ID 295 gen 6858 top level 5 path @
ID 296 gen 2129 top level 5 path timeshift-btrfs/snapshots/2020-10-09_16-25-23/@
ID 304 gen 2693 top level 5 path timeshift-btrfs/snapshots/2020-10-10_07-48-19/@
ID 434 gen 6302 top level 5 path timeshift-btrfs/snapshots/2020-10-12_09-54-39/@
ID 436 gen 6539 top level 5 path timeshift-btrfs/snapshots/2020-10-12_11-42-33/@
ID 437 gen 6579 top level 5 path timeshift-btrfs/snapshots/2020-10-12_12-00-16/@
ID 438 gen 6640 top level 295 path @/.snapshots
ID 439 gen 6609 top level 438 path @/.snapshots/1/snapshot
ID 440 gen 6905 top level 294 path @home/.snapshots
ID 441 gen 6690 top level 440 path @home/.snapshots/1/snapshot
ID 442 gen 6691 top level 440 path @home/.snapshots/2/snapshot
ID 443 gen 6692 top level 440 path @home/.snapshots/3/snapshot
ID 444 gen 6693 top level 440 path @home/.snapshots/4/snapshot
ID 445 gen 6710 top level 440 path @home/.snapshots/5/snapshot
ID 446 gen 6711 top level 440 path @home/.snapshots/6/snapshot
ID 447 gen 6765 top level 440 path @home/.snapshots/7/snapshot
ID 448 gen 6766 top level 440 path @home/.snapshots/8/snapshot
ID 449 gen 6803 top level 5 path timeshift-btrfs/snapshots/2020-10-12_13-33-58/@
ID 450 gen 6830 top level 440 path @home/.snapshots/9/snapshot
ID 451 gen 6832 top level 5 path timeshift-btrfs/snapshots/2020-10-12_13-48-44/@
ID 452 gen 6858 top level 5 path timeshift-btrfs/snapshots/2020-10-12_14-05-13/@
```
i used both timeshift and snapper same effect manualy creating snap from timeshift is ok
i have arch two partition one efi fat32 second root btrfs any help thank you

Edit: add balise code.

**Comment by Antynea** [comment]
Hello,

Do you use Arch Linux?
Did you generate your grub.cfg via grub-mkconfig after creating a snapshot ?
Or do you use the provided systemd service?

If `grub.cfg` is generated correctly,
can tell me the location of your grub folder, please.
(hdd partition, exact path)
Also, do you see the `Arch Linux snapshot` submenu in Grub ?

**Comment by nmars-cloud** [comment]
hi antynea thanks for reply yes i use arch linux terminal installing from guide from tecmint, and yes generating like that sudo grub-mkconfig -o /boot/grub/grub.cfg yes i use systemd service yes grub.cfg is generating correctly my fstab look like that # Static information about the filesystems.
# See fstab(5) for details.


# /dev/nvme0n1p2
UUID=6b3a61e1-1d4d-46e7-9233-176a1efa0de8       /               btrfs           rw,relatime,subvol=@    0 1

/dev/disk/by-uuid/66902dce-fc9e-494a-b03d-757c511579c8 /mnt/66902dce-fc9e-494a-b03d-757c511579c8 auto nosuid,nodev,nofail,x-gvfs-show 0 0

i added subvol=@
first i installed arch in system file ext4 after install i converted ext4 to btfrs first after converting and installing timeshift-autosnap and btrfs-grub and added subvol=@ i have one snapshot in the grub menu now i have nothing i paste you the output

Generating grub configuration file ...
Found linux image: /boot/vmlinuz-linux
Found initrd image: /boot/amd-ucode.img /boot/initramfs-linux.img
Found fallback initrd image(s) in /boot: initramfs-linux-fallback.img
Detecting snapshots ...
Info: Separate boot partition not detected 
No snapshots found.
If you think an error has occurred , please file a bug report at " https://github.com/Antynea/grub-btrfs "
Nothing to do. Abort.
done

my grub location is /boot/grub/
antynea thanks for help me with this
p.s i have two partitions efi in fat32 and btrfs root partition aha /dev/disk/by-uuid/66902dce-fc9e-494a-b03d-757c511579c8 /mnt/66902dce-fc9e-494a-b03d-757c511579c8 auto nosuid,nodev,nofail,x-gvfs-show 0 0 this is second disk i do not have efi partition in fstab thanks for reply and help

**Comment by nmars-cloud** [comment]
and output after timeshift autosnap
Creating new backup...(BTRFS)
Saving to device: /dev/nvme0n1p2, mounted at path: /run/timeshift/backup
Created directory: /run/timeshift/backup/timeshift-btrfs/snapshots/2020-10-12_19-04-44
Created subvolume snapshot: /run/timeshift/backup/timeshift-btrfs/snapshots/2020-10-12_19-04-44/@
Created control file: /run/timeshift/backup/timeshift-btrfs/snapshots/2020-10-12_19-04-44/info.json
BTRFS Snapshot saved successfully (0s)
Tagged snapshot '2020-10-12_19-04-44': ondemand
------------------------------------------------------------------------------

/dev/nvme0n1p2 is mounted at: /run/timeshift/backup, options: rw,relatime,ssd,space_cache,subvolid=5,subvol=/

------------------------------------------------------------------------------
Removing snapshot: 2020-10-12_12-00-16
Deleting subvolume: @ (Id:437)
Deleted subvolume: @ (Id:437)

Destroying qgroup: 0/437
Destroyed qgroup: 0/437

Deleted directory: /run/timeshift/backup/timeshift-btrfs/snapshots/2020-10-12_12-00-16
Removed snapshot: 2020-10-12_12-00-16
------------------------------------------------------------------------------
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-linux
Found initrd image: /boot/amd-ucode.img /boot/initramfs-linux.img
Found fallback initrd image(s) in /boot: initramfs-linux-fallback.img
Detecting snapshots ...
Info: Separate boot partition not detected 
No snapshots found.
If you think an error has occurred , please file a bug report at " https://github.com/Antynea/grub-btrfs "
Nothing to do. Abort.
done
:: Processing package changes...
(1/1) reinstalling timeshift-autosnap                                                          [#######################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

**Comment by nmars-cloud** [comment]
antynea please explain and help this doesnt work at the moment probably bad configuration your script my computer sorry for copy paste from terminal

**Comment by Antynea** [comment]
> antynea please explain and help this doesnt work at the moment probably bad configuration your script my computer sorry for copy paste from terminal

There is no point in begging, i was busy with my family.
You are on a non-instant messaging thread (this is not an instant messenger).

I humbly ask you to better format your messages.
Your answers, in their current form, are unusable.

Understand that if you don't make any effort to communicate, no one can help you.
I made the effort to correct your first message.
This was the first and last time.

If you want to continue to communicate here, presented a correct layout.
With answers adapted to the questions you are asked.

Between my answer and your request, you have tinkered with your system, so my queries about your initial request have become obsolete.


However, you should know that my script uses the following command to detect your snapshots:
`btrfs subvolume list -sa /`
Then performs tests on the snapshots found.

Challenge yourself, make the changes, and we can continue the discussion.
