### ISSUE TITLE
Error/bug on latest Manjaro update (maybe)

### ISSUE THREAD

**Issue by olividir** [Antynea/grub-btrfs#117]
I am running Manjaro Gnome with btrfs filesystem, currently on `testing` branch. 
Today's update threw out an error 
```
Adding boot menu entry for UEFI Firmware Settings ...
Detecting snapshots ...
Info: Separate boot partition not detected 
No snapshots found.
If you think an error has occurred , please file a bug report at " https://github.com/Antynea/grub-btrfs "
Error while configuring 
Nothing to do. Abort.
Found memtest86+ image: /boot/memtest86+/memtest.bin
/usr/bin/grub-probe: warning: unknown device type nvme0n1.
done
```
I am **NOT** sure if this is a bug or not. I haven't rebooted. Before I do anything I would like to know how to find or make bug report, to see if everything is OK or not. I have updated this system before without getting any errors. 

I am not sure what info you require here, but I am more than happy to help.

**Comment by olividir** [comment]
I tried to reboot, and everything seems smooth. I am guessing this error is nothing to worry about. I think it is OK to close this thread.

**Comment by Antynea** [comment]
Hello,

Ok.
However, if this happens to you again.
Disable `grub-btrfs` by editing the `config` file in `/etc/default/grub-btrfs/`.
Uncomment: `GRUB_BTRFS_DISABLE="true"`.
Then run the command `grub-mkconfig` again.
If a problem persists, Grub seems to install poorly.
Get closer to the manjaro forum.
