### ISSUE TITLE
Black screen when booting into snapshot on EndeavourOS

### ISSUE THREAD

**Issue by MarcelBochtler** [Antynea/grub-btrfs#119]
**OS: EndeavourOS
Version: 4.7.1-1**
Installed in UEFI mode and using NVIDIA's proprietary GPU driver.

Hi, I did setup `grub-btrfs` with [snapper](http://snapper.io/), [snap-pac](https://github.com/wesbarnett/snap-pac) and [snap-pac-grub](https://aur.archlinux.org/packages/snap-pac-grub/).
Unfortunately I'm getting a black screen whenever I try to boot into a snapshot. I'm also not able to switch to a different virtual console using `CTRL+ALT+F2`

My root subvolume layout looks like this:
```
❯ sudo btrfs subvolume list /
ID 256 gen 1719 top level 5 path @
ID 259 gen 20 top level 256 path var/lib/portables
ID 260 gen 21 top level 256 path var/lib/machines
ID 271 gen 1708 top level 256 path .snapshots
ID 272 gen 1720 top level 256 path var/log
ID 273 gen 1650 top level 271 path .snapshots/1/snapshot
```

**Comment by Antynea** [comment]
Hi,

It seems that you use snapper to create/manage your snapshots.
By default, snapper creates snapshots in read-only mode, it is tricky to boot on snapshots in read-only mode.
You can use this command to check if your snapshot is in read-only mode or not:
`btrfs property get /.snapshots/1/snapshot ro` ("ro=false" means writeable mode)

To make sure the issue comes from snapper, create a snapshot manually in writeable mode.
`btrfs subvolume snapshot / /.snapshot/test-writeable`
Replace `/.snapshot/` with correct path, where your snapshot is located.
Then, regenerate your grub config, reboot, and test to boot on snapshot previously created.

If the issue comes from the read-only mode, please read this:
https://github.com/Antynea/grub-btrfs#warning-booting-on-read-only-snapshots-can-be-tricky
and
https://github.com/Antynea/grub-btrfs/blob/master/initramfs/readme.md
and for more info :
https://github.com/Antynea/grub-btrfs/issues/92

**Comment by MarcelBochtler** [comment]
Thanks for the response.

Yes, all snapshots were created using snapper and in are read-only. Thanks for the links to deal with that.
However, I created a new snapshot using `btrfs subvolume snapshot / /.snapshots/test-writeable` and had the same result. I'm only getting a black screen after I tried to boot into that writable snapshot.

**Comment by Antynea** [comment]
It's strange this issue.
I may have a suggestion, it's possible that a kernel parameter or a module missing in the initramfs, or a systemd parameter, could prevent the snapshot (writable) to work properly.

You can try to provide this:
`cat /proc/cmdline`
Your file `/etc/default/grub`
A valid `grub.cfg` file as well as `grub-btrfs.cfg`

You can also try to remove the `quiet' parameter which will make the startup more verbose.


I installed EndeavourOS in a virtual machine, during formatting I partitioned as follows:

First virtual disk:
Disklabel type: dos (mbr)
only 1 partition type btrfs
3 subvolumes :
@ `mountpoint /`
@home `mountpoint /home`
@snapshots `mountpoint /.snapshots`

Second virtual disk:
Disklabel type: dos (mbr)
only 1 partition type FAT
`mountpoint /boot/efi`

Everything works fine, however I couldn't try the NVIDIA's proprietary GPU driver.

**Comment by MarcelBochtler** [comment]
```
marcel-desktop# cat /proc/cmdline
BOOT_IMAGE=/@/boot/vmlinuz-linux root=UUID=fcad65a9-4514-4309-a841-08282d900ca5 rw rootflags=subvol=@ loglevel=3 nowatchdog
```

[/etc/default/grub](https://gist.github.com/MarcelBochtler/311fdbddad66ca3f40ee78462dee9954)

[/boot/grub/grub.cfg](https://gist.github.com/MarcelBochtler/42f9be7f24c0ddbe0f29d9084a9a130f)

[/boot/grub/grub-btrfs.cfg](https://gist.github.com/MarcelBochtler/631b79c8ebad3dc3fe83e70020ae4bbc#file-grub-btrfs-cfg-L1054-L1092)

**Comment by Antynea** [comment]
Thank you for sharing your files.
Unfortunately, I don't find any error ...

After removing `quiet` parameter, do you see these messages at boot time ?? : 
```
Loading Snapshot: 2020-11-30 19:46:11 @/.snapshots/test-writeable
Loading Kernel: vmlinuz-linux ...
Loading Microcode & Initramfs: intel-ucode.img initramfs-linux-fallback.img ...
```
then :
```
:: running early hook [udev]
Starting version 246.5-1-arch
:: running hook [udev]
:: Triggering uevents...
etc...
```

Can you try this:
Edit the file /etc/grub.d/40_custom
```
#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'EndeavourOS snapshot writable' --class endeavouros --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-linux-advanced-fcad65a9-4514-4309-a841-08282d900ca5' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod btrfs
	set root='hd0,gpt6'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-ieee1275='ieee1275//disk@0,gpt6' --hint-bios=hd0,gpt6 --hint-efi=hd0,gpt6 --hint-baremetal=ahci0,gpt6  fcad65a9-4514-4309-a841-08282d900ca5
	else
	  search --no-floppy --fs-uuid --set=root fcad65a9-4514-4309-a841-08282d900ca5
	fi
	echo	'Loading snapshot writable ...'
	linux   "/@/.snapshots/test-writeable/boot/vmlinuz-linux" root=UUID=fcad65a9-4514-4309-a841-08282d900ca5 rw  loglevel=3 nowatchdog rootflags=subvol="@/.snapshots/test-writeable"
	echo	'Loading initrafms & microcode ...'
	initrd  "/@/.snapshots/test-writeable/boot/intel-ucode.img" "/@/.snapshots/test-writeable/boot/initramfs-linux-fallback.img"
}
```
Then regenerate your grub config, and try to boot on this new entry.
(If you have deleted `/@/.snapshots/test-writeable` create it again)

This configuration will be inserted directly in the grub.cfg file.
This allows to know if the problem comes from the grub-btrfs.cfg file.

**Comment by MarcelBochtler** [comment]
> After removing quiet parameter, do you see these messages at boot time ?? :

Yes I see these messages exactly as you described them.

> Can you try this:
Edit the file /etc/grub.d/40_custom

I added this and I can find the snapshot in my grub menu. Unfortunately it also only boots into a black screen.

**Comment by Antynea** [comment]
Ok, so if I understood correctly, your snapshot boots. 
However when loading your graphic session you get a black screen.
This problem isnt' related to this project.

To check and allow you to solve your problem by yourself.
You can change the [RUNLEVEL](https://wiki.archlinux.org/index.php/SysVinit#Runlevels) (5 by default) to 3.

Below I've added runlevel 3 to the kernel parameter of the snapshot.
Simply by adding the number corresponding to the desired runlevel, here "3".
```
#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'EndeavourOS snapshot writable' --class endeavouros --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-linux-advanced-fcad65a9-4514-4309-a841-08282d900ca5' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod btrfs
	set root='hd0,gpt6'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-ieee1275='ieee1275//disk@0,gpt6' --hint-bios=hd0,gpt6 --hint-efi=hd0,gpt6 --hint-baremetal=ahci0,gpt6  fcad65a9-4514-4309-a841-08282d900ca5
	else
	  search --no-floppy --fs-uuid --set=root fcad65a9-4514-4309-a841-08282d900ca5
	fi
	echo	'Loading snapshot writable ...'
	linux   "/@/.snapshots/test-writeable/boot/vmlinuz-linux" root=UUID=fcad65a9-4514-4309-a841-08282d900ca5 rw  loglevel=3 nowatchdog 3 rootflags=subvol="@/.snapshots/test-writeable"
	echo	'Loading initrafms & microcode ...'
	initrd  "/@/.snapshots/test-writeable/boot/intel-ucode.img" "/@/.snapshots/test-writeable/boot/initramfs-linux-fallback.img"
}
```

**Comment by MarcelBochtler** [comment]
>Ok, so if I understood correctly, your snapshot boots.

Yes, that is correct.

>However when loading your graphic session you get a black screen.
This problem isnt' related to this project.

Thank you anyways. I'll close this issue and will try to figure out what causes this black screen issue.
My guess is that I'd be able to boot using the nouveau driver instead of the proprietary NVidia driver.

**Comment by Antynea** [comment]
I hope you can find a solution, don't hesitate to come back here to share it.
Sorry I can't help you anymore.
