### ISSUE TITLE
GRUB stops updating after Snapper rollback

### ISSUE THREAD

**Issue by ozboss** [Antynea/grub-btrfs#120]
This issue is probably more a lack of understanding on my side but maybe someone can help me out.

I'm using grub-btrfs with Snapper on Debian 10.
I have enabled and started grub-btrfs.path.
The grub menu is populating fine with new snapshots until I do a rollback with snapper.
The rollback is working fine it and new snapshots are being created, they only don't show up in GRUB.
Running `update-grub` finds new snapshots and updates `/boot/grub/grub-btrfs.cfg` accordingly (says "Separate boot partition not detected" even though it should?).
Running `grub-install` fixes the situation and the snapshots populate again in GRUB until the next rollback.

I sure am missing something here...

```
$ lsblk
sda      8:0    1  29.9G  0 disk
├─sda1   8:1    1   512M  0 part /boot/efi
├─sda2   8:2    1  28.4G  0 part /
└─sda3   8:3    1   977M  0 part [SWAP]
sdb      8:16   0 119.2G  0 disk
sr0     11:0    1  1024M  0 rom
```
```
$  btrfs sub list /
ID 257 gen 905 top level 5 path @
ID 258 gen 16 top level 5 path @home
ID 259 gen 902 top level 5 path @snapshots
ID 262 gen 677 top level 259 path @snapshots/1/snapshot
ID 263 gen 679 top level 259 path @snapshots/2/snapshot
...
ID 303 gen 887 top level 259 path @snapshots/41/snapshot
ID 304 gen 891 top level 259 path @snapshots/42/snapshot
ID 305 gen 892 top level 259 path @snapshots/43/snapshot
ID 306 gen 914 top level 259 path @snapshots/44/snapshot
ID 307 gen 896 top level 259 path @snapshots/45/snapshot
ID 308 gen 901 top level 259 path @snapshots/46/snapshot
```
``` 
$ btrfs sub get-default /
ID 306 gen 915 top level 259 path @snapshots/44/snapshot
```
```
$ mount | grep sub
/dev/sda2 on / type btrfs (rw,relatime,space_cache,subvolid=306,subvol=/@snapshots/44/snapshot)
/dev/sda2 on /.snapshots type btrfs (rw,relatime,space_cache,subvolid=259,subvol=/@snapshots)
/dev/sda2 on /home type btrfs (rw,relatime,space_cache,subvolid=258,subvol=/@home)
```
```
$ cat /etc/fstab
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sdc2 during installation
UUID=a8887385-1865-4988-bb85-df56df3939bd /               btrfs   defaults,subvol=@        0       0
UUID=a8887385-1865-4988-bb85-df56df3939bd /home               btrfs   defaults,subvol=@home        0       0
UUID=a8887385-1865-4988-bb85-df56df3939bd /.snapshots               btrfs   defaults,subvol=@snapshots        0       0
# /boot/efi was on /dev/sdc1 during installation
UUID=1F15-36F2  /boot/efi       vfat    umask=0077      0       1
# swap was on /dev/sdc3 during installation
UUID=03a7a1c1-da4b-49ba-a54a-63b2550888af none            swap    sw              0       0
/dev/sr0        /media/cdrom0   udf,iso9660 user,noauto     0       0
```

**Comment by Antynea** [comment]
Hello,
The experience you are having is correct.

> (says "Separate boot partition not detected" even though it should?).

This is informative, and corresponds perfectly to the information you provided.

> The rollback is working fine it and new snapshots are being created, they only don't show up in GRUB.

The Grub menu is linked to the old snapshot, you have to use grub-install again.

> Running grub-install fixes the situation and the snapshots populate again in GRUB until the next rollback.

This is the right procedure.

**Comment by ozboss** [comment]
Thanks @Antynea  for your quick response.
I first had to wrap my head around this, but good to know I'm doing it the right way :)
I feel using Snapper on Debian is not that well documented so may this will also help others.
