### ISSUE TITLE
Compatible with UEFI boot

### ISSUE THREAD

**Issue by saivert** [Antynea/grub-btrfs#13]
I have a problem where it incorrectly assumes initramfs is in /subvol name/boot
As of commit 8fffc13c2f0e4f47facd12fa1aeafdeb1adaca90 at line 143:

    initrd \"${boot_dir_real_path}/"${u}"\" \"/"${snap_dir_name}"/boot/"${i}"\""

I have my EFI system partition mounted at /boot and my current boot entry always loads the initramfs direct from the ESP root (not in any subdirectories). This is the recommended setup for Arch Linux if you boot using UEFI.
ex: initrd	/intel-ucode.img /initramfs-linux.img

How could we best make sure this script recognizes this and use the appropriate path?

I'm happy to use GRUB_BTRFS_NINIT to override this but it doesn't seem like it does this mistake for the kernel.

**Comment by Antynea** [comment]
hi,

This script is not originally designed to UEFI boot, but you can use it anyway.

Otherwise, thank you for a reported bug detection for initramfs.

I push a fix, you can test it by changing the source in the PKGBUILD to the AUR.
uncomment:

> source=('git+https://github.com/Antynea/grub-btrfs.git#branch=v1.xx')

and comment master.

**Comment by Antynea** [comment]
Branch master update with early fix
Open a new issue if u are any trouble.
Close.
