### ISSUE TITLE
grub-btrfs 4.8.1.1 seems to mount / to /tmp/tmp.* at every update-grub

### ISSUE THREAD

**Issue by FGD-Garuda** [Antynea/grub-btrfs#141]
SPLIT OF https://github.com/Antynea/grub-btrfs/issues/140

Ok for lsof, I don't get much info.

╰─λ lsof /tmp
COMMAND    PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
latte-doc 1845 frank   23uW  REG   0,40       93   45 /tmp/latte-dock.frank.lock

I do 1 or 2 update-grub and I always get that above.

However after a full fresh system install and upgrading to 4.8.1.1 and not changing chmod to any file in /etc/grub.d, I get the following:

╰─λ grubup
Generating grub configuration file ...
Found theme: /usr/share/grub/themes/garuda/theme.txt
Found linux image: /boot/vmlinuz-linux-tkg-bmq-cust
Found initrd image: /boot/amd-ucode.img /boot/initramfs-linux-tkg-bmq-cust.img
Found fallback initrd image(s) in /boot: initramfs-linux-tkg-bmq-cust-fallback.img
umount: /var/lib/os-prober/mount: target is busy.
mount: /var/lib/os-prober/mount: /dev/sda1 already mounted on /.
Found Garuda Linux on /dev/nvme0n1p1
Found Garuda Linux on /dev/sda1
Detecting snapshots ...
Info: Separate boot partition not detected
Found snapshot: 2021-02-02 20:32:00 | @snapshots/@.updated
Found snapshot: 2021-02-02 20:18:15 | @snapshots/@.fresh_compiled_kernel2
Found snapshot: 2021-02-02 20:07:34 | @snapshots/@.fresh_compiled_kernel
Found snapshot: 2021-01-15 22:09:01 | @snapshots/ad-hoc/@.garuda_2021-01-15
Found snapshot: 2021-01-11 19:47:02 | @.bkp
Found snapshot: 2021-01-10 22:30:38 | @.2010
umount: /tmp/tmp.bCh3HZwZ58: target is busy.

There is another umount error in /var/lib this time. It is not present in `findmnt -l`, though. Only /tmp/tmp.* are.

**Comment by Antynea** [comment]
Confirmed.
I can reproduce this bug in a virtual machine
but only on the garuda distribution. (Arch Linux, Manjaro don't have this issue)

**Comment by FGD-Garuda** [comment]
A'right, thank you pal, as always. :)

I have advised the Garuda maintainers about this. I believe someone from their team should hop in on this issue as I don't think I can help much further. Sure I can test some stuff, but I do not know anything about the Garuda-specific packages and I don't want to waste anyone's time.

**Comment by librewish** [comment]
It was precached-git package causing this
For now i have conflicted it and it will soon be gone
You can probably close this issue

**Comment by FGD-Garuda** [comment]
True. Now working with 4.8.1.1.

Thanks.

Closing
