### ISSUE TITLE
Unified bash executable and a correction

### ISSUE THREAD

**Issue by petsam** [Antynea/grub-btrfs#142]
Browsing the code for understanding (irrelevant), I noticed `bash`  is called in various ways.
It may not be important, but I just wanted to bring it to your attention, in case you think it needs any change.
https://github.com/Antynea/grub-btrfs/blob/2f22fd8630252e5bc8d970e454fefa90e811fa68/41_snapshots-btrfs#L1

https://github.com/Antynea/grub-btrfs/blob/2f22fd8630252e5bc8d970e454fefa90e811fa68/grub-btrfs.service#L11

https://github.com/Antynea/grub-btrfs/blob/2f22fd8630252e5bc8d970e454fefa90e811fa68/initramfs/Arch%20Linux/overlay_snap_ro-install#L1

https://github.com/Antynea/grub-btrfs/blob/2f22fd8630252e5bc8d970e454fefa90e811fa68/initramfs/Arch%20Linux/overlay_snap_ro-hook#L1

This last one seems like an error.

**Comment by Antynea** [comment]
No statement error.
Maybe you would like more explanation:

https://github.com/Antynea/grub-btrfs/blob/2f22fd8630252e5bc8d970e454fefa90e811fa68/41_snapshots-btrfs#L1
`/usr/bin/env`
It is used to avoid knowing the exact path to bash on each distribution
(Arch Linux, Debian, etc ...)

https://github.com/Antynea/grub-btrfs/blob/2f22fd8630252e5bc8d970e454fefa90e811fa68/grub-btrfs.service#L11
The path is already declared in 
`Environment="PATH=/sbin:/bin:/usr/sbin:/usr/bin"`
No need to declare it again
https://github.com/Antynea/grub-btrfs/blob/2f22fd8630252e5bc8d970e454fefa90e811fa68/initramfs/Arch%20Linux/overlay_snap_ro-install#L1

https://github.com/Antynea/grub-btrfs/blob/2f22fd8630252e5bc8d970e454fefa90e811fa68/initramfs/Arch%20Linux/overlay_snap_ro-hook#L1
Specific to `Arch Linux` distribution
#

Thanks for reporting this.
If you think improvement is necessary,
Don't hesitate to comment.

**Comment by petsam** [comment]
> Specific to Arch Linux distribution

In Arch, (and I think others are going there) bin is a symlink
```
$ ls -l /bin
lrwxrwxrwx 1 root root 7 Ιαν  19 03:32 /bin -> usr/bin
```
You have both bash paths. I just say it looks nicer (and not confusing to beginners) to have one path for the same thing.
Truth is I now noticed the last two files are Arch specific. Though they don't use the same path.

But I guess you have still not noticed the mistake.
```
 #!/usr/bin/ash 
#=====
$ LANG=en ls -l /usr/bin/ash
ls: cannot access '/usr/bin/ash': No such file or directory
```

Summing up, use this in both Archlinux-initramfs scripts
```
#!/usr/bin/bash

**Comment by Antynea** [comment]
> cannot access '/usr/bin/ash': No such file or directory

I simply used the already existing paths provided in the official files that Arch Linux installs.
If you look at the contents of the hooks files provided by Arch Linux, all the shebang are equal to `#!/usr/bin/ash `

```
head -n 1 /usr/lib/initcpio/hooks/*

==> /usr/lib/initcpio/hooks/btrfs <==
#!/usr/bin/ash

==> /usr/lib/initcpio/hooks/consolefont <==
#!/usr/bin/ash

==> /usr/lib/initcpio/hooks/encrypt <==
#!/usr/bin/ash

==> /usr/lib/initcpio/hooks/grub-btrfs-overlayfs <==
#!/usr/bin/ash

...
```
```
head -n 1 /usr/lib/initcpio/install/*

==> /usr/lib/initcpio/install/autodetect <==
#!/bin/bash

==> /usr/lib/initcpio/install/base <==
#!/bin/bash

==> /usr/lib/initcpio/install/block <==
#!/bin/bash

==> /usr/lib/initcpio/install/btrfs <==
#!/bin/bash

==> /usr/lib/initcpio/install/consolefont <==
#!/bin/bash

==> /usr/lib/initcpio/install/encrypt <==
#!/bin/bash

==> /usr/lib/initcpio/install/filesystems <==
#!/bin/bash
...
```
I am aware that the path doesn't exist.
It would be interesting to know why Arch Linux developers continue to use it.

**Comment by Antynea** [comment]
Okay,
I had forgotten that the hooks files, were available in the initramfs, and the default shell of the initramfs is "ash".
so there are no errors.

**Comment by petsam** [comment]
I appreciate the info.
Sorry for the false alarm. One more piece of knowledge in my bag ;)
