### ISSUE TITLE
Document where and what the grub-btrfs script is looking for

### ISSUE THREAD

**Issue by amigalemming** [Antynea/grub-btrfs#143]
I am uncertain where and what `41_snapshots-btrfs` is looking for.
I have two btrfs partitions, one for Debian and one for Ubuntu, each having two subvolumes for different versions of the according GNU/Linux distributions. My idea: I start with a subvolume for, say, Debian 10/Buster, clone that subvolume and upgrade it to Debian 11/Bullseye installation. Now I can test the new Bullseye installation but can always switch back to old Buster at every boot.
The Debian partition contains only two subvolumes `@buster` and `@bullseye` and no other files at the top-level. However, `41_snapshots-btrfs` does not seem to find them. Should it?
Say, I use Debian to install the Grub bootloader. Can I expect that the two Ubuntu subvolumes are recognized, as well. In my setup, they don't.
grub-btrfs script says:
~~~~
Detecting snapshots ...
Info: Separate boot partition not detected 
No snapshots found.
If you think an error has occurred , please file a bug report at " https://github.com/Antynea/grub-btrfs "
Nothing to do. Abort.
done
~~~~
So, what must a snapshot look like? What and where is grub-btrfs looking for? Can I configure the behaviour? I have not found anything promising in `grub-btrfs/config`.

**Comment by Antynea** [comment]
> However, 41_snapshots-btrfs does not seem to find them. Should it?

No

> So, what must a snapshot look like?

https://btrfs.wiki.kernel.org/index.php/SysadminGuide#Snapshots

> What and where is grub-btrfs looking for?

https://github.com/Antynea/grub-btrfs#what-does-grub-btrfs-v4xx-do-

> Can I configure the behaviour? 

Nope. **Grub-btrfs** support **btrfs snapshots** only.
Searching a bootable system on **different subvolumes** isn't implemented.
