### ISSUE TITLE
`rootflags=subvol=` created twice

### ISSUE THREAD

**Issue by wesbarnett** [Antynea/grub-btrfs#15]
I have a specific subvolume I mount as root using `rootflags=subvol=subvol_root`. When I recreate the GRUB configuration file with this package installed, it creates another `rootflags=subvol=` entry, one for the one I've specified and then one for the snapshot.

**Comment by Antynea** [comment]
hi,

grub-btrfs list only all the existing snapshots on the root filesystem.

btrfs-prog is used for this:

btrfs subvolume -sa /
list only the existing snapshots on the root file system

btrfs subvolume -a /
list all existing subvolumes and snapshots on the root file system

grub-btrfs use first command.

if grub-btrfs detects your own subvolume, is that you create a snapshot, not a subvolume.

please refer to [wiki btrfs](https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-subvolume)

**Comment by wesbarnett** [comment]
I understand this. However, I already have `rootflags=subvol=` set in my kernel parameters. Instead of replacing my setting, grub-btrfs is adding another `rootflags=subvol=` to my kernel parameters. So I end up with the situation where two subvolumes are specified in two different `rootflags=subvol=` for one GRUB entry.

For example:

`linux "/subvol_snapshots/232/snapshot/boot/vmlinuz-linux" root=UUID=60d2f44d-87a1-4377-bb7c-ccd161d59a78 rw **rootflags=subvol="subvol_snapshots/232/snapshot"** cryptdevice=/dev/disk/by-uuid/bb7396f5-f246-4edf-9f1f-298c9ca560ac:cryptroot:allow-discards modprobe.blacklist=ehci_pci i915.semaphores=1 **rootflags=subvol=subvol_root** quiet loglevel=3 udev.log-priority=3`

**Comment by Antynea** [comment]
ok i understand.

you specified yourself "rootflags=subvol=" in the file "/etc/default/grub"

grub-btrfs use variables : 
GRUB_CMDLINE_LINUX_DEFAULT="" and GRUB_CMDLINE_LINUX=""
to get the parameters pass to the kernel.

**Comment by wesbarnett** [comment]
Right. grub-btrfs is not able to properly handle this case currently, where the user already has `rootflags=subvol=` in the kernel parameters.

**Comment by Antynea** [comment]
actually , it's not easy to find a universal solution
any suggestion is appreciated

**Comment by wesbarnett** [comment]
I have some ideas that I'm working on. Interestingly enough, even the default menu items end up being duplicated (but with the same subvol, so it's fine).

**Comment by wesbarnett** [comment]
Well, it looks like I don't even need to specify `rootflags` myself. GRUB autodetects it correctly, so it showing up double was an effect of me specifying it as well. So this can be closed.
