### ISSUE TITLE
Disabling check for snapshot 1

### ISSUE THREAD

**Issue by tommytran732** [Antynea/grub-btrfs#152]
Hi, 

I am getting this warning when I try to do grub-mkconfig

![image](https://user-images.githubusercontent.com/57488583/116966352-f10d4400-ac7d-11eb-9b71-2cb81614d300.png)

While this is accurate, I do not have snapshot 1, the message "snapshot check failed. not adding snapshot 1" is rather annoying, since I am following SUSE's partitioning scheme and snapshot 1 is not necessary at all. I wonder if there is a way to disable the check for snapshot 1 specifically?

Thank you

**Comment by Antynea** [comment]
hello,
This message shouldn't appear.
Can you provide the output of the following commands:
```sudo btrfs sub list -sa /``` #List your snapshots
```sudo bash -x /etc/grub.d/41_snapshots-btrfs > /dev/null 2>&1 | curl -F 'sprunge=<-' http://sprunge.us``` #Generates a link

**Comment by tommytran732** [comment]
![image](https://user-images.githubusercontent.com/57488583/116972783-8bbf5000-ac89-11eb-8690-e95e8cd5b748.png)
http://sprunge.us/0yjvUv

**Comment by tommytran732** [comment]
This is all of my subvols:

![image](https://user-images.githubusercontent.com/57488583/116972993-d93bbd00-ac89-11eb-83e4-34f3a5be8f59.png)

**Comment by Antynea** [comment]
Thanks,


Link is empty,
```bash /etc/grub.d/41_snapshots-btrfs``` return a error ?

**Comment by tommytran732** [comment]
![image](https://user-images.githubusercontent.com/57488583/116974661-73046980-ac8c-11eb-9ee9-a014f7c2ba1c.png)

**Comment by Antynea** [comment]
Ok, ```sudo``` is problematic

Login as root and run:
```bash -x /etc/grub.d/41_snapshots-btrfs > /dev/null 2>&1 | curl -F 'sprunge=<-' http://sprunge.us```

**Comment by tommytran732** [comment]
There you go: http://sprunge.us/jxfMwT

**Comment by Antynea** [comment]
Last try with:
```sudo bash -x /etc/grub.d/41_snapshots-btrfs 2>&1 | curl -F 'sprunge=<-' http://sprunge.us```
Otherwise, share the `dump.txt` file generated with
```sudo bash -x /etc/grub.d/41_snapshots-btrfs > dump.txt 2>&1```

**Comment by tommytran732** [comment]
There you go :)

[dump.txt](https://github.com/Antynea/grub-btrfs/files/6419985/dump.txt)

**Comment by Antynea** [comment]
Thanks,
Take time to analyze your file.
Come back to you later.

**Comment by tommytran732** [comment]
> Thanks,
> Take time to analyze your file.
> Come back to you later.

Thank you so much for your help!

**Comment by Antynea** [comment]
The error message comes from the following command:
```snapper --no-dbus -t 0 -c root list --disable-used-space```

I don't know why snapper is complaining, I can't find any information about it.
This is not a blocking error message, but indicates a problem with snapper.

Can you try this command in a terminal ? (with/without `sudo`)
```snapper --no-dbus -t 0 -c root list --disable-used-space```

If the message appears in your terminal, try to find a solution with snapper community.

I know that the message is not elegant, I could eventually hide it, but I think it is important to display it, to warn the user of a malfunction in `snapper`.

**Comment by tommytran732** [comment]
![image](https://user-images.githubusercontent.com/57488583/116986537-e661a780-ac9b-11eb-8a31-d37122104e02.png)

You are right, this was an issue with snapper. It probably expects the initial root file systems to always be there or something. Maybe I will just rename my current snapshot to 1 and be done with it.

A bit unrelated, but I also nice a weird behavior and I am not sure if this is a grub, grub-btrfs or snapper issue yet, so I hope you could advise me. I will open another issue if it indeed is a grub-btrfs issue.

I have already set my grub to always boot from the default BTRFS snapshot (by removing the rootflags from 10_linux and 20_linux_xen). However, grub-mkconfig will still set the initramfs and kernel to be specifically within the current snapshot rather than from the default subvol. The kernel and initramfs are snapshotted with the system and are not in their own partition/subvolume.

![image](https://user-images.githubusercontent.com/57488583/116987268-d7c7c000-ac9c-11eb-922a-1148dfa58f77.png)

**Comment by Antynea** [comment]
What you want to do, is not easily achievable.

This behavior is normal, this is the ```make_system_path_relative_to_its_root``` variable in the grub configuration files (00_hedaer, 10_linux, etc...).

This variable calls the "grub-mkrelpath" binary. 
You can try in a terminal ```/usr/bin/grub-mkrelpath --help```
There are no options for this binary. 

You can try changing the variable in the ```grub-mkconfig_lib``` file, but you will break `Grub` `Grub-btrfs` `os-prober` and others that have this variable as a dependency.

The least risky solution would be to create your own custom menu in `41_custom file`.

**Comment by tommytran732** [comment]
> What you want to do, is not easily achievable.
> 
> This behavior is normal, this is the `make_system_path_relative_to_its_root` variable in the grub configuration files (00_hedaer, 10_linux, etc...).
> 
> This variable calls the "grub-mkrelpath" binary.
> You can try in a terminal `/usr/bin/grub-mkrelpath --help`
> There are no options for this binary.
> 
> You can try changing the variable in the `grub-mkconfig_lib` file, but you will break `Grub` `Grub-btrfs` `os-prober` and others that have this variable as a dependency.
> 
> The least risky solution would be to create your own custom menu in `41_custom file`.

Ah got it, thank you. I will close this issue now.
