### ISSUE TITLE
grub-btrfs finds snapshots outside of PathModified

### ISSUE THREAD

**Issue by Toorero** [Antynea/grub-btrfs#153]
I have grub-btrfs setup for Timeshift as explained in the README.md but grub-btrfs seems to find my read-only "backup" snapshots as well saved under `/run/timeshift/backup/timeshift-btrfs/readonly`.

Is this expected behaviour or am I just missing something. If so how may I prevent grub-btrfs of picking up those pseudo snapshots.

**Comment by Antynea** [comment]
This is expected behavior.

`grub-btrfs` uses the command:
`btrfs subvolume list -sa /`
to find the snapshots.

If you need to exclude snapshots
refer to :
```
# Ignore specific path during run "grub-mkconfig".
# Only exact paths are ignored.
# e.g : if `specific path` = @, only `@` snapshot will be ignored.
# Default: ("@")
GRUB_BTRFS_IGNORE_SPECIFIC_PATH=("@")

# Ignore prefix path during run "grub-mkconfig".
# Any path starting with the specified string will be ignored.
# e.g : if `prefix path` = @, all snapshots beginning with "@/..." will be ignored.
# Default: ("var/lib/docker" "@var/lib/docker" "@/var/lib/docker")
GRUB_BTRFS_IGNORE_PREFIX_PATH=("var/lib/docker" "@var/lib/docker" "@/var/lib/docker")
```
in  config file.

**Comment by Toorero** [comment]
Thank you very much. Closing this "issue" then.
