### ISSUE TITLE
grub doesn't show snapshot of a snapshot in the list

### ISSUE THREAD

**Issue by eternalbit** [Antynea/grub-btrfs#155]
I'm not sure if this might be related to #154

My setup is as follows:

- The root of the btrfs filesystem is mounted at `/mnt/subvols` ... so this is where all subvolumes are
- the `@` subvolume is mounted at `/`
- snapshots of `@` are also stored in `/mnt/subvols`
- `@` also contains `/boot`
- `/var/lib/machines` and `/var/lib/portables` and `/var/tmp` are separate subvolumes

Situation:
- I booted with `@`mounted at `/`
- I created a ro snapshot of `@` named `2021-06`
- from `2021-06` I created a rw snapshot named `2021-06-rw`
- let's say my `@` stopped booting/working ... `2021-06-rw` is listed as a snapshot in grub and I successfully booted from it
- I then create another ro snapshot of the booted `2021-06-rw` named `2021-06-rw_bak` and from this another rw snapshot named `2021-06-rw_bak-rw` to have a copy of the working backup with which I can experiment without destroying my last working system

Problem:

- `2021-06-rw_bak-rw` (and also `2021-06-rw_bak`) doesn't show up in the grub list of snapshots so I can't select it to boot from

Additional info:

- `grub-btrfs.path` is enabled
- `grub-btrfs.service` is shown as `static`
- the path in `grub-btrfs.path` is set to `PathModified=/mnt/subvols` (I noticed I had a trailing `/` at the end; removed it; hope it wasn't the cause)
- the name of the `.mount` unit according to `systemctl list-units -t mount` is `mnt-btrfs\x2dsubvols\x2droot.mount` so I set this in `grub-btrfs.path` ... or should I only set the last part `x2droot.mount` ?
- when I run `update-grub` it correctly detects and lists all four snapshots
- I'm using btrfs-grub 4.9-1

**Comment by eternalbit** [comment]
Sorry @Antynea ... I forgot to first have a look in the closed issues ... my bad. I'll look there now and possibly delete this if I find a solution on my own.

**Comment by Kr1ss-XD** [comment]
Hi @eternalbit,

Since you described that your `/boot` directory is part of the `@` subvolume (which is mounted at `/`), I'm assuming the reason for the two newer snapshots not appearing in your grub menu is because you created them while booted into another snapshot.

Hence, the modified `grub-btrfs.conf` is _inside_ this snapshot, while on a reboot, the main one from the `@` subvolume is used (which doesn't contain the references to the new snapshots).

Hope this is helpful. _Cheers !_

**Comment by eternalbit** [comment]
Hi @Kr1ss-XD .. thanks.

(Without having tried to find out the inner workings of `update-grub` and `mkinitcpio`) ... I assumed that - when executed - they'd somehow automatically detect, which subvolume is currently booted and modify all files involved in the boot process, so that from next boot on the `/boot` inside the currently mounted (as `/`) subvolume/snapshot is used, instead of just always the `/boot` inside `@`.

**Comment by eternalbit** [comment]
Does this mean I'd simply have to copy `grub-btrfs.conf` from my `/mnt/subvols/snapshotname/boot` to `/mnt/subvols/@/boot` and then I'd see the snapshots in grub and be able to boot them?

**Comment by Kr1ss-XD** [comment]
You might just have to `grub-install` right after creating the new snapshots, to make the `grub{,-btrfs}.cfg` files of the subvolume that's currently booted the active ones.

Here an interesting thread, esp. this [comment](https://bbs.archlinux.org/viewtopic.php?pid=1615360#p1615360 "[SOLVED] Btrfs root with subvolumes question / Installation - comment") from the Archlinux BBS.

I hope that's what you're looking for.

**Comment by eternalbit** [comment]
Thanks @Kr1ss-XD ... after reading the discussion I was indeed wondering whether I'd have to deal with the default subvolume.

So now it's clear.

Since I'm always doing things on my only machine for daily use I'll wait with trying the `grub-install` thing, until I run into some situation when I actually need it ... don't want to unnecessarily risk that things are working right now.

I'll close this issue since it's most probably solved.

Thanks again.
