### ISSUE TITLE
Issue with the TPM module on Grub 2.06

### ISSUE THREAD

**Issue by tommytran732** [Antynea/grub-btrfs#156]
Hi,

I am using Arch Linux. Just a few weeks ago, GRUB 2.04 was still being used, and there was no problem with grub-btrfs. However since Arch updated to GRUB 2.06, GRUB modules must be included in grub-install if the user wish to use Secure Boot, as GRUB will no longer allow side loading modules when Secure Boot is active.

In order to use my own secure boot keys and not shim, I must include the tpm module in my grubx64.efi stub when running grub-install. However, when the tpm module is included in the grubx64.ef stub, attempting to boot from a readonly snapshot on GRUB menu will cause "Unkown TPM error". Even simply accessing the "Arch Snapshots" menu and backing out, booting normally will cause that error as well.

I don't know why the grub-btrfs menu is having issue if the TPM module is in the grubx64.efi stub, so I hope you could have a look.

Thank you

**Comment by tommytran732** [comment]
Just to clarify, I installed GRUB with `grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB --modules="normal test efi_gop efi_uga search echo linux all_video gfxmenu gfxterm_background gfxterm_menu gfxterm loadenv configfile tpm" --disable-shim-lock`

**Comment by tommytran732** [comment]
Okay, so I seem to have somewhat solved this myself. I will explain what I did here in case someone needs it:

To verify the kernel when Secure Boot is active, grub needs the tpm.mod, and since GRUB 2.06 disabled module sideloading, we need to include tpm.mod in the grubx64.efi stub.

This will cause it to attempt to do measured boot, however (https://www.gnu.org/software/grub/manual/grub/html_node/Measured-Boot.html), because I obviously do not have measured boot set up yet. It causes GRUB to complain about the TPM error.

The solution turned out to be quite simple: Still  include tpm.mod in the grub image, but disable the TPM in your firmware (or set up measured boot if you know how to).

**Comment by Antynea** [comment]
Hello

I had started to test but didn't have the option to enable secure boot on my test machine.
However, I could activate tpm 2.0
I couldn't reproduce your setup, but I didn't detect anything wrong.
Thank you for your investigations and your feedback.

**Comment by pandom79** [comment]
> Okay, so I seem to have somewhat solved this myself. I will explain what I did here in case someone needs it:
> 
> To verify the kernel when Secure Boot is active, grub needs the tpm.mod, and since GRUB 2.06 disabled module sideloading, we need to include tpm.mod in the grubx64.efi stub.
> 
> This will cause it to attempt to do measured boot, however (https://www.gnu.org/software/grub/manual/grub/html_node/Measured-Boot.html), because I obviously do not have measured boot set up yet. It causes GRUB to complain about the TPM error.
> 
> The solution turned out to be quite simple: Still include tpm.mod in the grub image, but disable the TPM in your firmware (or set up measured boot if you know how to).

Hi, 
I have the same problem which I partially resolved via this command:

`grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB --modules="normal test efi_gop efi_uga search echo linux all_video gfxmenu gfxterm_background gfxterm_menu gfxterm loadenv configfile tpm" --disable-shim-lock`

Now, it can boot up with secure boot enabled but I don't see properly the grub menu.
Amongst the various modules, which should i remove/add to try ?

**Comment by tommytran732** [comment]
> > Okay, so I seem to have somewhat solved this myself. I will explain what I did here in case someone needs it:
> > To verify the kernel when Secure Boot is active, grub needs the tpm.mod, and since GRUB 2.06 disabled module sideloading, we need to include tpm.mod in the grubx64.efi stub.
> > This will cause it to attempt to do measured boot, however (https://www.gnu.org/software/grub/manual/grub/html_node/Measured-Boot.html), because I obviously do not have measured boot set up yet. It causes GRUB to complain about the TPM error.
> > The solution turned out to be quite simple: Still include tpm.mod in the grub image, but disable the TPM in your firmware (or set up measured boot if you know how to).
> 
> Hi, I have the same problem which I partially resolved via this command:
> 
> `grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB --modules="normal test efi_gop efi_uga search echo linux all_video gfxmenu gfxterm_background gfxterm_menu gfxterm loadenv configfile tpm" --disable-shim-lock`
> 
> Now, it can boot up with secure boot enabled but I don't see properly the grub menu. Amongst the various modules, which should i remove/add to try ?

Hi, sorry for the late reply, did you ever figure this out?
