### ISSUE TITLE
Whitelist entries based on description

### ISSUE THREAD

**Issue by r0skar** [Antynea/grub-btrfs#157]
Hi - thanks for your work on this! It works perfectly :+1: 

I am using snapper and I would like to disable all of the timeline snaps and only show snapshots, which  I have taken manually. Ideally, I could filter them based on the `--description` I add to the snapshot. The grub menu shows the `description` field in the entries table, but is there a way to filter by it?

Maybe there is a way to achieve this with `GRUB_BTRFS_IGNORE_PREFIX_PATH`(?) However, the paths dont include a the description text..

**Comment by Antynea** [comment]
hello,

I can add filters.
filter by 
"type" : `number, timeline, pre, post`
and by 
"description" : `specific string or not ?`
