### ISSUE TITLE
/boot on a separate btrfs subvolume

### ISSUE THREAD

**Issue by as400l** [Antynea/grub-btrfs#161]
This is actually not an issue but rather a question or a possible improvement.

I have boot on a separate partition in a btrfs subvolume. Since my root is on a LUKS2 container there is no other way - boot has to be on a separate partition.

Now the question is - if I make a snapshot of the boot subvolume is there any way that I can use the snapshot for booting into the root snapshots that I have ?

**Comment by Hxppdv** [comment]
Maybe [this post](https://www.reddit.com/r/btrfs/comments/sbm5r0/idea_get_real_boot_environments_with_an/) will help.
