### ISSUE TITLE
Generates two identical grub menuentries for snapper snapshots (version 4.10)

### ISSUE THREAD

**Issue by truly-irham** [Antynea/grub-btrfs#168]
Hi there, 

Upon upgrading grub-btrfs to the latest version (4.10), grub-btrfs generates two identical grub menuentries for snapshots whenever I update the grub (manually or/and when installing packages using pacman). As a workaround, I downgrade this package to the previous version which is v4.9 and now this issue is resolved. Followings are some details of my current setup:

OS: Arch Linux
Kernel: 5.14.7-zen1-1-zen
snapshot tool: snapper 0.9.1
other tool: snap-pac-grub 1.0.4

Followings are all of the grub menuentries (with exact sequence):

Arch Linux
Advanced options for Arch Linux
Arch Linux snapshots
UEFI Firmware Settings
Arch Linux snapshots

I will help you provide more details if you need them for troubleshooting purpose.

As you can see from above menuentries, there are two "Arch Linux snapshots" and all of the subfolders and snapshots are identical to each other. Although I have two configs for my snapper (root and home), the snapshots appear in grub are ONLY for root, and as I said, both of the menuentries are IDENTICAL (I have checked all of the subfolders and snapshots to confirm it). I have also done troubleshooting this issue by downgrading grub-btrfs from v4.10 to v4.9 and this issue is resolved. At first, I tried to uninstall snap-pac-grub to see if this can be the culprit for this, but uninstalling snap-pac-grub just disable the pacman hook for snapshotting, and updating grub using grub-mkconfig still generates two identical snapshots menuentries after removing snap-pac-grub. Is it a new implemented feature? If so, I'm really sorry for my ignorance. If it is a bug, I appreciate any help from you guys. Thank you and keep up the great work :D

**Comment by truly-irham** [comment]
I also want to add that, upon upgrading grub-btrfs to v4.10 from v4.9, I got the following warning:

warning: could not get file information for etc/grub.d/41_snapshots-btrfs

**Comment by Antynea** [comment]
Hello,

Thanks for your feedback.

Can you uninstall grub-btrfs, then make sure that the `/etc/grub.d/41_snapshots-btrfs` is correctly deleted.
Otherwise delete it and install grub-btrfs 4.10 again.

**Comment by truly-irham** [comment]
Thanks for the reply. Since I downgrade the package by issuing undochange command using snapper, the file 41_snapshots-btrfs isnt there anymore. When I upgrade btrfs-grub again to v4.10, the issue is still reproduced. Here are all of the dicrectories under /etc/grub.d for your reference:

00_header                             41_linux_proxy          46_uefi-firmware_proxy  bin
06_grub-customizer_menu_color_helper  42_linux_xen            47_fwupd                proxifiedScripts
10_linux_proxy                        43_os-prober            48_custom               README
35_fwupd                              44_uefi-firmware_proxy  49_snapshots-btrfs
40_custom_proxy                       45_custom_proxy         backup

See that there is a directory "49_snapshots-btrfs". Is this could be the culprit for the multiple menuentries?

**Comment by truly-irham** [comment]
Im sorry for the messed up directories. Here you go (better listed):

00_header
06_grub-customizer_menu_color_helper
10_linux_proxy
35_fwupd
40_custom_proxy
41_linux_proxy
42_linux_xen
43_os-prober
44_uefi-firmware_proxy
45_custom_proxy
46_uefi-firmware_proxy
47_fwupd
48_custom
49_snapshots-btrfs
backup
bin
proxifiedScripts
README

**Comment by Antynea** [comment]
> Is this could be the culprit for the multiple menuentries ?

Yes. delete it. 
`grub-btrfs` install 41_snapshots-btrfs` not 49...

**Comment by Antynea** [comment]
problem solved ?
If not, re-open.

**Comment by truly-irham** [comment]
Hi, sorry for the delay. Yes by deleting 49_snapshots-btrfs, grub-btrfs will only generate one menuentry for the snapshots. Thanks for your time @Antynea and keep up the good work!

**Comment by truly-irham** [comment]
But can I know whether is it alright to have same grub.d number? Because in that directory, I also have 41_linux_proxy, so right now I have two 41 initials, ie 41_linux_proxy and 41_snapshots-btrfs. Since this issue is now resolved, this question is just to clarify things up and I wont reopen this issue.

**Comment by Antynea** [comment]
The number represents the processing priority of the files.
Grub will read the files in alphabetical order and generate its menu accordingly.

> But can I know whether is it alright to have same grub.d number ?

It doesn't matter.
Let's say you can change this number yourself, if you want to see a menu entry appear in a different order.

That's certainly what you did with 49_snapshots-btrfs....
but you must not have remembered it ...
or you have used grub-customizer, which does it for you.

**Comment by truly-irham** [comment]
Alright that clears things up. Thank you again @Antynea
