### ISSUE TITLE
Docker snapshots being detected.

### ISSUE THREAD

**Issue by Psykar** [Antynea/grub-btrfs#17]
Bit of a hairy one.
As the docker snapshots include linux kernels, autodetect is finding them and adding them to the boot menu.
Interestingly I actually think it might be possible to boot them (haven't checked yet) but it's very unlikely that you'd ever actually want to do this.

```
> Attempting to update grub-cfg
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-linux
Found initrd image: /boot/initramfs-linux.img
Found fallback initramfs image: /boot/initramfs-linux-fallback.img
###### - Grub-btrfs: Auto-detect - ######
# Found Snapshot: 2016-03-31 10:26:52 var/lib/docker/btrfs/subvolumes/74040aee4fa98f7dc6bbdcd7df8e361352c7d9dc55440ee54f312eda1f52079c
# Found Snapshot: 2016-03-31 10:26:50 var/lib/docker/btrfs/subvolumes/74040aee4fa98f7dc6bbdcd7df8e361352c7d9dc55440ee54f312eda1f52079c-init
# Found Snapshot: 2016-03-31 10:26:46 var/lib/docker/btrfs/subvolumes/b61091160bd9583172cf1a4f81be99b244aefa0674f1e04cd5990928552e0825
# Found Snapshot: 2016-03-31 10:26:45 var/lib/docker/btrfs/subvolumes/b61091160bd9583172cf1a4f81be99b244aefa0674f1e04cd5990928552e0825-init
# Found Snapshot: 2016-03-31 10:26:42 var/lib/docker/btrfs/subvolumes/5bc5ce665173d6fbc356096f938e8ebf4b3b69e2aa6c779c88e5ba19edcacd66
# Found Snapshot: 2016-03-31 10:26:42 var/lib/docker/btrfs/subvolumes/5bc5ce665173d6fbc356096f938e8ebf4b3b69e2aa6c779c88e5ba19edcacd66-init
# Found Snapshot: 2016-03-31 10:25:00 .snapshots/913/snapshot
# Found Snapshot: 2016-03-31 10:24:41 var/lib/docker/btrfs/subvolumes/805c0ef9f093c6fc2685ec9592485c2bca478f3cd0b8716533d0e78a3f07aa20
# Found Snapshot: 2016-03-31 10:24:36 var/lib/docker/btrfs/subvolumes/805c0ef9f093c6fc2685ec9592485c2bca478f3cd0b8716533d0e78a3f07aa20-init
# Found Snapshot: 2016-03-31 10:22:22 .snapshots/912/snapshot
# Found Snapshot: 2016-03-31 10:00:27 .snapshots/911/snapshot
###### - Grub-btrfs: Auto-detect - ######
```

**Comment by Antynea** [comment]
Currently , the script detects the presence of the `/boot` folder in snapshot.
I could add an option to detect the dock folder, free user has to activate or not.

**Comment by Psykar** [comment]
Not too fussed, I'd think checking if 'docker' is in the path *to* the snapshot makes most sense though?
No rush on it, increasing the number of snapshots added to the menu suffices as a workaround for now.

**Comment by ar-qun** [comment]
A more universal option would be to add a way to ignore path or volume. What if docker/nspawn images are on separate partition? The docker folder may be just a mount point.

**Comment by Antynea** [comment]
> What if docker/nspawn images are on separate partition?

the script detects only snapshots present on the root partition via :
`btrfs subvolume list -sa --sort=+rootid /`
`-s : list snapshots only in the filesystem`
> A more universal option would be to add a way to ignore path or volume

Good idea, when I have a moment I would do this

**Comment by Antynea** [comment]
i added a way to ignore path
any feedback is apreciate

to use it : 
add `GRUB_BTRFS_IGNORE_SPECIFIC_PATH=("var/lib/docker")`
in `/etc/default/grub`

grub-mkconfig will skip all snapshot found in the path specified

Warning : copy exactly the right path (var/lib/docker , not /var/lib/docker/), do not put the full path

**Comment by Psykar** [comment]
Thanks :) will let you know if there are issues :)
