### ISSUE TITLE
Grub can't detect other partitions than Manjaro

### ISSUE THREAD

**Issue by DavutHaxor** [Antynea/grub-btrfs#171]
I want it to detect Windows but it can't. 
`sudo update-grub output: 
Generating grub configuration file ...
Found theme: /usr/share/grub/themes/manjaro/theme.txt
Found linux image: /boot/vmlinuz-5.14-x86_64
Found initrd image: /boot/intel-ucode.img /boot/initramfs-5.14-x86_64.img
Found initrd fallback image: /boot/initramfs-5.14-x86_64-fallback.img
Found linux image: /boot/vmlinuz-5.10-x86_64
Found initrd image: /boot/intel-ucode.img /boot/initramfs-5.10-x86_64.img
Found initrd fallback image: /boot/initramfs-5.10-x86_64-fallback.img
Found linux image: /boot/vmlinuz-4.19-x86_64
Found initrd image: /boot/intel-ucode.img /boot/initramfs-4.19-x86_64.img
Found initrd fallback image: /boot/initramfs-4.19-x86_64-fallback.img
Warning: os-prober will be executed to detect other bootable partitions.
Its output will be used to detect bootable binaries on them and create new boot entries.
Adding boot menu entry for UEFI Firmware Settings ...
Detecting snapshots ...
Root partition isn't a btrfs filesystem.
This script only supports snapshots of the btrfs filesystem.
If you think an error has occurred , please file a bug report at " https://github.com/Antynea/grub-btrfs "
Nothing to do. Abort.
Found memtest86+ image: /boot/memtest86+/memtest.bin
done`

**Comment by Antynea** [comment]
How does this relate to the[ current project](https://github.com/Antynea/grub-btrfs#description-) ?
