### ISSUE TITLE
grub-script-check: No such file or directory

### ISSUE THREAD

**Issue by theclakuh** [Antynea/grub-btrfs#176]
I am using Fedora 34 with timeshift which snapshots I want to be able to boot. However,  `grub-btrfs` is no longer in fedora repos, so I followed the README tutorial.

After installing `grub-btrfs` and creating the first snapshots using timeshift I was not able to create grub entries including the snapshots with the following error:
```
$> sudo grub2-mkconfig -o /boot/grub2/grub.cfg
[sudo] password for suuser: 
Generating grub configuration file ...
Adding boot menu entry for UEFI Firmware Settings ...
Detecting snapshots ...
Info: Separate boot partition detected 
Found snapshot: 2021-10-19 19:38:20 | timeshift-btrfs/snapshots/2021-10-19_19-38-19/@
Found snapshot: 2021-10-19 19:33:43 | timeshift-btrfs/snapshots/2021-10-19_19-33-43/@
Found 2 snapshot(s)
/etc/grub.d/41_snapshots-btrfs: line 598: /usr/bin/grub-script-check: No such file or directory
Syntax errors are detected in generated grub-btrfs.cfg file.
If you think an error has occurred , please file a bug report at " https://github.com/Antynea/grub-btrfs "
Unmount /tmp/grub-btrfs.k20ag9qqVK .. Success
done
```

Dispite the misleading `Success` there is no option or config to tell the scripts about the `script-check` tool, which is `grub2-script-check` in my case. 

After creating a symbolic link  `grub-btrfs` worked like charm. 
```
$> which grub2-script-check
/usr/bin/grub2-script-check
$> cd /usr/bin/ && ln -s grub2-script-check grub-script-check && cd -
``` 

It would be nice to have another config like `GRUB_BTRFS_MKCONFIG=/usr/bin/grub2-mkconfig` to tell the check-tool.

**Comment by Antynea** [comment]
hello,
Thanks for your feedback
Fix in progress, following your recommendations.

**Comment by trofosila** [comment]
Not the original op, but can confirm https://github.com/Antynea/grub-btrfs/pull/177 fixed the issue for me (on Fedora 35, UEFI boot).

**Comment by Antynea** [comment]
@trofosila , thank you.
