### ISSUE TITLE
grub.cfg failes to generate

### ISSUE THREAD

**Issue by huegelc** [Antynea/grub-btrfs#18]
Here is the output of:

` grub-mkconfig -o /boot/grub/grub.cfg` 

    ###### - Grub-btrfs: Auto-detect - ######
    ###### - Grub-btrfs: Auto-detect - ######
    error: syntax error.
    error: Incorrect command.
    error: syntax error.   
    Syntax error at line 173
    Syntax errors are detected in generated GRUB config file.
    Ensure that there are no errors in /etc/default/grub
    and /etc/grub.d/* files or please file a bug report with
    /boot/grub/grub.cfg.new file attached.
    done

**Comment by Antynea** [comment]
Can you provide us with the output from :

```
uname -srvmo
pacman -Qs grub
pacman -Qs bash
pacman -Qs btrfs
btrfs subvolume list -sa --sort=+rootid / | curl -F 'sprunge=<-' http://sprunge.us
blkid
cat /etc/fstab
grub-probe --target="fs" "/boot"
grub-probe --target="fs_uuid" "/boot"
grub-probe --target="fs" "/"
grub-probe --target="fs_uuid" "/"
ls -al /boot
ls -al /etc/grub.d/
cat /etc/grub.d/41_snapshots-btrfs > /dev/null 2>&1 | curl -F 'sprunge=<-' http://sprunge.us
cat /etc/default/grub > /dev/null 2>&1 | curl -F 'sprunge=<-' http://sprunge.us
sh /etc/grub.d/41_snapshots-btrfs > /dev/null 2>&1 | curl -F 'sprunge=<-' http://sprunge.us
grub-mkconfig -o /boot/grub/grub.cfg > /dev/null 2>&1 | curl -F 'sprunge=<-' http://sprunge.us
```

**Comment by huegelc** [comment]
OK, i figured it out. This error message is displayed when no snapshots are available under .snapshots . Maybe you could check the availability of snapshots first before a error message is thrown?!

**Comment by Antynea** [comment]
yes, i know, grub is evil on the detection of incorrect menu.
I apologize, I do not have access to different vm to correct the code now.
I done soon

**Comment by Antynea** [comment]
fixed
