### ISSUE TITLE
openSUSE unbootable GRUB snapshots due to missing initrd

### ISSUE THREAD

**Issue by geckolinux** [Antynea/grub-btrfs#183]
Hi there, this is a continuation of #180 regarding using grub-btrfs on an openSUSE Tumbleweed system (and also hopefully openSUSE Leap) installed from a custom ISO with the Calamares installer.

This is what I'm getting:

![Screenshot from 2021-11-20 18-00-42](https://user-images.githubusercontent.com/2692138/142743268-d4021897-0e82-465d-b8fe-103b6c5937bc.png)

![Screenshot from 2021-11-20 17-59-54](https://user-images.githubusercontent.com/2692138/142743266-d2c3d1d3-82a8-470e-9fe5-585882edf1d4.png)

Here's what my test system looks like:

```
sam@sam-virtualbox:~> cat /etc/fstab 
UUID=1d9d72f6-8ef9-4440-a542-4ba1a279b8fb /              btrfs   subvol=/@,defaults,noatime,space_cache,autodefrag,compress=zstd 0 0
UUID=1d9d72f6-8ef9-4440-a542-4ba1a279b8fb /home          btrfs   subvol=/@home,defaults,noatime,space_cache,autodefrag,compress=zstd 0 0
UUID=1d9d72f6-8ef9-4440-a542-4ba1a279b8fb /var/cache     btrfs   subvol=/@cache,defaults,noatime,space_cache,autodefrag,compress=zstd 0 0
UUID=1d9d72f6-8ef9-4440-a542-4ba1a279b8fb /var/log       btrfs   subvol=/@log,defaults,noatime,space_cache,autodefrag,compress=zstd 0 0

sam@sam-virtualbox:~> sudo btrfs sub list /
ID 257 gen 158 top level 5 path @
ID 258 gen 158 top level 5 path @home
ID 259 gen 158 top level 5 path @cache
ID 260 gen 158 top level 5 path @log
ID 267 gen 149 top level 257 path .snapshots
ID 268 gen 105 top level 258 path @home/.snapshots
ID 269 gen 112 top level 267 path .snapshots/1/snapshot
ID 270 gen 113 top level 267 path .snapshots/2/snapshot
[...]
ID 286 gen 148 top level 267 path .snapshots/18/snapshot

```

From this [comment](https://github.com/Antynea/grub-btrfs/issues/180#issuecomment-974789761) by @pandom79 it looks like it's missing the initrd, and @Antynea [discovered](https://github.com/Antynea/grub-btrfs/issues/180#issuecomment-975689986) that the initrd list is no longer in sync with the GRUB list.

Thanks for the help!

**Comment by Antynea** [comment]
Can you test the patch, please.
This should fix this issue.

**Comment by pandom79** [comment]
It works for me. :+1:

**Comment by geckolinux** [comment]
Works great! Thanks very much for this fix.
#160 and #179 would improve thing more, but this is an excellent start that at least allows for booting and switching to a tty.

**Comment by pandom79** [comment]
> Works great! Thanks very much for this fix. #160 and #179 would improve things even more, but this is an excellent start that at least allows for booting and switching to a tty.

Probably, we cannot correctly boot up the snapshot because many services write in the /var/log folder which (in my case and maybe yours too) is not mounted in a separate subvol and thus they cannot write into because it is read-only causing the error.
Somewhere I read that to mount the snapshot on overlay fs could be a nice and elegant solution because it guarantees the write in a non-persistent way. @Antynea, feel you free to correct me if I'm wronging.
That means that for our btrfs layout, it works great. At least, we can run "snapper rollback" from a tty.

**Comment by Antynea** [comment]
@pandom79 , you are right.
Another solution that might be considered is to use `systemd.volatile=state`. (Only if you're using `systemd`)
See https://github.com/Antynea/grub-btrfs/issues/92#issuecomment-966869223

To do this:
You must edit the kernel command line in the `Grub` menu and add `systemd.volatile=state` at end of line.
For example:
```
...
echo 'Loading Kernel: vmlinuz-5.14.11-2-default ...'
linux "/@/.snapshots/1/snapshot/boot/vmlinuz-5.14.11-2-default" root=UUID=1d9d72f6-8ef9-4440-a542-4ba1a279b8fb quiet mitigations=off rootflags=defaults,noatime,space_cache,autodefrag,compress=zstd,subvol="@/.snapshots/1/snapshot" systemd.volatile=state
...
```
The snapshot will boot in read-only mode, but `/var` will be writable.

If you have a good result with this method, I think I would include it by default.

**Comment by pandom79** [comment]
> @pandom79 , you are right. Another solution that might be considered is to use `systemd.volatile=state`. (Only if you're using `systemd`) See [#92 (comment)](https://github.com/Antynea/grub-btrfs/issues/92#issuecomment-966869223)
> 
> To do this: You must edit the kernel command line in the `Grub` menu and add `systemd.volatile=state` at end of line. For example:
> 
> ```
> ...
> echo 'Loading Kernel: vmlinuz-5.14.11-2-default ...'
> linux "/@/.snapshots/1/snapshot/boot/vmlinuz-5.14.11-2-default" root=UUID=1d9d72f6-8ef9-4440-a542-4ba1a279b8fb quiet mitigations=off rootflags=defaults,noatime,space_cache,autodefrag,compress=zstd,subvol="@/.snapshots/1/snapshot" systemd.volatile=state
> ...
> ```
> 
> The snapshot will boot in read-only mode, but `/var` will be writable.
> 
> If you have a good result with this method, I think I would include it by default.

Thanks for this method. 
I tried it, there are some services which fails yet but it can start sddm...even if it's more slow than before.
At the moment, it looks like not worth....at least for me.

**Comment by Antynea** [comment]
Thank you for your feedback

**Comment by geckolinux** [comment]
My Calamares installer configuration does put `/var/log` on a separate subvolume, and I could even change it to put all of `/var` in a subvolume. So not sure why my login manager (LightDM in my case) won't start. I also need to experiment more with `snapper rollback`, which doesn't seem to work correctly.

**Comment by Antynea** [comment]
@geckolinux 
I think, if you are using a login manager, `/var/log` in a different subvolume is not enough.
From what I have experienced in VM, `/var` should be writable when using a graphical environment.

`snapper rollback` on Arch Linux replaces the default btrfs subvolume `subvolid=5` with the snapshot you choose.
This is pointless, as `Grub` on Arch Linux is not patched to work like this.
`Grub `will use the current subvolume to create a valid entry and not `subvolid=5`.

In my opinion, the best way to rollback is to delete/move the `@` subvolume and create a copy of a read-only snapshot instead.
Don't forget to reinstall `Grub` in this new `@` subvolume.

For example:
**Please note that this is not a step-by-step guide, some steps may be missing.**
* Boot on the functional snapshot
* Mount btrfs tree in `/mnt`
(mount -o subvolid=5 /dev/sdxxx /mnt)
* delete/move `/mnt/@` subvolume
* Create a writable snapshot of the read-only source snapshot of your choice with the destination `/mnt/@`
(btrfs sub snap /mnt/snap-ro /mnt/@)
* Chroot into `/mnt/@`
  - Use `grub-install` to install `Grub` in `/mnt/@`
  - Use `grub-mkconfig` pour générer un nouveau fichier `grub.cfg`
* Exit chroot
* unmount `/mnt`
* On the next reboot, you should be in your new subvolume @ (perfect copy of the snapshot you chose earlier)

**Comment by Antynea** [comment]
Now that `grub-btrfs` supports the missing initrd,
this pr can be closed ?

**Comment by pandom79** [comment]
Yes ;)

**Comment by geckolinux** [comment]
Yep! Thanks!
