### ISSUE TITLE
Configuration issues on Fedora 35

### ISSUE THREAD

**Issue by RumenBlack84** [Antynea/grub-btrfs#191]
I am currently having an issue installing grub-btrfs on Fedora 35, more information provided below. Please let me know if there is any more information you require to help pin down the problem.

### Current config
-----------------------
OS: Fedora Linux 35 (Workstation Edition) [x86_64]
 Host: Alienware m15 R4 1.6.2
Kernel: 5.15.8-200.fc35.x86_64
Uptime: 56 mins
Packages: 1 (flatpak)
Shell: bash 5.1.8
Resolution: 1920x1080
DE: GNOME
WM: Mutter (X11)
Terminal: gnome-terminal-server
CPU: Intel Core i9-10980HK (16) @ 5.3GHz
Memory: 4282MiB / 31854MiB (13%)
Disk (/): 58GB / 952GB (6%)
Disk (/home): 58GB / 952GB (6%)
Battery: 100%
Locale: en_US.UTF-8

### Errors when attempting to run grub2-mkconfig -o /boot/grub2/grub.cfg

sudo grub2-mkconfig -o /boot/grub2/grub.cfg
Generating grub configuration file ...
Adding boot menu entry for UEFI Firmware Settings ...
Detecting snapshots ...
/etc/grub.d/41_snapshots-btrfs: line 545: /boot/grub/grub-btrfs.new: No such file or directory

###  correcting line 72 of /etc/grub.d/41_snapshots-btrfs to be /boot/grub2/ as its supposed to be in Fedora
Code changes to line 72

From;
grub_directory=${GRUB_BTRFS_GRUB_DIRNAME:-"/boot/grub"}

To;
grub_directory=${GRUB_BTRFS_GRUB_DIRNAME:-"/boot/grub2"}

### New Error Message
sudo grub2-mkconfig -o /boot/grub2/grub.cfg
Generating grub configuration file ...
Adding boot menu entry for UEFI Firmware Settings ...
Detecting snapshots ...
Found snapshot: 2021-12-19 16:08:17 | root/.snapshots/22/snapshot | single | writable copy of #14                                       |
Found snapshot: 2021-12-19 16:08:17 | root/.snapshots/21/snapshot | single | rollback backup of #20                                     |
Found snapshot: 2021-12-19 16:03:00 | root/.snapshots/20/snapshot | single | writable copy of #16                                       |
Found snapshot: 2021-12-19 16:03:00 | root/.snapshots/19/snapshot | single | rollback backup of #18                                     |
Found snapshot: 2021-12-19 16:02:40 | root/.snapshots/18/snapshot | single | writable copy of #14                                       |
Found snapshot: 2021-12-19 16:02:40 | root/.snapshots/17/snapshot | single | rollback backup of #16                                     |
Found snapshot: 2021-12-19 16:01:59 | root/.snapshots/16/snapshot | single | writable copy of #14                                       |
Found snapshot: 2021-12-19 16:01:59 | root/.snapshots/15/snapshot | single | rollback backup                                            |
Found snapshot: 2021-12-19 15:53:02 | root/.snapshots/14/snapshot | single | before grub-btrfs                                          |
Found snapshot: 2021-12-19 14:38:25 | root/.snapshots/13/snapshot | post   | /usr/bin/dnf install bottles                               |
Found snapshot: 2021-12-19 14:38:23 | root/.snapshots/12/snapshot | pre    | /usr/bin/dnf install bottles                               |
Found snapshot: 2021-12-19 14:38:12 | root/.snapshots/11/snapshot | post   | /usr/bin/dnf install lutris                                |
Found snapshot: 2021-12-19 14:38:09 | root/.snapshots/10/snapshot | pre    | /usr/bin/dnf install lutris                                |
Found snapshot: 2021-12-19 14:38:01 | root/.snapshots/9/snapshot  | post   | /usr/bin/dnf install winehq-staging                        |
Found snapshot: 2021-12-19 14:37:39 | root/.snapshots/8/snapshot  | pre    | /usr/bin/dnf install winehq-staging                        |
Found snapshot: 2021-12-19 14:35:48 | root/.snapshots/7/snapshot  | post   | /usr/bin/dnf install vulkan vulkan-tools                   |
Found snapshot: 2021-12-19 14:35:46 | root/.snapshots/6/snapshot  | pre    | /usr/bin/dnf install vulkan vulkan-tools                   |
Found snapshot: 2021-12-19 14:22:04 | root/.snapshots/5/snapshot  | post   | /usr/bin/dnf install thunderbird                           |
Found snapshot: 2021-12-19 14:22:00 | root/.snapshots/4/snapshot  | pre    | /usr/bin/dnf install thunderbird                           |
Found snapshot: 2021-12-19 14:20:48 | root/.snapshots/3/snapshot  | post   | /usr/bin/dnf install protonmail-bridge-1.8.12-1.x86_64.rpm |
Found snapshot: 2021-12-19 14:20:44 | root/.snapshots/2/snapshot  | pre    | /usr/bin/dnf install protonmail-bridge-1.8.12-1.x86_64.rpm |
Found snapshot: 2021-12-19 13:23:46 | root/.snapshots/1/snapshot  | single | Before AD                                                  |
Found 22 snapshot(s)
/etc/grub.d/41_snapshots-btrfs: line 568: /usr/bin/grub-script-check: No such file or directory
Syntax errors are detected in generated grub-btrfs.cfg file.
If you think an error has occurred , please file a bug report at " https://github.com/Antynea/grub-btrfs "
Unmount /tmp/grub-btrfs.FOofztZ9X6 .. Success
done

**Comment by Antynea** [comment]
hello,

> Install issues on Fedora 35 #191

Everything you provide is about setup errors, not about installation,  I would like to rename your request.

The solution is very simple.
You need to configure the config file that comes with the package.

If you need help with the configuration, do not hesitate.

**Comment by Schievel1** [comment]
I updated the instructions a little for Fedora users (https://github.com/Antynea/grub-btrfs/commit/57687ac0ab76d2ae710f04e7365381c7217d7b0c), otherwise there are  already plenty of instructions in the config file.
