### ISSUE TITLE
Syntax error when updating grub if a snapshot name contains one single quote

### ISSUE THREAD

**Issue by ajayyy** [Antynea/grub-btrfs#198]
```
Generating grub configuration file ...
Found theme: /usr/share/grub/themes/manjaro/theme.txt
Found linux image: /boot/vmlinuz-5.15-x86_64
Found initrd image: /boot/intel-ucode.img /boot/initramfs-5.15-x86_64.img
Found initrd fallback image: /boot/initramfs-5.15-x86_64-fallback.img
Found linux image: /boot/vmlinuz-5.4-x86_64
Found initrd image: /boot/intel-ucode.img /boot/initramfs-5.4-x86_64.img
Found initrd fallback image: /boot/initramfs-5.4-x86_64-fallback.img
Warning: os-prober will be executed to detect other bootable partitions.
Its output will be used to detect bootable binaries on them and create new boot entries.
Found Windows Boot Manager on /dev/nvme0n1p1@/efi/Microsoft/Boot/bootmgfw.efi
Found Debian GNU/Linux 11 (bullseye) on /dev/nvme0n1p9
Found Windows Boot Manager on /dev/sda4@/efi/Microsoft/Boot/bootmgfw.efi
Adding boot menu entry for UEFI Firmware Settings ...
Detecting snapshots ...
<REDACTED>
Found 20 snapshot(s)
error: syntax error.
error: Incorrect command.
error: syntax error.
Syntax error at line 452
Syntax errors are detected in generated grub-btrfs.cfg file.
If you think an error has occurred , please file a bug report at " https://github.com/Antynea/grub-btrfs "
Unmount /tmp/grub-btrfs.590QglV0nS .. Success
Found memtest86+ image: /boot/memtest86+/memtest.bin
/usr/bin/grub-probe: warning: unknown device type nvme0n1.
done
```

I found that removing the single quote fixes it, and it does not occur when there are two single quotes.

Version: 4.1.1
Distro: Manjaro

**Comment by Schievel1** [comment]
Hi, 

when you ran `grub-mkconf` with a snapshot with a quote in it and it failed, can you post `/boot/grub/grub-btrfs-new`? 

I probably just gonna add a function to sanitize the snapshot names and run every snapshot though it.

**Comment by blisshome** [comment]
I got the same syntax error messages when running grub-mkconfig, and the snapshot submenu of GRUB was empty. Both issues went away after removing the single quotation mark (possessive apostrophe, actually) in the description field of one of my Timeshift snapshots. I look forward to Schievel1's fix, but avoiding a single quotation mark/apostrophe in the description works for now. Thanks!
Running  5.19.17-1-MANJARO (64-bit) with grub-btrfs 4.11-2

**Comment by Schievel1** [comment]
I created a really small sanitize function. All it does is removing the ' from the menu and submenu titles. That seems to be enough already. 
However, I wonder if this function should remove more characters. But so far I tried `' !@#$%^&*()+={}[],<>.;:` and they all go well. It's only `'` that causes a problem.

**Comment by blisshome** [comment]
I only encountered problems with the apostrophe. I suspect it causes an imbalance in the single quotes which confuses the syntax checker. Thanks for dealing with this.

**Comment by Schievel1** [comment]
I am only sanitizing the menu titles, which seems to be enough for when there is a ' in the comment of a snapshot. 
I guess this also happens when there is a ' in the snapshot name. 

This is more or less a note to myself to try that out, but you can give that a try as well if you want to.

**Comment by Schievel1** [comment]
Turns out in Timeshift you can not alter the snapshot names, its always the date. So no way to get a `'` in there and no need to sanitize.

I will have to check how this is in snapper.
