### ISSUE TITLE
More snapper friendly

### ISSUE THREAD

**Issue by penetal** [Antynea/grub-btrfs#2]
Hey, love this script, but it would be even better if it was snapper friendly.
I am just going from using my own simple script to using snapper and would ask if you would add date and time to the menu entry.

Snapper only numbers them in the snapshot path, which will be pretty uninformative when looking at the menu.

My suggestion would just be to add something like the output of this `$bindir/btrfs subvolume list -s / --sort=-ogen | $bindir/cut -d" " -f11-12` to the end of the menu entry line which is just a date and time: `2015-05-11 10:09:23`

**Comment by Antynea** [comment]
hi,

Interesting idea, I'll see what I can do.
I do not use snapper, I create my snapshots with my own alias:

Ssnapshot () {local dest = "/ snapshots / system / @" $ (date + "% d% Y-% m-% H:% M"); if [$ 1]; Then local dest = $ dest "_ $ 1"; fi; while [-e $ dest $ as $ num]; as do local = "_"; Local num = `expr $ num + 1`; therefore; btrfs subvolume snapshot / $ dest $ as $ num;}

(e.g: @snapshots/@05-05-2015-10:11_pre-maj )

it already included the date.

**Comment by penetal** [comment]
I assumed you had a nice way to do it, I do too. However I want to use the
"most accepted" tool since I can't be bothered to keep replication
functionality (was about to start work on easy rollback).

Besides, this way you can include dating in the name of the snapshot, or
leave it out. Gives a tiny bit more flexibility, and won't mess up things
when the date is already included if it's the very last part of the menu
entry name.

In any case I will keep using your script because it is a great way to do
it. Thanks for the work you put into this.

**Comment by Antynea** [comment]
You're right, it is a more elegant way to do it.
I am currently busy, do not hesitate to pull request.

**Comment by Antynea** [comment]
Hi,
I finally found the time to test snapper.
once installed and configured, it automatically creates read-only snapshots.
What interest will start on such a snapshot?
I hope the 1.xx version of the script responds to your expectations?

**Comment by tristan-k** [comment]
There is a fork of `41_snapshots-btrfs`, which seems to do that: https://gist.github.com/wesbarnett/bcbd6217ee08c7d3581f68258a25413a
