### ISSUE TITLE
grub don't update after pacman

### ISSUE THREAD

**Issue by zarMarco** [Antynea/grub-btrfs#202]
Hi, I use arch with brtfs (subvol for @ @home and @snapshot), snapper, grub-btrfs and snap-pac. Grub see .shapshot's folder, pacman create snapshot before and after update but also I started grub-btrfs.service and grub-btrfs.path after pacman  finished, grub didn't upgrade. what's wrong?

**Comment by Arnie97** [comment]
Was your snapshot mount managed by systemd as `.snapshot.mount`, as described in `grub-btrfs.path`?

Apart from systemd mount units, there is also an alternative way provided by this little pacman hook snippet: [snap-pac-grub](https://github.com/maximbaz/snap-pac-grub), which is available from the AUR.

**Comment by Schievel1** [comment]
I updated the daemon in the last PR to watch the snapshots directory for new snapshots instead of watching mount points using a systemd daemon. You maybe want to give it a try.
