### ISSUE TITLE
Re-Opening - You might experience issues loading snapshots menu in GRUB

### ISSUE THREAD

**Issue by JaKooLit** [Antynea/grub-btrfs#212]
https://github.com/Antynea/grub-btrfs/issues/42

So since this issue was closed, anybody got a fix for it? 

grub-btrfs 4.11-2 is installed on my System (From Arch Repo) and I noticed today I have a message 
"Generated 400 total GRUB entries. You might experience issues loading snapshots menu in GRUB."

Which leds me to that closed issue

I have edited config located on /etc/default/grub-btrfs/ limiting to 50 

GRUB_BTRFS_LIMIT="50" - by default this commented

Any work around here? or fix. Thanks

**Comment by Schievel1** [comment]
The snapshots submenu in grub consists of submenues for every snapshots which in themselves consist of menuentries for the kernel. So when booting a snapshot you would first choose the snapshot and then the kernel you want to boot with that snapshot. 

The warning "Generated 400 total GRUB entries. You might experience issues loading snapshots menu in GRUB" in generated when there are too many menuentries. Menuentries are all the kernel entries in every snapshot. 
So for example you have 10 kernels in your /boot and you have 20 snapshots this would make (10*20=)200 menuentries. 

The variable GRUB_BTRFS_LIMIT on the other hand limits the amount of snapshots that are added to the menu. 

So, when you have 50 snapshots and 8 kernels in your `/boot` (both are not totally unrealistic numbers) you could easily generate 400 menuentries. 

Try setting GRUB_BTRFS_LIMIT to something lower.
