### ISSUE TITLE
(Guide for) Configuring systemd to update grub after modifying timeshift snapshots

### ISSUE THREAD

**Issue by danboid** [Antynea/grub-btrfs#213]
I am running grub-btrfs and timeshift under endeavouros. I want to configure grub-btrfs so that it will update the grub menu after creating a new BTRFS snapshot with timeshift but I was unable to successfully use the example `grub-btrfs.path` given in the current grub-btrfs README.

`grub-btrfs.path` depends upon `run-timeshift-backup.mount` but I have no such file or service installed or configured. How do I create or configure `run-timeshift-backup.mount`?

I also presume that the user has to configure the `PathModified=` statement in `grub-btrfs.path` by checking the path used by timeshift (`timeshift --list`) so this should be covered in the README too, if required.

**Comment by danboid** [comment]
I have got it working now - systemd now auto updates GRUB when I create or delete timeshift snapshots so I have created a guide to getting this configured correctly.

# Configuring systemd to update grub after modifying timeshift snapshots

Neither timeshift nor grub-btrfs will update your grub menu after you create or delete any snapshots so we have to manually configure systemd to do this for us, if we want the ability to boot directly into snapshots from GRUB.

First, we must check the base path used to store your timeshift snapshots. Create at least one snapshot with timeshift and then run timeshift --list 

```
# timeshift --list
Mounted '/dev/sda5' at '/run/timeshift/6724/backup'
Device : /dev/sda5
UUID   : fac5f415-21f5-44e9-93a8-c4b6b5687c72
Path   : /run/timeshift/6724/backup
Mode   : BTRFS
Status : OK
1 snapshots, 387.5 GB free

Num     Name                 Tags  Description  
------------------------------------------------------------------------------
0    >  2022-08-30_21-56-43  O
```

We can see here that the path of the snapshot is `/run/timeshift/6724/backup`. If you create more snapshots you will notice a similar path used but with a different 4 digit number so from this we can see it is actually `/run/timeshift` that we want to monitor for new directories / snapshots.

systemd has a function called PathModified that we'll use to monitor /run/timeshift for changes to update grub but we can only use it with dynamically created dirs such as this by creating a new mount point for it. Edit `/etc/fstab` and add a line like:  

```
UUID=<UUID> /run/timeshift/       btrfs   defaults,noatime  0 0
```

You must replace <UUID> with the UUID of your btrfs disk that you are snapshotting. After adding the new fstab entry, reboot and run

```
# systemctl list-units -t mount
  UNIT                                              LOAD   ACTIVE SUB     DESCRIPTION                              
  ...
  run-timeshift.mount                               loaded active mounted /run/timeshift
```

To check systemd has registered the new mount point.

Create `/etc/systemd/system/update-grub.service` with the following contents:

```
[Unit]
Description=Regenerate grub menu

[Service]
Type=oneshot
# Regenerate the grub menu
ExecStart=bash -c 'grub-mkconfig -o /boot/grub/grub.cfg' 
```

Create `/etc/systemd/system/grub-btrfs.path` with the following contents:

```
[Unit]
Description="Monitor /run/timeshift for new snapshots"
DefaultDependencies=no
Requires=run-timeshift.mount
After=run-timeshift.mount
BindsTo=run-timeshift.mount

[Path]
PathModified=/run/timeshift
Unit=update-grub.service

[Install]
WantedBy=run-timeshift.mount
```

Now by enabling / starting `grub-btrfs.path`, systemd will update GRUB when snapshots are created or deleted.

```
systemctl enable grub-btrfs.path
systemctl start grub-btrfs.path
```

**Comment by danboid** [comment]
I'll create a PR to add these instructins to the README if @Antynea proves he's still with us and he deals with the existing PRs.

**Comment by Schievel1** [comment]
I am working on a daemon right now to watch for snapshots and triggering grub-btrsd instead of relying on systemd mounts and its almost finished. Maybe you want to give it a try. I put instructions into the PR, #218, for more instructions visit https://github.com/Schievel1/grub-btrfs/tree/update-daemon.

**Comment by danboid** [comment]
Yes I will. I'm not happy with my current systemd solution because you have to add an extra mount point which seems messy to me. Its one of the reasons I don't like snap packages - extra mounts.
