### ISSUE TITLE
Possible solution for dracut-based distros?

### ISSUE THREAD

**Issue by Le0xFF** [Antynea/grub-btrfs#214]
Hello and thank you for this massive work!

I'm using Void Linux, today I tried to boot a snapshot from grub to check if this works but I ended up with a black screen, with some `/var/log` error, even if I have some subvolumes of `/var` as you can see from my layout:

``` bash
$ sudo btrfs subvolume list /
ID 256 gen 1055 top level 5 path @
ID 276 gen 1067 top level 5 path @home
ID 257 gen 1055 top level 5 path @snapshots
ID 258 gen 849 top level 256 path var/cache/xbps
ID 259 gen 538 top level 256 path var/tmp
ID 260 gen 1065 top level 256 path var/log
```

I saw that this could be related to issue #92, so looking better at this [README](https://github.com/Antynea/grub-btrfs/tree/master/initramfs/readme.md), there are specific instructions for `mkinitcpio`-based distros, but not for `dracut` ones, as also I read from issue #160.

Looking at [`dracut` documentation](https://www.man7.org/linux/man-pages/man7/dracut.cmdline.7.html) I saw two options that made my snapshots bootable:
* `rd.live.overlay.readonly=1`
* `rd.live.overlay.overlayfs=1`

Adding one of these two options to the `linux` grub line, my snapshot booted without any issue.

The problem is that I don't know if this is the proper way to boot a snapshot the way it should be as I'm not really a Linux savvy. May I ask you if you could take a look at that?

**Comment by mbana** [comment]
I have this working in Fedora 36.

I'd watch this space: <https://github.com/banaio/grub-btrfs>. When I find time, I'll detail the steps and configuration required for Fedora on BTRFS.

The annoying thing is that you need to set the default volume back after doing a snapshot. Other than that, it works fine.

**Comment by daiaji** [comment]
@Antynea Looks like the work has been made simpler, providing an option to add rd.live.overlay.readonly=1 with rd.live.overlay.overlayfs=1 to the kernel command line by the way when generating the grub menu?

**Comment by slashmach1** [comment]
fedora also may need to install the inotify-tools package.  testing on latest nobara

**Comment by Schievel1** [comment]
> fedora also may need to install the inotify-tools package. testing on latest nobara

It certainly does for the daemon.



> adding either option @daiaji mentioned to this line in 41_snapshots-btrfs: kernel_parameters="$GRUB_CMDLINE_LINUX $GRUB_CMDLINE_LINUX_DEFAULT
> 
> before installing grub-btrfs will allow this to work with dracut distros. rd.live.overlay.readonly=1 will make readonly while rd.live.overlay.overlayfs=1 allows read/write but changes are lost on reboot unless comitted to a new snapshot: example: kernel_parameters="$GRUB_CMDLINE_LINUX $GRUB_CMDLINE_LINUX_DEFAULT rd.live.overlay.overlayfs=1"
> 
> NOTE: certain var directories need to be separate subvolumes depending on your window manager or desktop environment; otherwise systemd wont load to GUI. gnome is /var/lib/gdm and /var/lib/AccountsService

If I add a config parameter like 
kernel_parameters="$GRUB_CMDLINE_LINUX $GRUB_CMDLINE_LINUX_DEFAULT $GRUB_BTRFS_SNAPSHOT_KERNEL_PARAMETERS

and you can set that in /etc/default/grub-btrfs/config to whatever you like, would this be enough?

> fedora also may need to install the inotify-tools package. testing on latest nobara

It certainly does for the daemon.

**Comment by slashmach1** [comment]
Have not tested the  modification using that file.  The file I'm referring to in my previous comment is /etc/grub.d/41_snapshots-btrfs after grub-btrfs is install.  And either rd.live.overlay.overlayfs=1 or rd.live.overlay.readonly=1 needs to be added to the snapshot boot commandline

**Comment by Schievel1** [comment]
I see, but basically all you need is the ability to add this to the snapshots kernel command line?

**Comment by slashmach1** [comment]
This line is incorrect: 
"After changing this run sudo /etc/grub.d/41_snapshots-btrfs to generate a new snapshot-submenu with the parameter added."
That script is executed when grub is regenerating grub.cfg so simply updating grub after installation or changing that parameter should be enough for implementation.  

The only thing other than that is to make note of is the /var partition layout.  the desktop dnvironment or display manager directories (/var/lib/{display manager or desktop environment application folder}) at least need to be on separate partitions.  Otherwise even with these changes the system will boot but wont load to GUI from what I have tried.  

EXAMPLE:
/var/lib/AccountsService and /var/lib/gdm on a separate partition for gnome users and 
/var/lib/AccountsService and /var/lib/sddm on a separate partition for KDE users

**Comment by slashmach1** [comment]
That im not 100% sure.  I did get grub-btrfs working on Nobara, just sharing my steps to replicate the full picture.

**Comment by slashmach1** [comment]
I believe the documentation calls for var being on a separate partition anyways in setup which would cover the directories I reference

**Comment by Schievel1** [comment]
Yes when I find the time I will rework what is written in which place and so on to make this a bit less scattered

**Comment by Schievel1** [comment]
> > Gentoo, where Dracut is a niche thing. 
> To be honest, dracut is not particularly niche, at least opensuse uses dracut to generate initramfs by default. And this post seems to show some native functions used by dracut, such as overlay without hook script, which is more convenient than mkinitcpio.

Nah, I meant on Gentoo it is kinda niche.  Gentoo has [genkernel](https://wiki.gentoo.org/wiki/Genkernel) which can build you the initrd. 
But I gotta say, Dracut does it's job, all I did was deleting my initrds and runnig `drauct --regerate-all`. Problem is rather, that I can not reproduce your problem. I can boot the snapshots all fine, regardless of what I give as kernel command line.  That I a bit of a bummer, because I was hoping I could write some proper documentation with this.

**Comment by daiaji** [comment]
What I know about Gentoo is limited to his support for x32 ABI, but x32 ABI is too niche, and using him seems to mean that you need to recompile all packages for x32 ABI, which seems to mean that I have almost no container images available.

**Comment by daiaji** [comment]
https://github.com/dracutdevs/dracut/issues?q=rd.live.overlay.overlayfs
Actually rd.live.overlay.overlayfs=1 is faulty, since I created a separate subvolume for the /var folder, it seems that the OS is bootable, but the root directory is still not writable.
At least I didn't find the overlayfs was mounted.
A quirky mistake.
`dracut-pre-udev : sh: /usr/bin/sysctl: No such file or directory`
I guess I should add /usr/bin/sysctl for initramfs, but I don't know how.

**Comment by daiaji** [comment]
> @daiaji which dracut version are you on ?
> 
> [dracutdevs/dracut#1934](https://github.com/dracutdevs/dracut/pull/1934) is not yet released, hope to get it released with dracut v58.

archlinux has an AUR package called dracut-git, which I built and installed.


> dracut -I sysctl
> 
> If you want to see how rd.live.overlay.overlayfs is tested upstream (some example command line options) - https://github.com/dracutdevs/dracut/blob/master/test/TEST-16-DMSQUASH/test.sh#L21

I did a more detailed test and the glitch seems to go away after adding the dmsquash-live module. And after checking the directory mounting status, I found that rootfs mounted the overlay, but there is a problem that when I add the dmsquash-live module, the --hostonly parameter seems to be unavailable, which means that after adding the dmsquash-live module I can't use [dracut-hook](https://aur.archlinux.org/cgit/aur.git/tree/dracut-install?h=dracut-hook).

```
mount | grep -E "overlay"
rootfs on / type overlay (rw,relatime,lowerdir=/tmp.ICyUf1,upperdir=/tmp.2YEua1/upper,workdir=/tmp.2YEua1/work)
rootfs on /var/lib type overlay (rw,relatime,lowerdir=/tmp.ICyUf1,upperdir=/tmp.2YEua1/upper,workdir=/tmp.2YEua1/work)
```
```
sudo dracut --hostonly --force /boot/initramfs-6.0-x86_64.img
/etc/dracut.conf.d/myflags.conf:add_dracutmodules+="dmsquash-live"

dracut: WARNING: <key>+=" <values> ": <values> should have surrounding white spaces!
dracut: WARNING: This will lead to unwanted side effects! Please fix the configuration file.

dracut: Executing: /usr/bin/dracut --hostonly --force /boot/initramfs-6.0-x86_64.img
dracut: dracut module 'dash' will not be installed, because command 'dash' could not be found!
dracut: dracut module 'mksh' will not be installed, because command 'mksh' could not be found!
dracut: dracut module 'busybox' will not be installed, because command 'busybox' could not be found!
dracut: dracut module 'dbus-broker' will not be installed, because command 'dbus-broker' could not be found!
dracut: dracut module 'rngd' will not be installed, because command 'rngd' could not be found!
dracut: dracut module 'connman' will not be installed, because command 'connmand' could not be found!
dracut: dracut module 'connman' will not be installed, because command 'connmanctl' could not be found!
dracut: dracut module 'connman' will not be installed, because command 'connmand-wait-online' could not be found!
dracut: dracut module 'network-wicked' will not be installed, because command 'wicked' could not be found!
dracut: dracut module 'tpm2-tss' will not be installed, because command 'tpm2' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsi-iname' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsiadm' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsid' could not be found!
dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
dracut: dracut module 'memstrack' will not be installed, because command 'memstrack' could not be found!
dracut: memstrack is not available
dracut: If you need to use rd.memdebug>=4, please install memstrack and procps-ng
dracut: dracut module 'dmsquash-live' cannot be found or installed.
```

**Comment by daiaji** [comment]
```
sudo dracut --hostonly --force /boot/initramfs-6.0-x86_64.img -a "debug dmsquash-live"
dracut: Executing: /usr/bin/dracut --hostonly --force /boot/initramfs-6.0-x86_64.img -a "debug dmsquash-live"
dracut: dracut module 'dash' will not be installed, because command 'dash' could not be found!
dracut: dracut module 'mksh' will not be installed, because command 'mksh' could not be found!
dracut: dracut module 'busybox' will not be installed, because command 'busybox' could not be found!
dracut: dracut module 'dbus-broker' will not be installed, because command 'dbus-broker' could not be found!
dracut: dracut module 'rngd' will not be installed, because command 'rngd' could not be found!
dracut: dracut module 'connman' will not be installed, because command 'connmand' could not be found!
dracut: dracut module 'connman' will not be installed, because command 'connmanctl' could not be found!
dracut: dracut module 'connman' will not be installed, because command 'connmand-wait-online' could not be found!
dracut: dracut module 'network-wicked' will not be installed, because command 'wicked' could not be found!
dracut: dracut module 'tpm2-tss' will not be installed, because command 'tpm2' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsi-iname' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsiadm' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsid' could not be found!
dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
dracut: dracut module 'memstrack' will not be installed, because command 'memstrack' could not be found!
dracut: memstrack is not available
dracut: If you need to use rd.memdebug>=4, please install memstrack and procps-ng
dracut: dracut module 'dmsquash-live' cannot be found or installed.

```
It seems that now that the overlayfs is no longer mounted, things get weird.
