### ISSUE TITLE
Unit file grub-btrfsd.service does not exist.

### ISSUE THREAD

**Issue by Mossy93** [Antynea/grub-btrfs#225]
When I try to enable the `grub-btrfsd` service on a fresh install on Arch Linux, I get the error message: `Unit file grub-btrfsd.service does not exist.`

**Comment by Schievel1** [comment]
What version did you install? Git version or 4.11?

**Comment by Schievel1** [comment]
Well I am not quite sure which version Arch installs. The Readme should come with the package I guess. But have you tried with the old instructions from the 4.11? https://github.com/Antynea/grub-btrfs/tree/v4.11

**Comment by Mossy93** [comment]
Yes, the Arch version should be 4.11 according to the [Arch package database](https://archlinux.org/packages/community/any/grub-btrfs/)

I will try that and let you know

**Comment by Schievel1** [comment]
I am not very familiar with Arch's pkgbuild format. 
So the -git version from the AUR is fetching HEAD of master branch isn't it?
This one https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=grub-btrfs-git

It just wonder because the version says 4.11.r4.g3dc1d89, and this is not the commit SHA of the last commit on master.

**Comment by Mossy93** [comment]
`pacman -Q` confirms that I have grub-btrfs 4.11-2. 

I ran `sudo systemctl enable grub-btrfs.path` and I got:
`Created symlink /etc/systemd/system/\x2esnapshots.mount.wants/grub-btrfs.path → /usr/lib/systemd/system/grub-btrfs.path.
Unit /usr/lib/systemd/system/grub-btrfs.path is added as a dependency to a non-existent unit \x2esnapshots.mount.`

**Comment by Schievel1** [comment]
Right, place follow the readme from 4.11. originally this is set up for snapshots to be mounted on /.snapshots like snapper does it. If you don't have snapshots there yet or you don't use snapper you will have to edit the service file accordingly

**Comment by Mossy93** [comment]
Okay. I'll have to take a look later on, but I'm using Snapper and my snapshots are saved to /.snapshots

**Comment by Mossy93** [comment]
> It just wonder because the version says 4.11.r4.g3dc1d89, and this is not the commit SHA of the last commit on master.

It appears to be flagged out of date, and has no maintainer listed
https://aur.archlinux.org/packages/grub-btrfs-git

**Comment by maetthew** [comment]
Experiencing the same issue here.

**Comment by Mossy93** [comment]
I installed the `-git` version from the AUR, and was able to follow the instructions on the main GitHub page

**Comment by Schievel1** [comment]
Hey, thanks for trying that out.

Does it work well?

**Comment by Mossy93** [comment]
> Hey, thanks for trying that out.
> 
> Does it work well? 

Once I updated it worked right out of the box

**Comment by LorenzoBettini** [comment]
I don't think the AUR package will be updated until there's a new release of grub-btrfs (the latest one is 4.11, dated Nov 29, 2021).

In any case, do you suggest we simply install it from the master branch of grub-btrfs? I mean, is the master branch to be considered stable to install it from there?

**Comment by Schievel1** [comment]
Well judging from your other issue it isn’t, but then again, I was waiting for some people to install the git package or manually “from source” so to speak and the issue to come up before I make a release. So please, install the git package or the master branch :)

**Comment by Schievel1** [comment]
I think it is save to assume this is a version mismatch and no issue of grub-btfs

**Comment by Schievel1** [comment]
Speaking of versions, let’s have a new feature to print the version when the script is called with —version. 
I reopen so I can remember it.
