### ISSUE TITLE
Timeshift snapshots not detected (and journalctl flooded with messages)

### ISSUE THREAD

**Issue by LorenzoBettini** [Antynea/grub-btrfs#227]
Hi

I've just installed grub-btrfs on a new computer, running Ubuntu, so I had to install it from sources (I had done this two months ago on a previous Ubuntu version, and I'm using grub-btrfs from AUR, version 4.11, on several Arch installations).

In Ubuntu 22.10, Timeshift has been updated to version 22.06.5, so by following the README section https://github.com/Antynea/grub-btrfs#-timeshift--version-2206 I changed the line of the service configuration as follows:

```
ExecStart=/usr/bin/grub-btrfsd --syslog --timeshift-auto
```

I restarted the grub-btrfsd service and the journal log is flooded with these message (1 every second):

```
grub-btrfsd[5236]: Watching /run/timeshift for timeshift to start
```

As soon as I start Timeshift, it is detected:

```
grub-btrfsd[5529]: detected running Timeshift at daemon startup, PID is: 5477
grub-btrfsd[5530]: Watching /run/timeshift/5477/backup/timeshift-btrfs/snapshots for new snapshots...
```

I try to create a new snapshot (or delete an existing one), but the log does not show grub-btrfsd detected the snapshot (in fact, the grub menu is not updated).

I close Timeshift, and grub-btrfsd starts to flood the log again, as above.

It's the first time I'm trying this new grub-btrfsd service (In Arch, with still version 4.11, there was not this service, but by editing /etc/fstab I could correctly make grub-btrfs detect snapshots, now I can't anymore). Am I missing something?

Thanks in advance

**Comment by Schievel1** [comment]
Hi and thanks for this very good issue report. 
You can switch in verbose logging by also passing —verbose to the daemon. 
but a shot in the blue, have you installed https://archlinux.org/packages/community/x86_64/inotify-tools/ ? Because that is needed by the daemon

**Comment by LorenzoBettini** [comment]
@Schievel1 Thank you for the quick answer!
My bad! I hadn't seen that new requirement.
Once installed, everything works like a charm (and no more flooding in the log).

I updated my blog article for Ubuntu accordingly: https://www.lorenzobettini.it/2022/10/timeshift-and-grub-btrfs-in-ubuntu/

Thanks a lot for this new systemd service, making everything much easier in the presence of Timeshift. :)

**Comment by Schievel1** [comment]
Thanks for checking that out, and finding those things. Please report back if you find any more issues. 
I will put a check for inotify in soon.
