### ISSUE TITLE
grub-btrfs should not parse pre-post snapshots

### ISSUE THREAD

**Issue by darkbasic** [Antynea/grub-btrfs#23]
I use snap-pac which hooks into pacman to add transactions support: it creates a pre snapshot before running pacman and a post snapshot afterward. This makes possible to revert it or to diff the changes: https://wiki.archlinux.org/index.php/Snapper#Wrapping_pacman_transactions_in_snapshots

Unfortunately pre-post snapshots are not normal snapshots and should not be listed by brub-btrfs. You can show them with:
`snapper -c @ list -t pre-post`
or looking at the first column of
`snapper -c @ list`

**Comment by Antynea** [comment]
Support for snapper has not yet started in this project.
I have not found the time to do so.

If a charitable soul goes through here, I invite her to contribute :)

**Comment by vince2678** [comment]
I'll be playing around with snapper and grub-btrfs and see if i can resolve this.

**Comment by Antynea** [comment]
#2 As tristan-k said :
> There is a fork of 41_snapshots-btrfs, which seems to do that: https://gist.github.com/wesbarnett/bcbd6217ee08c7d3581f68258a25413a

**Comment by darkbasic** [comment]
Any chance to merge snapper support?

**Comment by daftaupe** [comment]
Yes, that would be a good added feature.

**Comment by NicoHood** [comment]
> Unfortunately pre-post snapshots are not normal snapshots

Could you please explain this more detailed?

**Comment by darkbasic** [comment]
I simply meant that they pollute the grub list because they are created every time pacman installs a package and they are of no interest.

Also btrfs-grub should update the grub config every time that snapper creates a new snapshot or deletes an old one. It probably could be easily achieved with a /etc/systemd/system/snapper-timeline.timer.d/override.conf / /etc/systemd/system/snapper-cleanup.timer.d/override.conf

**Comment by NicoHood** [comment]
They do not pollute the list, as they are created for every update that you do. When does the system likely break? If you update/install something with pacman. If it was not meant for this, for what else would you want to use snapshots?

For normal file recovery you can use the file explorer. I did that a lot of times, so I see no reason why to hide pre/post snapshots. We should rather hide timeline snapshots with this argumentation, but I still think that'd be a bad idea.

**Comment by darkbasic** [comment]
Ok, let's say there is no way to understand which snapshot is what if you have so many of them.
Instead of removing them grub-btrfs should probably simply add some kind of hints in the entry description about being a pre or post snapshot (and which package was installed before/after that snapshot), if it was an hourly snapshot or a manual one, etc.. Such informations can be easily found using snapper.

**Comment by daftaupe** [comment]
Yes I agree, grub-btrfs should probably give more details from snapper snapshots if available, though they're either sorted historically or in the reverse order, and it makes no sense that you would have a lot of snapshots after you encounter an issue.
@NicoHood is right, at first I thought they were of a special type, but it sounds like they are regular ro snapshots. So it's alright to have all the snapshots in the grub menu.

**Comment by darkbasic** [comment]
> @NicoHood is right, at first I thought they were of a special type, but it sounds like they are regular ro
> snapshots. So it's alright to have all the snapshots in the grub menu.

My fault, sorry for the confusion. Initially when I filed the bug I thought they were of some special type, but then I noticed the difference was at the snapper level and they were like normal snapshots for btrfs. Somehow I didn't want them because having too many snapshots without description in grub-btrfs can be actually worse, but we should really add some kind of description instead.

Summarizing, to properly support snapper we need:
1) To hook into snapper-timeline.service and snapper-cleanup.service by creating /etc/systemd/system/snapper-timeline.service.d/override.conf and /etc/systemd/system/snapper-cleanup.service.d/override.conf to allow grub-btrfs to know when snapshots are created/delete and thus updating the grub config.
2) To fix the grub configuration file update logic to grab snapshot informations from snapper (like being a pre/post/hourly/manual snapshots and which packages have been updated if pre or post) and put that informations in the boot entry description. Such informations can be easily found with a simple "sudo snapper -c @subvolume list".

**Comment by maximbaz** [comment]
If anyone is still around, I've submitted PR #35 that implements the second point (to show snapper's snapshot description in GRUB entries). 

It works nicely on my own system (Arch Linux, snapshots being made by [snap-pac-grub](https://aur.archlinux.org/packages/snap-pac-grub)), I posted an example in the PR description, but feel free to test and give additional feedback if you are interested.
