### ISSUE TITLE
Fedora 37 version 4.12 does not work correct

### ISSUE THREAD

**Issue by McGrey86** [Antynea/grub-btrfs#234]
I'm not a Linux expert, I'm just going to switch to it and I want to set everything up right away. But I've run into a problem that I can't seem to solve. As I see it, the problem is that "grub-btrfsd.service" does not start automatically even after installation. After reboot too. Entering the command "sudo systemctl start grub-btrfsd" only affects it when the "Timeshift" application is open. When only by activating it in this way it works correctly and in the GRUB menu it records everything normally.

The only thing is that if you delete all the snapshots from Timeshift, then one snapshot remains there anyway in GRUB menu. But it was the same on 4.11. Otherwise, version 4.11 works great.

Fedora 37 full default. Below I will add something like a log, I hope it helps.

[grub btrfsd service Regenerate.txt](https://github.com/Antynea/grub-btrfs/files/10087556/grub.btrfsd.service.Regenerate.txt)

**Comment by Schievel1** [comment]
Could you post what you have in ‘sudo systemctl edit --full grub-btrfsd’

**Comment by McGrey86** [comment]
[Unit]
Description=Regenerate grub-btrfs.cfg

[Service]
Type=simple
LogLevelMax=notice
# Set the possible paths for `grub-mkconfig`
Environment="PATH=/sbin:/bin:/usr/sbin:/usr/bin"
# Load environment variables from the configuration
EnvironmentFile=/etc/default/grub-btrfs/config
# Start the daemon, usage of it is:
# grub-btrfsd [-h, --help] [-t, --timeshift-auto] [-l, --log-file LOG_FILE] SNAPSHOTS_DIR
# SNAPSHOTS_DIR         Snapshot directory to watch, without effect when --timeshift-auto
# Optional arguments:
# -t, --timeshift-auto  Automatically detect Timeshifts snapshot directory
# -l, --log-file        Specify a logfile to write to
# -v, --verbose         Let the log of the daemon be more verbose
# -s, --syslog          Write to syslog
ExecStart=/usr/bin/grub-btrfsd --syslog /run/timeshift/backup/timeshift-btrfs/snapshots

[Install]
WantedBy=multi-user.target


Timeshift v21.09.1

**Comment by McGrey86** [comment]
Timeshift v21.09.1
[Unit Description Regenerate.txt](https://github.com/Antynea/grub-btrfs/files/10089484/Unit.Description.Regenerate.txt)

**Comment by McGrey86** [comment]
```
[Unit]
Description=Regenerate grub-btrfs.cfg

[Service]
Type=simple
LogLevelMax=notice
# Set the possible paths for `grub-mkconfig`
Environment="PATH=/sbin:/bin:/usr/sbin:/usr/bin"
# Load environment variables from the configuration
EnvironmentFile=/etc/default/grub-btrfs/config
# Start the daemon, usage of it is:
# grub-btrfsd [-h, --help] [-t, --timeshift-auto] [-l, --log-file LOG_FILE] SNAPSHOTS_DIR
# SNAPSHOTS_DIR         Snapshot directory to watch, without effect when --timeshift-auto
# Optional arguments:
# -t, --timeshift-auto  Automatically detect Timeshifts snapshot directory
# -l, --log-file        Specify a logfile to write to
# -v, --verbose         Let the log of the daemon be more verbose
# -s, --syslog          Write to syslog
ExecStart=/usr/bin/grub-btrfsd --syslog /run/timeshift/backup/timeshift-btrfs/snapshots

[Install]
WantedBy=multi-user.target
```

Timeshift v21.09.1

**Comment by Schievel1** [comment]
Looks like you did everything correctly, problem is that this use case of old timeshift with new daemon from 4.12 is not tested properly. So I think you found a bug there. 
I will release a fix soon, in the meantime you can still use the .service-files from 4.11 with 4.12.

**Comment by Schievel1** [comment]
Notes for me: Problem here is that old timeshift  has it's snapshots under `/run/timeshift/backup/timeshift-btrfs/snapshots`, but that snapshot directory is only there, when timeshift is started. But when grub-btrfsd is starting up, it checks if the snapshot directory exists. Which it does not, when timeshift is not started, so the daemon exits with an error. 
https://github.com/Antynea/grub-btrfs/blob/1d760ad73011e5610610b41955dc6948ceb64249/grub-btrfsd#L176

What we could do: 
- remove the check for the directory
- OR make it a warning?
- OR add a new flag for timeshift-old that removes the check only when the flag is set (overcomplicates things)

**Comment by McGrey86** [comment]
Ok thanks for the quick response, I'll try experimenting with that a bit later

**Comment by Schievel1** [comment]
I made an ad hoc version with the warning solution real quick, you maybe want to try it out. 
I can't test it right now though.
https://github.com/Antynea/grub-btrfs/tree/fix-snap-dir-check

**Comment by McGrey86** [comment]
> I made an ad hoc version with the warning solution real quick, you maybe want to try it out. I can't test it right now though. https://github.com/Antynea/grub-btrfs/tree/fix-snap-dir-check

I tested this version and already a different result. But still this process does not automatically start. I am attaching the test results below.

[grub-btrfs-fix-snap-dir-check.txt](https://github.com/Antynea/grub-btrfs/files/10093723/grub-btrfs-fix-snap-dir-check.txt)

**Comment by Schievel1** [comment]
Yes, now we run into this:
https://github.com/Antynea/grub-btrfs/blob/91c4aac82cffbfefe9cb1cd1b81788c98b1f1f1e/grub-btrfsd#L251

*sigh* I will install old timeshift and try to find a solution. I updated the branch already. If you want you can keep testing this stuff when I push new commit to this branch, but I will tell you when I think that it's finished.

**Comment by McGrey86** [comment]
> / If you are on a production system and want this to just work, use the .service-file from 4.11 or install timeshift >=v22.06

No no, i am home user )
Installing a new version of the timeshift >=v22.06 via "sudo make install" fails on Fedora 37.

I tried to use the service file from 4.11 and it does not work correctly either, you also need to start manually. And in the GRUB menu it’s somehow incomprehensible, like snapshots are added, but not everything that was in Timeshift. I also hope  understand correctly that this means simple replacing the "grub-btrfsd.service" file with the "grub-btrfs.service" file in the "/etc/systemd/system" folder. 

It's easier then to just use the full 4.11 in it, everything works automatically. Well, below, if interesting, I'll attach what happened from such a combination. True, it was not installed on a clean 4.12, but on this one with the fix "grub-btrfs-fix-snap-dir-check"

[pipi g14 sudo systemctl.txt](https://github.com/Antynea/grub-btrfs/files/10094228/pipi.g14.sudo.systemctl.txt)

**Comment by McGrey86** [comment]
> If you want to test this now, please set `--timeshift-auto` and `--timeshift-old` as flags when you edit `sudo systemctl edit --full grub-btrfsd`. The snapshot directory in that line is ignored then and can be removed.
> Also setting the `--verbose` flag will generate some more output to investigate.

`--timeshift-old` with flag was error
[timeshift-old.txt](https://github.com/Antynea/grub-btrfs/files/10095131/timeshift-old.txt)

`--timeshift-auto` with path `/run/timeshift/backup/timeshift-btrfs/snapshots` works, BUT (write describe below)
[timeshift-auto +path.txt](https://github.com/Antynea/grub-btrfs/files/10095135/timeshift-auto.%2Bpath.txt)

`--timeshift-auto` without path works, BUT
[timeshift-auto.txt](https://github.com/Antynea/grub-btrfs/files/10095139/timeshift-auto.txt)

version 4.12 + auto (without "grub-btrfs-fix-snap-dir-check") and without path too works, BUT 
[4.12 + auto.txt](https://github.com/Antynea/grub-btrfs/files/10095145/4.12.%2B.auto.txt)

BUT now in GRUB menu snapshots are added with a delay of one iteration. That is, I make changes in Timeshift, restart the computer and see the snapshots before these changes in the GRUB menu. And so it repeats.

**Comment by McGrey86** [comment]
And I want to add that this utility "inotify-tools" is now required to be installed. Doesn't work without it.

**Comment by Schievel1** [comment]
The pure script in /etc/grub.d does work without inotify and this is what grub-btrfs is mostly about. 
The daemon does not work without inotify, but the daemon is just a nice gimmick and not the main thing here. That's why I added it as optional dependency in the readme.

**Comment by Schievel1** [comment]
Just pushed a new commit. I can't get timeshift 22.06 to compile on my system. So I have to figure this out first to test it.

**Comment by Schievel1** [comment]
Got timeshift 21.09 working and works fine for me now, please test.

You have to checkout the branch and pull it again with git pull. Let me know if you have trouble with that and I will give you some more help.

**Comment by McGrey86** [comment]
The same thing happens. Snapshots in GRUB menu lag behind those who are actually in Timeshift.
Initially, if you do snapshots in GRUB menu correctly displayed. But if you remove/add again you can see this lag.

And yes I use with flag `--timeshift-auto` because without him, she also didn’t work at all like before.
[pipi g14 sudo systemctl.txt](https://github.com/Antynea/grub-btrfs/files/10096447/pipi.g14.sudo.systemctl.txt)

I can also assume here what a magical feature of my computer and work with him Fedora. Because there are contenders. At first, when installing, kernel errors immediately appeared. Cured by writing a flash drive through Ventoy and launching only through Normal mode. Then it rebooted and did not turn off, it was cured by installing Nvidia drivers. Then there was a problem with the timeshift, since the manuals are old on the network, but on command `git clone https://github.com/Antynea/grub-btrfs.git` already downloaded a new one, ok that's clear. Now, for some reason, my programs do not see the Nvidia card, although they saw it before. 
Tell me why are you doing this. Install another system. But I want something clean, beautiful and modern. Ubunta, Mahjaro don't quite suit me. I tried to install Arch Linux, but at the stage when infa is read from the flash drive and the command line should appear, it appears, but along with it an endless stream of repeating information flows. Tried googling and didn't come across anything like that. Apparently I'm just so lucky. Therefore, only one Fedor remains.

Linux is, of course, a beautiful and fast system, as I noticed, but how difficult it is to work with it. Therefore, you will excuse me for such an offtopic, it's just that for almost a week I've been wanting to perfectly configure everything, and for now I'll probably just use version 4.11.

**Comment by Schievel1** [comment]
Sad to hear that you are having trouble. It is a great benefit but also a curse of the Linux world that there is that much diversion.  But Fedora is a great system from what I hear. Your problem here is not because you are using Fedora, it is because of a bug in our `grub-btrfs` when using Timeshift with version <22.06.
Again, this is because of the diversity of the Linux world. Grub-btrfs is already supporting different boot systems (legacy boot, efi in different locations), different initramfs systems (mkinitcpio from arch), different init-systems (openrc and systemd), different snapshot programs (Snapper, Timeshift) and different versions of them (Timeshift >=22.06 vs Timeshift <22.06). It's no wonder some thing slip though. :-(
I also wonder why the newest Fedora does use such an old version of Timeshift. Makes me wonder if they are also having trouble with the newer versions.

If version 4.11 works for you, just stick with it. That's fine. It's not like we make a lot different here. Especially for you use case, because the main difference of 4.12 is the new daemon, because the old way of doing this was not working with Timeshift v22.06 anymore. So since you are not using it, it is fine. 

If you still want to test things out, I noticed two things: 
> but on command git clone https://github.com/Antynea/grub-btrfs.git already downloaded a new one, ok that's clear
but the version I made to fix your problem is on a different branch. So what you actually should to to get that is:
```
git clone https://github.com/Antynea/grub-btrfs.git
cd grub-btrfs
git checkout fix-snap-dir-check
sudo make install
```
Secondly I noticed that you do not pass `--timeshift-old` to the daemon: 
```
     CGroup: /system.slice/grub-btrfsd.service
             ├─ 986 /bin/sh /usr/bin/grub-btrfsd --syslog --timeshift-auto --verbose /run/timeshift/backup/timeshift-btrfs/snapshots
             └─1203 inotifywait -e create -e delete /run/timeshift
```

So after you installed the version from branch `fix-snap-dir-check`, run `sudo systemctl edit --full grub-btrfsd`, edit the flags and add `--timeshift-old` and `--timeshift-auto` and after that run `sudo systemctl stop grub-btrfsd` and `sudo systemctl start grub-btrfsd`

**Comment by McGrey86** [comment]
Yes, everything works now.
[pipi g14 btrfs.txt](https://github.com/Antynea/grub-btrfs/files/10096956/pipi.g14.btrfs.txt)

 And as I understand it, now I'm not afraid of the future of the Timeshift update, since there is already a flag `--timeshift-auto` there?

Could you tell me what this `git checkout` command does? 
I see that you have already made fixes in the master version. Can I just download this master version directly from the site? Or is this procedure required with a `git checkout`?

**Comment by Schievel1** [comment]
When you update timeshift to version 22.06 or later you would have to remove the --timeshift-old flag. 

Git checkout sets your working directory to the thing you check out. In this case you gave the command git checkout fix-snap-dir-check, this took the files from the inner guts of the .git directory and put them into the working directory. (The grub-btrfs directory in this case) 

For example, type git log. (You can quit git log by typing 'q') What you see is all the commits we did, commits are like points in time, and every time I do something meaningful on that project a save that state. You can jump to any commit with the commits SHA, the SHA are the alphanumeric codes in the git log that look like gibberish (like sfj67s24s3...)
Give git checkout sfj67s... and it will take you to this commit, that is it will make the state of the working directory the same like is was when this commit was done.

**Comment by McGrey86** [comment]
Thanks a lot for this clarification. And in general for a quick and clear response to the problem.
I wish you further successful development of your projects!

**Comment by ismay** [comment]
> The pure script in /etc/grub.d does work without inotify and this is what grub-btrfs is mostly about. The daemon does not work without inotify, but the daemon is just a nice gimmick and not the main thing here. That's why I added it as optional dependency in the readme.

Would be good to list it as an optional dependency for the arch package in that case.

**Comment by korakios** [comment]
Since Timeshift version in Fedora doesn't work well with grub-btrfs, 
(adding the "--timeshift-old" flag , partially works . On boot ,grub lags a snapshot behind )
I suggest that the issue remain open to better inform Fedora 37 users 
Thanks for your contribution :)
