### ISSUE TITLE
emerge: there are no ebuilds to satisfy "virtual/awk".

### ISSUE THREAD

**Issue by Henryws** [Antynea/grub-btrfs#246]
I get this error when attempting to install:

```
emerge: there are no ebuilds to satisfy "virtual/awk".
(dependency required by "app-backup/grub-btrfs-4.12::guru" [ebuild])
(dependency required by "grub-btrfs" [argument])
```

**Comment by Schievel1** [comment]
Thanks for reporting that, but I'm afraid the problem lief within gentoos guru and not here.

They recently did a package move of awk from virtual/awk to app-alternatives/awk. https://github.com/gentoo/gentoo/commit/1b39922b75edcd897083f7b0d91aded7ba0523e4

But they haven't done this yet for the packages on guru that depend on awk as well.

**Comment by Henryws** [comment]
So I'll have to wait for them to update?

**Comment by Schievel1** [comment]
I'm afraid yes, this is not something we can do. Gentoo devs (or Guru contributors) do the packaging on their site. We just provide the code as a tarball and we have no power over how distributions package that or if they break their packages.
You could install manually in the meantime, that is cloning the git repo and running `sudo make OPENRC=true SYSTEMD=false install`  in it. That is actually all you need to do.

**Comment by Henryws** [comment]
Awesome! I'll install after school.
