### ISSUE TITLE
I plan to migrate from Snapper to btrbk, does grub-btrfs support btrbk?

### ISSUE THREAD

**Issue by daiaji** [Antynea/grub-btrfs#247]
Basically I found a pacman hook for btrbk, but I don't know if it's available, and then the only thing preventing me from migrating btrbk is whether grub-btrfs supports btrbk.

Since Snapper itself does not support the file system layout recommended by Archwiki, it does not natively support synchronizing snapshots to remote servers.

Then the tool that supports Snapper synchronization to remote servers is almost unavailable, so it seems that migrating from Snapper to btrbk will be easier, at least btrbk is still actively developed, and natively supports sending snapshots to remote servers.

On the way to replace the NVME SSD, I planned to securely erase the old SSD and sell it second-hand, but I forgot to confirm which SSD I installed on the computer, resulting in file loss, but it seems that there is an old backup in the NAS , and modern browsers all have remote backup functions. To be honest, there is not much loss, but this is enough to prove that stand-alone backups cannot resist file loss caused by wrong operations, but I think I should not need to make another backup for NAS. First of all, I did not The budget is adequate enough to support this kind of backup, and secondly I don't think my mistakes can destroy all backups on local and remote servers.

Snapper really doesn't work well, Snapper doesn't work out of the box for me due to my filesystem layout, and restoring snapshots requires additional components.

Snapper also has some performance issues that I can't understand at all.

**Comment by daiaji** [comment]
> so if that btrfbk does nothing fancy like timeshift
That's why I abandoned timeshift, the layout is really quite fancy, Snapper's layout can be called clumsy, timeshift also lacks a CLI client running in a Xorg-free environment, and of course I know that timeshift was developed for GUI users.

**Comment by Schievel1** [comment]
I don't want to talk you out of it (on the contrary: I am happy if someone tries out btrbk with this and other users find this issue) but timeshift does have a CLI interface. It is not as mighty and powerful as the CLI from snapper, with all the fancy tables and stuff, but it is there and I use it on a daily basis. 
Just do `timeshift --create` and it will make you a snapshot.

**Comment by daiaji** [comment]
The last time I used timeshift on my VPS, I found that I could not start it because I lacked x11 components, and I could not start the CLI without x11 components, which was very strange to me.

**Comment by daiaji** [comment]
The last time I used the timeshift CLI on my VPS, I found that I could not start it because of the lack of x11 components. It was strange to me that I could not start the CLI without x11 components.

**Comment by Schievel1** [comment]
Any updates on this? Were you successful?

**Comment by daiaji** [comment]
The migration is complete and the remote backup snapshot of btrbk is functional.
