### ISSUE TITLE
Grub menu not work

### ISSUE THREAD

**Issue by mhagnumdw** [Antynea/grub-btrfs#251]
Problem:
- In the grub screen, when selecting the `Fedora Linux snapshots` menu, nothing happens and it goes back to the first option.

Versions:
- Fedora 37
- grub-btrfs 4.12-master-2022-12-10T21:20:15+00:00
- Timeshift v21.09.1

UEFI?
- Yes.
```terminal
$ [ -d /sys/firmware/efi ] && echo UEFI || echo BIOS
UEFI
```

`sudo timeshift --list` return 7 snapshots.

The `/boot/grub2/grub-btrfs.cfg` file appears to be populated with the 7 snapshots. But I don't know if the file is correct.

File `/etc/default/grub-btrfs/config`:
```terminal
$ grep -P -v '(^#|^\s*$)' /etc/default/grub-btrfs/config
GRUB_BTRFS_VERSION=4.12-master-2022-12-10T21:20:15+00:00
GRUB_BTRFS_IGNORE_SPECIFIC_PATH=("@")
GRUB_BTRFS_IGNORE_PREFIX_PATH=("var/lib/docker" "@var/lib/docker" "@/var/lib/docker")
GRUB_BTRFS_GRUB_DIRNAME="/boot/grub2"
GRUB_BTRFS_GBTRFS_DIRNAME="/boot/grub2"
GRUB_BTRFS_MKCONFIG=/usr/sbin/grub2-mkconfig
GRUB_BTRFS_SCRIPT_CHECK=grub2-script-check
```

`grub-btrfsd.service`:
```terminal
$ sudo systemctl cat grub-btrfsd.service | grep -P -v '(^#|^\s*$)'
[Unit]
Description=Regenerate grub-btrfs.cfg
[Service]
Type=simple
LogLevelMax=notice
Environment="PATH=/sbin:/bin:/usr/sbin:/usr/bin"
EnvironmentFile=/etc/default/grub-btrfs/config
ExecStart=/usr/bin/grub-btrfsd --syslog --timeshift-auto --timeshift-old
[Install]
WantedBy=multi-user.target
```

File `/boot/grub2/grub.cfg`:
```
# ...
### BEGIN /etc/grub.d/41_snapshots-btrfs ###
submenu 'Fedora Linux snapshots' {
    configfile "${prefix}/grub-btrfs.cfg"
} 
### END /etc/grub.d/41_snapshots-btrfs ###
```

Can anyone help me? Do you need any more information?

**Comment by mhagnumdw** [comment]
In Grub Customize, nothing appears inside the submenu:

![image](https://user-images.githubusercontent.com/17688846/209278159-6f1a6742-3124-4993-b2a3-003ba0c330ca.png)

**Comment by kevinchevreuil** [comment]
Hello, 

I proposed a solution here:

View #252

**Comment by Schievel1** [comment]
Maybe this is related to #234? What is your version of btrfs-progs?

**Comment by mhagnumdw** [comment]
> btrfs-progs

6.0.2-1.fc37

**Comment by Schievel1** [comment]
Hi, yes the culprit is grub-btrfs-4.12. It does not work very well with the pre 22.06 versions of timeshift. 4.12 does not support the `--timeshift-old` flag. 
Please install manually by cloning the repo, going into the cloned directory and doing `sudo make install`.

**Comment by mhagnumdw** [comment]
> Please install manually by cloning the repo, going into the cloned directory and doing `sudo make install`

It was exactly how I did it from the beginning.

**After doing two things the problem was solved**, I still don't know which one solved it:
- `btrfs-progs` updated to `6.1-2.fc37`
- `grub2-mkconfig -o /boot/grub2/grub.cfg` instead of `/boot/efi/EFI/fedora/grub.cfg` (I needed to restore /boot/efi/EFI/fedora/grub.cfg to the original version)

Since I've done a lot of things, I'm going to redo all the steps from a clean install of Fedora 37 and come back here.

**Comment by mhagnumdw** [comment]
Steps retraced right now on a clean, up-to-date install of Fedora 37 and **everything worked fine!**

Versions:
- Fedora 37 (up-to-date: dnf update --refresh)
- grub-btrfs 4.12-master-2022-12-10T21:20:15+00:00 (installed from sources, master branch)
- Timeshift v21.09.1
- btrfs-progs 6.1-2.fc37

Tip: [since Fedora 34 and above](https://fedoraproject.org/wiki/GRUB_2#Updating_the_GRUB_configuration_file), even if EFI, use to update grub: `sudo grub2-mkconfig -o /boot/grub2/grub.cfg`

ps: configuration details in the first post

**Comment by Schievel1** [comment]
Happy to hear that, although I wonder what was the problem in the first place now :/
