### ISSUE TITLE
Snapshots not being detected

### ISSUE THREAD

**Issue by bjroden** [Antynea/grub-btrfs#254]
After a recent update on EndeavourOS, grub-btrfs has not been able to find snapshots in the directory. It is able to detect whenever snapshots are created or deleted, and it gives this output whenever that happens:

```
sudo grub-btrfsd /.snapshots --verbose
grub-btrfsd starting up...
Watching /.snapshots for new snapshots...
Detected snapshot creation/ deletion, recreating Grub menu
Detecting snapshots ...
No snapshots found.
If you think an error has occurred, please file a bug report at "https://github.com/Antynea/grub-btrfs"
Unmount /tmp/grub-btrfs.PvfTtjMUFv .. Success
Grub submenu recreated
```

I do have snapshots in the /.snapshots directory though. I am using a layout similar to the one on the [Archwiki snapper page](https://wiki.archlinux.org/title/Snapper#Suggested_filesystem_layout) where they are stored on a separate @snapshots subvolume and mounted to /.snapshots.

```
sudo ls -al /.snapshots
drwxr-x--- 1 root root 338 Dec 26 20:33 .
drwxr-xr-x 1 root root 150 Oct 19 19:09 ..
drwxr-xr-x 1 root root  32 Aug 29 14:21 1
drwxr-xr-x 1 root root  32 Nov  7 11:28 1040
drwxr-xr-x 1 root root  32 Nov  7 12:38 1056
drwxr-xr-x 1 root root  32 Dec 14 14:00 1633
drwxr-xr-x 1 root root  32 Dec 18 12:12 1643
drwxr-xr-x 1 root root  32 Dec 26 01:10 1645
drwxr-xr-x 1 root root  72 Dec 18 13:12 1646
drwxr-xr-x 1 root root  32 Dec 26 01:10 1656
drwxr-xr-x 1 root root  72 Dec 18 23:35 1657
drwxr-xr-x 1 root root  32 Dec 19 00:00 1658
drwxr-xr-x 1 root root  32 Dec 20 00:00 1661
drwxr-xr-x 1 root root  32 Dec 20 22:00 1664
drwxr-xr-x 1 root root  32 Dec 21 20:00 1665
drwxr-xr-x 1 root root  32 Dec 26 01:10 1666
drwxr-xr-x 1 root root  72 Dec 21 20:34 1667
drwxr-xr-x 1 root root  32 Dec 21 20:38 1670
drwxr-xr-x 1 root root  72 Dec 21 20:39 1671
drwxr-xr-x 1 root root  32 Dec 26 01:10 1672
drwxr-xr-x 1 root root  72 Dec 25 16:50 1673
drwxr-xr-x 1 root root  32 Dec 26 01:10 1674
drwxr-xr-x 1 root root  72 Dec 25 16:50 1675
drwxr-xr-x 1 root root  32 Dec 25 16:51 1676
drwxr-xr-x 1 root root  72 Dec 25 16:51 1677
drwxr-xr-x 1 root root  32 Dec 25 16:51 1678
drwxr-xr-x 1 root root  72 Dec 25 16:51 1679
drwxr-xr-x 1 root root  32 Dec 25 17:00 1680
drwxr-xr-x 1 root root  32 Dec 26 13:43 1681
drwxr-xr-x 1 root root  72 Dec 25 17:11 1682
drwxr-xr-x 1 root root  32 Dec 26 01:00 1683
drwxr-xr-x 1 root root  32 Dec 26 13:43 1684
drwxr-xr-x 1 root root  72 Dec 26 13:19 1685
drwxr-xr-x 1 root root  32 Dec 26 13:21 1686
drwxr-xr-x 1 root root  72 Dec 26 13:21 1687
drwxr-xr-x 1 root root  32 Dec 26 13:26 1688
drwxr-xr-x 1 root root  72 Dec 26 13:26 1689
drwxr-xr-x 1 root root  32 Dec 26 13:26 1690
drwxr-xr-x 1 root root  72 Dec 26 13:27 1691
drwxr-xr-x 1 root root  32 Dec 26 14:00 1692
drwxr-xr-x 1 root root  32 Dec 26 14:10 1693
drwxr-xr-x 1 root root  72 Dec 26 14:10 1694
drwxr-xr-x 1 root root  32 Dec 26 14:13 1696
drwxr-xr-x 1 root root  72 Dec 26 14:13 1697
drwxr-xr-x 1 root root  32 Dec 26 20:33 1698
```
This also happens when I run grub-mkconfig manually. I have installed the inotify-tools optional dependency and disabled the old grub-btrfs.path systemd unit, since it seems to have been replaced with grub-btrfsd from what I can gather.

**Comment by The-Repo-Club** [comment]
i on base arch have also just come across this issue

**Comment by Evan-aja** [comment]
**+1** for ArchLinux

Linux nitro 6.1.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:55 +0000 x86_64 GNU/Linux

System Information
        Manufacturer: Acer
        Product Name: Nitro AN515-57
        Version: V1.19
        UUID: 682e0646-4a65-ec11-80e2-088fc3381eb0
--
Base Board Information
        Manufacturer: TGL
        Product Name: Scala_TLS
        Version: V1.19
        Asset Tag: Type2 - Board Asset Tag

**Comment by Antynea** [comment]
Btrfs-progs is buggy
Otime return nothing
https://github.com/adam900710/btrfs-progs/commit/fd138f8678808717635a145832c1b13320ce6cd2

**Comment by LorenzoBettini** [comment]
I've just experienced this problem as well, and, indeed, it seems to happen after the update of `btrfs-progs-6.1-1-x86_64`

**Comment by bjroden** [comment]
Downgrading btrfs-progs to 6.0.2-1 fixed the issue for me.

**Comment by pierostrada** [comment]
Thank you.

For now I got back to version 6.0.2-1 from /var/cache/pacman/pkg/btrfs-progs-6.0.2-1-x86_64.pkg.tar.zst
and flagged
IgnorePkg = btrfs-progs
in /etc/pacman.conf

sudo downgrade btrfs-progs
sudo grub-mkconfig -o /boot/grub/grub.cfg

reboot
By so doing, it works again both in UEFI and legacy bios.

Hope it will be fixed soon: all the best,
Piero

**Comment by Draguljche** [comment]
and instructions for Debian based distros:

First download binary file: [http://ftp.de.debian.org/debian/pool/main/b/btrfs-progs/btrfs-progs_6.0.2-1_amd64.deb](url)
then sudo dpkg -i /path/to/the/file/btrfs-progs_6.0.2-1_amd64.deb
and then lock the version through Muon Package Manager or dont upgrade btrfs-progs.

**Comment by TheLinuxNinja** [comment]
#https://github.com/kdave/btrfs-progs/issues/562

**Comment by TheLinuxNinja** [comment]
Until this is fixed, I changed line 295 of 41_snapshots-btrfs on my local system to reference field 12 instead of the missing field 13. This is a good workaround for me. Once btrfs-progs is fixed, I can revert my local change.

**Comment by jfabernathy** [comment]
core/btrfs-progs 6.1-2  is what I see today and it's working for me on Archlinux

**Comment by pierostrada** [comment]
Great" Thanks Mr. [jfabernathy](https://github.com/jfabernathy)

**Comment by UnFunnyGuy** [comment]
> core/btrfs-progs 6.1-2 is what I see today and it's working for me on Archlinux

is this the latest?

**Comment by jfabernathy** [comment]
> > core/btrfs-progs 6.1-2 is what I see today and it's working for me on Archlinux
> 
> is this the latest?

I guess that depends on the Distro. For Archlinux:
[https://archlinux.org/packages/core/x86_64/btrfs-progs/](url)

**Comment by UnFunnyGuy** [comment]
> > > core/btrfs-progs 6.1-2 is what I see today and it's working for me on Archlinux
> > 
> > is this the latest?
> 
> I guess that depends on the Distro. For Archlinux:
> [https://archlinux.org/packages/core/x86_64/btrfs-progs/](url)

I am on  arch, just making sure it's fixed on the latest. I had to downgrade yesterday.

**Comment by LorenzoBettini** [comment]
Yes, with the latest it's fixed

**Comment by Schievel1** [comment]
so this was just a small detour btrfs-progs took and with the newest version it's working again?

**Comment by nastasie-octavian** [comment]
The upstream btrfs-progs isn't fixed yet.

The Archlinux maintainer for the btrfs-progs package released a new package build https://github.com/archlinux/svntogit-packages/commit/1998182d93ed81a610d245cb2588453d00bd8801, 6.1-**2** (upstream version 6.1, build number 2 for Archlinux), that includes a patch that fixes this issue. 

As far as I can tell that patch hasn't yet been included in the upstream version of btrfs-progs, for now it's something extra that the Archlinux build of btrfs-progs carries.

**Comment by The-Repo-Club** [comment]
this seems to have been fixed as of today 

![image](https://user-images.githubusercontent.com/9284733/210138889-c72bcbc8-f01b-40a5-af6f-5f07249e0659.png)

**Comment by Schievel1** [comment]
> The upstream btrfs-progs isn't fixed yet.
> 
> The Archlinux maintainer for the btrfs-progs package released a new package build [archlinux/svntogit-packages@1998182](https://github.com/archlinux/svntogit-packages/commit/1998182d93ed81a610d245cb2588453d00bd8801), 6.1-**2** (upstream version 6.1, build number 2 for Archlinux), that includes a patch that fixes this issue.
> 
> As far as I can tell that patch hasn't yet been included in the upstream version of btrfs-progs, for now it's something extra that the Archlinux build of btrfs-progs carries.

Hm alright. But even on Gentoos testing btrfs-progs is only on 6.0.2 yet. So I think there is a good chance this is fixed by the time it hits the other distros. Except Debian Sid maybe.

**Comment by pierostrada** [comment]
[Schievel1](https://github.com/Schievel1), I see and have it fixed:

> pacman -Qi btrfs-progs
Nome                      : btrfs-progs
Versione                  : 6.1-2
Descrizione               : Btrfs filesystem utilities
Architettura              : x86_64
URL                       : https://btrfs.wiki.kernel.org
Licenze                   : GPL2
Gruppi                    : Nessuno
Fornisce                  : btrfs-progs-unstable
Dipenda da                : glibc  util-linux-libs  lzo  zlib  zstd  libgcrypt
Dipendenze opzionali      : python: libbtrfsutil python bindings [installato]
                            e2fsprogs: btrfs-convert [installato]
                            reiserfsprogs: btrfs-convert [installato]
Richiesto da              : grub-btrfs  libblockdev  libguestfs
Opzionale per             : gparted  timeshift
Conflitti con             : btrfs-progs-unstable
Sostituisce               : btrfs-progs-unstable
Spazio richiesto          : 5,16 MiB
Pacchettizzatore          : Tobias Powalowski <tpowa@archlinux.org>
Data di creazione         : ven 30 dic 2022, 06:52:56
Data di installazione     : ven 30 dic 2022, 15:27:41
Motivo dell'installazione : Installato esplicitamente
Script di install         : Sì
Convalidato da            : Firma

**Comment by geckolinux** [comment]
Thanks to everyone for identifying the issue.
@nastasie-octavian Do you know if this is something that the upstream Btrfs developers consider to be a bug, or is it only a bug for grub-btrfs? Because Debian for example I think usually doesn't like to patch upstream projects' code, and I'm wondering if Debian Sid will ever get the fix.

**Comment by nastasie-octavian** [comment]
The patch is on the upstream mailing list https://lore.kernel.org/linux-btrfs/cover.1672120480.git.wqu@suse.com/T/#t and it has a bunch of reviewed-by and no objections against it, so I would assume that the upstream developers consider it a bug and are going to fix it. I don't know how soon though.

**Comment by dirtydog01** [comment]
I had to "sudo apt-mark hold btrfs-progs" to stop it from updating for now.

**Comment by dirtydog01** [comment]
I had to "sudo apt-mark hold btrfs-progs" to stop it from updating for now.

**Comment by nastasie-octavian** [comment]
As of yesterday the bug has been fixed upstream and a new stable version, **v6.1.1**, has been released. You should check with your particular distribution for when that version will be made available.

**Comment by dirtydog01** [comment]
Thanks

**Comment by PartyWumpus** [comment]
Fixed for me on endevourOS!

**Comment by Archcan** [comment]
Plasma-dev Manjaro. Snapshot creation detected after updating grub. Thanks!

```
$ pacman -Q grub-btrfs
grub-btrfs 4.12-2
$ pacman -Q timeshift-autosnap
timeshift-autosnap-manjaro 0.10-1
$ pacman -Q timeshift
timeshift 22.11.2-1
$ pacman -Q btrfs-progs
btrfs-progs 6.1.2-1
```

**The bug was more severe here:** No snapshot detected and multiple entries of the same drive (up to 5). Despite the fact that btrfs-progs was updated on Jan. 3rd and 7th, we did not use grub-btrfs, nor timeshift for the last 2 weeks or so.

All is good now.
