### ISSUE TITLE
"grub-mkconfig -o /boot/grub/grub.cfg" returns "No snapshots found" and no GRUB menu entry is being created

### ISSUE THREAD

**Issue by Ai-Elias** [Antynea/grub-btrfs#256]
I'm running a minimal Arch environment with btrfs setup with Arch's recommended subvolume layout. I have snapper and snap-pac packages. Both are configured and running, generating snapshots to /.snapshots

grub-btrfsd is running and is configured to look in /.snapshots for snapshots.

Likely, this is my error somewhere. Any suggestions for what I might be missing? I'm using coreboot, I'm not sure if that might be a problem.

**Comment by Peppe61** [comment]
Same here: running Arch on LVM, using timeshift and timeshift autosnap. Timeshift still show 4 snapshots available; grub-btrfs finds nothing.

**Comment by Antynea** [comment]
See #254

**Comment by Draguljche** [comment]
ok thats my exactly problem to. But Im using Debian Sid(SpiralLinux). Timeshift shows snapshots but no Grub menu entry. Timeshift-autosnap-apt are to installed.

**Comment by pakyrs** [comment]
Run the script directly, if it doesn't find the snapshots, it's likely cause it's looking elsewhere or avoiding the location  ``` sudo /etc/grub.d/41_snapshots-btrfs ``` grub not displaying it is just a consequence of this script not running.

**Comment by danboid** [comment]
@Antynea I'm sorry but this does not appear to be a problem with btrfs-progs. Maybe there is/was a btrfs-progs problem too but something has broken in btrfs-grub for sure.

I've tried the latest git version of grub-btrfs under both Debian 11 and Debian Testing (Debian 12) and grub-btrfs fails to find any of my timeshift btrfs snapshots using btrfs-progs 5.x under Debian 11 and 6.x under Testing. However, if I checkout grub-btrfs from approx a year ago (just before all the openrc stuff was introduced) then grub-btrfs does find my snapshots.

This Kali / Debian packaged version is also successful in finding my snapshots:

http://http.kali.org/pool/main/g/grub-btrfs/grub-btrfs_4.12-0kali1~jan+nur1_all.deb

**Comment by Schievel1** [comment]
Hm, thats interesting. 
Are you using some special characters anywhere? Your username, your distros name if you set that in the config or something like that?

Actually grub-btrfs takes the output of `btrfs subvolume list -sa /` and gets the snapshots from that. What does that output for you?

**Comment by pakyrs** [comment]
@danboid I am on 4.11-Kali2 which is stable, by changing the parameter to 13 in that version my system is able to list the snapshots when you fire update-grub. To my understanding, you don't need that in v. 4.12-Kali1, however, that is in Kali experimental so I am fine with the fix for now.

**Comment by danboid** [comment]
> btrfs subvolume list -sa /

btrfs subvolume list -sa /
ID 485 gen 379501 cgen 373315 top level 5 otime 2023-03-26 14:48:54 path <FS_TREE>/timeshift-btrfs/snapshots/2023-03-26_14-48-51/@
ID 486 gen 373317 cgen 373316 top level 5 otime 2023-03-26 14:48:56 path <FS_TREE>/timeshift-btrfs/snapshots/2023-03-26_14-48-51/@home

**Comment by kamkarthi** [comment]
On ubuntu 22.04, I just need to replace line #301 as below and thereafter running update-grub able to generate snapshot menu entries.
   	        #local path_snapshot=${snap[@]:13:${#snap[@]}}
   		local path_snapshot=$(echo "${snap}" |awk '{print $NF}')

**Comment by danboid** [comment]
> On ubuntu 22.04, I just need to replace line #301 as below and thereafter running update-grub able to generate snapshot menu entries. #local path_snapshot=${snap[@]:13:${#snap[@]}} local path_snapshot=$(echo "${snap}" |awk '{print $NF}')
> 
> Note: although I'm using snapper + grub-btrfs, the same should work fine with timeshift

Thanks @kamkarthi ! Your suggested fix works to enable the latest grub-btrfs to successfully find snapshots under Debian.

**Comment by danboid** [comment]
I wrote this guide on how I got systemd to update my GRUB menu with snapshots every time I shutdown or reboot because the grub-btrfsd doesn't work with systemd for me:

https://github.com/Antynea/grub-btrfs/discussions/270
