### ISSUE TITLE
minor issue: Arch package missing inotify-tools dependency

### ISSUE THREAD

**Issue by ericx** [Antynea/grub-btrfs#258]
grub-btrfsd wants inotifywait and the Arch package does not require inotify-tools.

$ systemctl status grub-btrfsd.service               
× grub-btrfsd.service - Regenerate grub-btrfs.cfg                                                        
     Loaded: loaded (/usr/lib/systemd/system/grub-btrfsd.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Thu 2022-12-29 08:26:54 EST; 3s ago
   Duration: 3ms                                                                                         
    Process: 86313 ExecStart=/usr/bin/grub-btrfsd --syslog /.snapshots (code=exited, status=1/FAILURE)
   Main PID: 86313 (code=exited, status=1/FAILURE)                                                       
        CPU: 3ms                                    
                                                                                                         
Dec 29 08:26:54 ella.ericx.net grub-btrfsd[86315]: [!] inotifywait was not found, exiting. Is inotify-too
ls installed?                                       
Dec 29 08:26:54 ella.ericx.net systemd[1]: grub-btrfsd.service: Main process exited, code=exited, status=
1/FAILURE                                                                                                
Dec 29 08:26:54 ella.ericx.net systemd[1]: grub-btrfsd.service: Failed with result 'exit-code'.
[Exit 3 ]

**Comment by Antynea** [comment]
[inotify-tools is a optional Dependency.](https://archlinux.org/packages/community/any/grub-btrfs/)

@Schievel1 @maximbaz Is this the expected behaviour ?

**Comment by Schievel1** [comment]
Yes it is, if we don't check for inotify and it is not available we would end up in a very fast infinite loop.

**Comment by maximbaz** [comment]
And to explain why it's optional, it's a custom in Arch to mark dependency as optional when it's not required by the core application itself, when it's not required by every single user of the application, which seemed to be the case with `grub-btrfsd` service, which is just one of possible ways people would want to trigger `grub-btrfs`, and it's a service that is not pre-enabled, and requires user action to be activated.

**Comment by Antynea** [comment]
Thank you both for your intervention :)
I hope you are well.

**Comment by ericx** [comment]
Thank you.
