### ISSUE TITLE
System stuck on grub command prompt after apt update and restart - empty grub.cfg

### ISSUE THREAD

**Issue by kyrpro** [Antynea/grub-btrfs#259]
Hi there,

After running apt update that included a kernel update, the system cannot boot after a restart and is stuck on the grub command prompt. After some checks I noticed that 'grub.cfg' in '/boot/grub/' (same dir contains 'grub-btrfs.cfg') is empty. Some info on the setup and grub parameters:
- OS: Linux Mint 20.1
- root=hd0,gpt3
- prefix=(hd0,gpt3)/@/boot/grub
- grub_pltaform=efi
- package_version=2.04-1ubuntu44.2

Please advise.

**Comment by Schievel1** [comment]
Not sure if that is a problem of grub-btrfs, since we only append something to the grub.cfg. 
Looks like your grub config generation is broken. I guess you are in a live system now? Can you chroot into your system and run grub-mkconfig?
