### ISSUE TITLE
line 569: /boot/grub/grub-btrfs.new: No such file or directory 

### ISSUE THREAD

**Issue by InvisibleRasta** [Antynea/grub-btrfs#263]
I am running fedora 37. I just installed grub-btrfs and as the Usage guide says I run sudo grub2-mkconfig -o /boot/grub2/grub.cfg
but it fails. It seems that  it should be /boot/grub**2**/... and not just /boot/grub/
Detecting snapshots ...
/etc/grub.d/41_snapshots-btrfs: line 569: /boot/grub/grub-btrfs.new: No such file or directory

**Comment by kevinchevreuil** [comment]
You can set this param in this file :

/etc/default/grub-btrfs/config

Update these params:
GRUB_BTRFS_GRUB_DIRNAME="/boot/grub2"
GRUB_BTRFS_MKCONFIG=/usr/bin/grub2-mkconfig

And run this command: sudo grub2-mkconfig /boot/grub2/grub.cfg

**Comment by RedSnt** [comment]
Brilliant tip @kevinchevreuil  - I had to further uncomment `GRUB_BTRFS_SCRIPT_CHECK=grub2-script-check` on Fedora 41 (Nobara 41 to be precise).
