### ISSUE TITLE
Failed to enable grub-brtfs.path

### ISSUE THREAD

**Issue by thinkjk** [Antynea/grub-btrfs#265]
Hello! I'm just getting started with this and a clean install of the latest version of endeavourOS.

When I try to enable grub-btrfs.path I get an error.

```
[root@laptop /]# systemctl enable --now grub-btrfs.path
Failed to enable unit: Unit file grub-btrfs.path does not exist.
```

Can someone please point me in the right direction?

**Comment by Esinkingz** [comment]
Since the 4.12 release, the grub-btrfsd daemon has replaced the grub-btrfs.pathsystemctl enable --now grub-btrfs.path

so you can
 sudo systemctl enable grub-btrfsd
