### ISSUE TITLE
Kali - grub-btrfsd.service doesn't exist

### ISSUE THREAD

**Issue by pakyrs** [Antynea/grub-btrfs#267]
Installed grub-btrfs on Kali, but it doesn't come with the grub-btrfsd daemon?

`systemctl enable --now grub-btrfsd`
`Failed to enable unit: Unit file grub-btrfsd.service does not exist.`

**Comment by Schievel1** [comment]
What version do you have?

**Comment by pakyrs** [comment]
It's `4.11-0kali2`

**Comment by Schievel1** [comment]
Then you can either use the instructions from 4.11 (by going to that releases commit for example) or you can install 4.12 by cloning the GitHub repo and running make install manually.
