### ISSUE TITLE
No initrd line when harmonized entries chosen

### ISSUE THREAD

**Issue by daftaupe** [Antynea/grub-btrfs#27]
Hello,

I've noticed that the script doesn't generate initrd lines when the variable
GRUB_BTRFS_CREATE_ONLY_HARMONIZED_ENTRIES is set to "true" in my /etc/default/grub.

This makes the grub.cfg unusable for snapshots unfortunately.

**Comment by Antynea** [comment]
Hello,

thanks for feedback,
fix in progress...

**Comment by Antynea** [comment]
patch done
Don't hesitate to test it :)

**Comment by daftaupe** [comment]
Hello @Antynea , thanks for the quick patch :) It's working now, at least in my case.

**Comment by Antynea** [comment]
thanks for feedback,
glad to learn that it works for you :)
