### ISSUE TITLE
Snapper + Debian 12 broken after last couple commits

### ISSUE THREAD

**Issue by david-cortes** [Antynea/grub-btrfs#273]
If installing `grub-btrfs` from the current master branch, snapper snapshots will not be found in debian.

I did some testing with previous versions, and can tell for now that:
* Commit ec5ff8b4bc1d1cc91e2fed5d1361bb0818928e54 makes it fail due to some syntax error compared to the previous commit. Not sure if it's related.
* Under commit 879bec36975ee66aca63db185ccb39dea678c054 (throughout the current commit at the time of writing, c7d4bbbe4576d5777e750759676710a303bfe87e) it then doesn't fail due to some syntax error when findind snapshots, but it reports no snapshots being found despite there being snapper snapshots.
* Under commit 1556c345dac23c1f13ca6470c7ff68a22d56971c (the one that commes immediately before the commit listed in the first bullet point), everything seems to work correctly - snapshots are found, a boot menu is generated, and it's possible to boot into those snapshots.

**Comment by Schievel1** [comment]
Hi, thanks for bisecting this. The syntax error from your first bullet point isn't related, this was just my git commit hooks messing up the config file. 

Have you tried this? https://github.com/Antynea/grub-btrfs/issues/256#issuecomment-1492656696

**Comment by Schievel1** [comment]
sorry for autoclosing this so fast. Please check if latest commit fixes this. I think it should. 

Still freaks me out that different distros bash versions differ so much.

**Comment by david-cortes** [comment]
Thanks. Tried again - it works with the latest commit (c6550d0d96c9bb01b686f28f1abcac0ad0a9f207), and doesn't find any snapshots if I enquote that variable `snap` on `https://github.com/Antynea/grub-btrfs/blob/master/41_snapshots-btrfs:L300` as it was before this last commit.
