### ISSUE TITLE
[Arch] No snapshots found

### ISSUE THREAD

**Issue by MichaelTrip** [Antynea/grub-btrfs#279]
Hi,

I just tried to configure grub-btrfs but it doesn´t seem to work. 

1: i start the daemon with `sudo /usr/bin/grub-btrfsd --verbose --timeshift-auto`
2: i create a snapshot with timeshift (ui)
3: Daemon says it detects snapshots, but it does not detect the snapshot:

```
Watches established.
/run/timeshift/14265/backup/timeshift-btrfs/snapshots/ CREATE,ISDIR 2023-04-25_21-04-28
Detected snapshot creation/ deletion, recreating Grub menu
Generating grub configuration file ...
Found theme: /boot/grub/themes/Arch/theme.txt
Found linux image: /boot/vmlinuz-linux-lts
Found initrd image: /boot/intel-ucode.img /boot/initramfs-linux-lts.img
Found fallback initrd image(s) in /boot:  intel-ucode.img initramfs-linux-lts-fallback.img
Warning: os-prober will be executed to detect other bootable partitions.
Its output will be used to detect bootable binaries on them and create new boot entries.
Adding boot menu entry for UEFI Firmware Settings ...
Detecting snapshots ...
No snapshots found.
If you think an error has occurred, please file a bug report at "https://github.com/Antynea/grub-btrfs"
Unmount /tmp/grub-btrfs.bkevkd6gSG .. Success
Detecting snapshots ...
No snapshots found.
If you think an error has occurred, please file a bug report at "https://github.com/Antynea/grub-btrfs"
Unmount /tmp/grub-btrfs.4uceU8I7Df .. Success
Found memtest86+ image: /boot/memtest86+/memtest.bin
done
Grub menu recreated
Watching /run/timeshift/14265/backup/timeshift-btrfs/snapshots for new snapshots...
Setting up watches.
Watches established.
```

And so the grub bootmenu is not updated. I have the debug log with the `set -x` added to the `41_snapshots-btrfs` attached.
[log.txt](https://github.com/Antynea/grub-btrfs/files/11325957/log.txt)

**Comment by Schievel1** [comment]
Are you running 4.12 or from a git commit? 

We had some problems with a few commits a few weeks ago, see https://github.com/Antynea/grub-btrfs/issues/273

that should be fixed in the latest commit, though.

**Comment by MichaelTrip** [comment]
> Are you running 4.12 or from a git commit?
> 
> We had some problems with a few commits a few weeks ago, see #273
> 
> that should be fixed in the latest commit, though.

I just tried both the script and the config from the last commit (main branch) but it doesn´t work :(

**Comment by Schievel1** [comment]
Hm, btrfs-progs was failing us a few times already in the past. Maybe that's just that again? Has it been updated on arch lately?
See https://github.com/Antynea/grub-btrfs/issues/254

Maybe try downgrading to an earlier version.
