### ISSUE TITLE
Can't enable grub-btrfs.service

### ISSUE THREAD

**Issue by Schievel1** [Antynea/grub-btrfs#281]
### Discussed in https://github.com/Antynea/grub-btrfs/discussions/280

<div type='discussions-op-text'>

<sup>Originally posted by **tav9122** April 26, 2023</sup>
As the title says, when I run `systemctl enable grub-btrfs.path` I got the output `Unit btrfs.path does not exist`</div>

> ![IMG_20230428_201527.jpg](https://user-images.githubusercontent.com/93392095/235157580-639cc1a9-ae84-4cc2-8f3a-d79e224ec25d.jpg)
> 
> I couldn't find snapshots menu in the grub boot so I checked with the systemctl status, do you have any idea what cause this

**Comment by Schievel1** [comment]
Try running grub-btrfsd with verbose flag and/or manually. It will give you more info what is wrong. 
See:
https://github.com/Antynea/grub-btrfs#running-grub-btrfsd-in-verbose-mode

**Comment by tav9122** [comment]
> Try running grub-btrfsd with verbose flag and/or manually. It will give you more info what is wrong. 
> See:
> https://github.com/Antynea/grub-btrfs#running-grub-btrfsd-in-verbose-mode
> 
> If you are running grub-btrfsd as a daemon, the output will be printed to syslog. On Arch you can use `journalctl -f` to watch the syslog.

turned out I was missing the inotify-tools, I added the packeage now but still no snapshots menu in grub, below is the output of `systemctl status grub-btrfsd`
![IMG_20230429_093154.jpg](https://user-images.githubusercontent.com/93392095/235279672-645871ce-cb0c-4bfd-b600-a566c2b994c3.jpg)

**Comment by tav9122** [comment]
> > Try running grub-btrfsd with verbose flag and/or manually. It will give you more info what is wrong. 
> > See:
> > https://github.com/Antynea/grub-btrfs#running-grub-btrfsd-in-verbose-mode
> > 
> > If you are running grub-btrfsd as a daemon, the output will be printed to syslog. On Arch you can use `journalctl -f` to watch the syslog.
> 
> turned out I was missing the inotify-tools, I added the packeage now but still no snapshots menu in grub, below is the output of `systemctl status grub-btrfsd`
> ![IMG_20230429_093154.jpg](https://user-images.githubusercontent.com/93392095/235279672-645871ce-cb0c-4bfd-b600-a566c2b994c3.jpg)
> 
> 

turned out I need to run `grub-mkconfig -o /etc/grub/grub.cfg` at least once

**Comment by Schievel1** [comment]
So this can be closed?

**Comment by tav9122** [comment]
> So this can be closed? 

Yup, sorry couldn't find the close button on my phone

**Comment by Salman7236** [comment]
I think it will be better to make inotify-tools a required dependency when installing grub-btrfs to avoid people opening the same issues in the future. Or at least display a note to the user after installation that says something like, "Please install inotify-tools to enable auto-generation of grub.cfg".
