### ISSUE TITLE
U-boot support

### ISSUE THREAD

**Issue by danboid** [Antynea/grub-btrfs#284]
I have a few SBC's that use U-boot and it'd be great if I could get a grub-btrfs like experience on those. I would like to have most of the features of grub-btrfs replicated for U-boot on my RockPi 4 and VisionFive 2 etc. 

Has anyone previously suggested or considered expanding grub-btrfs to also support U-boot? It may be better to fork it as U-boot-btrfs rather than adding U-boot support into grub-btrfs?

I am suggesting it here first because I think the U-boot devs may deem this too much to integrate into standard U-boot. The standard program for updating the u-boot menu ( /boot/extlinux/extlinux.conf) is u-boot-update.

Do you own any U-boot using devices @Schievel1? Do you know enough about U-boot to know any reason why this couldn't work?

**Comment by danboid** [comment]
https://www.phoronix.com/news/Fedora-U-Boot-x86-BIOS

**Comment by Schievel1** [comment]
I have one, but it's my home NAS with all the important stuff an it. I don't feel very comfortable experimenting with this thing.

But to my understanding most SBCs don't have a monitor attached during boot. I access mine using ssh only. Tbh until this post I didn't even know that there is a menu to choose the kernel to boot. I thought it is just booting the kernel image that in the right place. 

In any way, I think this is so far away from grub-btrfs, which in it's essence is just a script that reads paths and names of snapshots and generated a grub menu out of this information, that it's worth making a separate project out of this.
