### ISSUE TITLE
system booting in read only mode after doing a rollback

### ISSUE THREAD

**Issue by imthenachoman** [Antynea/grub-btrfs#294]
I installed snapper and grub-btrfs and everything was fine.

I rolled back to a snapshot and rebooted the default entry, but it is in read only mode. I can't figure out what I've done wrong?

If it matters/helps, this is the guide I am using to get all this working: https://github.com/david-cortes/snapper-in-debian-guide

**Comment by Schievel1** [comment]
I haven't read the whole guide, but it says 
> Now you should have booted into a READ-ONLY snapshot of your system at the time before atop was installed.

So this is desired behavior, isn't it?

**Comment by imthenachoman** [comment]
This be strange. I did a fresh install and installed all the tools: [snapper](https://github.com/openSUSE/snapper), [grub-btrfs](https://github.com/Antynea/grub-btrfs) and [snapper-rollback](https://github.com/jrabinow/snapper-rollback).

I haven't done any rollbacks and am booting up the default grub menuentry.
 Everything works as expected. The filesystem is not read only. I can do things. 

But it still shows ro for how the kernel was booted:

```
BOOT_IMAGE=/vmlinuz-6.1.0-10-amd64 root=UID... ro rootflags=subvol=@rootfs quite
```

**Comment by Schievel1** [comment]
Yes I have that too, regardless of btrfs or ext4. This is a wild guess, but could it be that this ro option is applied to the initramfs if there is one?

**Comment by imthenachoman** [comment]
I fixed the issue. I did a fresh install and chnaged two things. I'm not sure which fixed the issue, but one of them did. Thank you and sorry about that.

https://github.com/david-cortes/snapper-in-debian-guide/issues/2#issuecomment-1629926033 if you're curious what I did.
