### ISSUE TITLE
Debian default grub option, not select default snapshot or last rollback.

### ISSUE THREAD

**Issue by chriztheanvill** [Antynea/grub-btrfs#295]
Hi.
After making default snapshot or rollback, booting with grub and do not select any snapshot (just leave the count down finish and boot), does not boot with default snapshot or last rollback.

Example:
* Install screenfetch
* boot to the pre snapshot and make a rollback: `sudo snapper --ambit classic rollback` 
* In the grub menu, do not select anything, and finish the countdown, the screenfetch still installed.
* But if in the grub menu, select the pre snapshot or the new writable copy of \# 2, the screenfetch is not installed.
* And I would like to after making a snapshot a default or a rollback, grub by default boot into these.

My config:
```sh
@
@home
@opt
@root
@tmp
@var-cache
@var-log
@var-tmp
@snapshots

```

* Installed grub-btrfs with sudo make install and sudo update-grub
* Also installed grub-btrfs 4.13

**Comment by Schievel1** [comment]
I am not quite sure what you are trying to achieve here. Rolling back a snapshot is not a feature of grub-btrfs. We just provide that snapshot subfolder. Rolling back is done manually or by some btrfs-snapshot  programs like snapper or timeshift.

**Comment by chriztheanvill** [comment]
> I am not quite sure what you are trying to achieve here. Rolling back a snapshot is not a feature of grub-btrfs. We just provide that snapshot subfolder. Rolling back is done manually or by some btrfs-snapshot programs like snapper or timeshift.

Yeah, my mistake, I thought it was fault of grub-btrfs, but even without installing it, I had this issue.

**Comment by arashsm79** [comment]
I've been trying to set up an Ubuntu/Debian installation with functioning rollbacks that allows grub to boot into the rolled back system by default.
[This post](https://moslehian.com/posts/2023/2-reliable-btrfs-snapshots-snapper-debian-ubuntu/) might be helpful for who ever winds up in this issue.
