### ISSUE TITLE
How to remove??

### ISSUE THREAD

**Issue by randyoles** [Antynea/grub-btrfs#307]
Tried to install this with nobara, but can't make it work. How do I remove it and restore my grub?? I have found lots of install guides but no one explaining removal.

**Comment by Schievel1** [comment]
You installed it via package manager? Then remove the package via package manager and run the grub-mkconf command for your distro

**Comment by randyoles** [comment]
Oh nice.
 It's usually easy once someone explains it. 
Us ex windows users have no clue until then.
It's obvious once you know. :P

**Comment by Schievel1** [comment]
true that, this is just so common for decades now in the Unix world, you sometimes forget to even point it out. I will add a section on the readme.
