### ISSUE TITLE
Missing grub-btrfsd daemon

### ISSUE THREAD

**Issue by Guthauser** [Antynea/grub-btrfs#319]
I've got an running version of grub-btrfs and it works so far. Now i wanted to Automatically update grub upon snapshot creation or deletion. If I want to do so with 

> sudo systemctl start grub-btrfsd

I get following output:

> Failed to start grub-btrfsd.service: Unit grub-btrfsd.service not found.

Did I miss a something to install?

**Comment by Schievel1** [comment]
Probably yes, can you give some more info about how you installed grub-btrfs and what distro you are using? 
Maybe also the content of /usr/lib/systemd/system?

**Comment by Guthauser** [comment]
Im using ParrotOS 6.0 and installed grub-btrfs via command

> sudo apt install grub-btrfs

Didn't do anything other than that configuration/installation wise. (As far as I remember)

Content of /usr/lib/systemd/system:

>  accounts-daemon.service
>  alsa-restore.service
>  alsa-state.service
>  alsa-utils.service
>  anacron.service
>  anacron.timer
>  anonsurfd.service
>  apache2.service
>  apache2@.service
>  apache-htcacheclean.service
>  apache-htcacheclean@.service
>  apparmor.service
>  apt-daily.service
>  apt-daily.timer
>  apt-daily-upgrade.service
>  apt-daily-upgrade.timer
>  arpwatch.service
>  arpwatch@.service
>  autovt@.service
>  avahi-daemon.service
>  avahi-daemon.socket
>  basic.target
>  basic.target.wants
>  bettercap.service
>  binfmt-support.service
>  blk-availability.service
>  blockdev@.target
>  blueman-mechanism.service
>  bluetooth.service
>  bluetooth.target
>  boot-complete.target
>  colord.service
>  configure-printer@.service
>  console-getty.service
>  console-setup.service
>  container-getty@.service
>  cron.service
>  cryptdisks-early.service
>  cryptdisks.service
>  cryptsetup-pre.target
>  cryptsetup.target
>  ctrl-alt-del.target
>  cups-browsed.service
>  cups.path
>  cups.service
>  cups.socket
>  dbus-org.freedesktop.hostname1.service
>  dbus-org.freedesktop.locale1.service
>  dbus-org.freedesktop.login1.service
>  dbus-org.freedesktop.timedate1.service
>  dbus.service
>  dbus.socket
>  debug-shell.service
>  default.target
>  dev-hugepages.mount
>  dev-mqueue.mount
>  dm-event.service
>  dm-event.socket
>  dnsmasq.service
>  dnsmasq@.service
>  dpkg-db-backup.service
>  dpkg-db-backup.timer
>  e2scrub_all.service
>  e2scrub_all.timer
>  e2scrub_fail@.service
>  e2scrub_reap.service
>  e2scrub@.service
>  emergency.service
>  emergency.target
>  exim4-base.service
>  exim4-base.timer
>  exit.target
>  factory-reset.target
>  final.target
>  first-boot-complete.target
>  fprintd.service
>  fstrim.service
>  fstrim.timer
>  geoclue.service
>  getty-pre.target
>  getty@.service
>  getty-static.service
>  getty.target
>  getty.target.wants
>  graphical.target
>  graphical.target.wants
>  grub-btrfs.path
>  grub-btrfs.service
>  halt.target
>  halt.target.wants
>  haveged.service
>  hibernate.target
>  hostapd.service
>  hostapd@.service
>  hv-fcopy-daemon.service
>  hv-kvp-daemon.service
>  hv-vss-daemon.service
>  hwclock.service
>  hybrid-sleep.target
>  ifupdown-pre.service
>  ifupdown-wait-online.service
>  ifup@.service
>  iio-sensor-proxy.service
>  initrd-cleanup.service
>  initrd-fs.target
>  initrd-parse-etc.service
>  initrd-root-device.target
>  initrd-root-device.target.wants
>  initrd-root-fs.target
>  initrd-root-fs.target.wants
>  initrd-switch-root.service
>  initrd-switch-root.target
>  initrd-switch-root.target.wants
>  initrd.target
>  initrd.target.wants
>  initrd-udevadm-cleanup-db.service
>  initrd-usr-fs.target
>  integritysetup-pre.target
>  integritysetup.target
>  iodined.service
>  ipp-usb.service
>  ipsec.service
>  kexec.target
>  kexec.target.wants
>  keyboard-setup.service
>  kmod.service
>  kmod-static-nodes.service
>  ldconfig.service
>  lightdm.service
>  lighttpd.service
>  lm-sensors.service
>  local-fs-pre.target
>  local-fs.target
>  logrotate.service
>  logrotate.timer
>  lvm2-lvmpolld.service
>  lvm2-lvmpolld.socket
>  lvm2-monitor.service
>  lynis.service
>  lynis.timer
>  machine.slice
>  man-db.service
>  man-db.timer
>  mariadb@bootstrap.service.d
>  mariadb.service
>  mariadb@.service
>  mariadb.socket
>  mariadb@.socket
>  mdadm-grow-continue@.service
>  mdadm-last-resort@.service
>  mdadm-last-resort@.timer
>  mdadm.service
>  mdadm-shutdown.service
>  mdadm-waitidle.service
>  mdcheck_continue.service
>  mdcheck_continue.timer
>  mdcheck_start.service
>  mdcheck_start.timer
>  mdmonitor-oneshot.service
>  mdmonitor-oneshot.timer
>  mdmonitor.service
>  mdmon@.service
>  miredo.service
>  ModemManager.service
>  modprobe@.service
>  multi-user.target
>  multi-user.target.wants
>  mysqld.service
>  mysql.service
>  networking.service
>  NetworkManager-dispatcher.service
>  NetworkManager.service
>  NetworkManager-wait-online.service
>  network-online.target
>  network-pre.target
>  network.target
>  nftables.service
>  nginx.service
>  nmbd.service
>  nm-priv-helper.service
>  nss-lookup.target
>  nss-user-lookup.target
>  ntpsec-rotate-stats.service
>  ntpsec-rotate-stats.timer
>  ntpsec.service
>  ntpsec-systemd-netif.path
>  ntpsec-systemd-netif.service
>  ntpsec-wait.service
>  opensnitch.service
>  open-vm-tools.service
>  open-vm-tools.service.d
>  openvpn-client@.service
>  openvpn-server@.service
>  openvpn.service
>  openvpn@.service
>  pam_namespace.service
>  paths.target
>  pcscd.service
>  pcscd.socket
>  pg_basebackup@.service
>  pg_basebackup@.timer
>  pg_compresswal@.service
>  pg_compresswal@.timer
>  pg_dump@.service
>  pg_dump@.timer
>  pg_receivewal@.service
>  phpsessionclean.service
>  phpsessionclean.timer
>  plymouth-halt.service
>  plymouth-kexec.service
>  plymouth-log.service
>  plymouth-poweroff.service
>  plymouth-quit.service
>  plymouth-quit-wait.service
>  plymouth-read-write.service
>  plymouth-reboot.service
>  plymouth.service
>  plymouth-start.service
>  plymouth-switch-root-initramfs.service
>  plymouth-switch-root.service
>  polkit.service
>  postgresql.service
>  postgresql@.service
>  postgresql@.service.d
>  poweroff.target
>  poweroff.target.wants
>  printer.target
>  procps.service
>  proc-sys-fs-binfmt_misc.automount
>  proc-sys-fs-binfmt_misc.mount
>  pulseaudio-enable-autospawn.service
>  qemu-guest-agent.service
>  quotaon.service
>  rc-local.service
>  rc-local.service.d
>  rc.service
>  rcS.service
>  reboot.target
>  reboot.target.wants
>  remote-cryptsetup.target
>  remote-fs-pre.target
>  remote-fs.target
>  remote-veritysetup.target
>  rescue.service
>  rescue-ssh.target
>  rescue.target
>  rescue.target.wants
>  rngd.service
>  rpcbind.target
>  rsync.service
>  rtkit-daemon.service
>  runlevel0.target
>  runlevel1.target
>  runlevel2.target
>  runlevel3.target
>  runlevel4.target
>  runlevel5.target
>  runlevel6.target
> 'run-vmblock\x2dfuse.mount'
>  samba-ad-dc.service
>  saned.service
>  saned@.service
>  saned.socket
>  screen-cleanup.service
>  selinux-autorelabel-mark.service
>  selinux-autorelabel.service
>  selinux-autorelabel.target
>  serial-getty@.service
>  shutdown.target
>  sigpwr.target
>  sleep.target
>  slices.target
>  smartcard.target
>  smartmontools.service
>  smbd.service
>  sockets.target
>  sockets.target.wants
>  soft-reboot.target
>  sound.target
>  sound.target.wants
>  spice-vdagentd.service
>  spice-vdagentd.socket
>  spice-vdagent.service
>  ssh.service
>  ssh.socket
>  sslh.service
>  strongswan-starter.service
>  stunnel@.service
>  stunnel.target
>  sudo.service
>  suspend.target
>  suspend-then-hibernate.target
>  swap.target
>  sys-fs-fuse-connections.mount
>  sysinit.target
>  sysinit.target.wants
>  sys-kernel-config.mount
>  sys-kernel-debug.mount
>  sys-kernel-tracing.mount
>  syslog.socket
>  sysstat-collect.service
>  sysstat-collect.timer
>  sysstat.service
>  sysstat-summary.service
>  sysstat-summary.timer
>  systemd-ask-password-console.path
>  systemd-ask-password-console.service
>  systemd-ask-password-plymouth.path
>  systemd-ask-password-plymouth.service
>  systemd-ask-password-wall.path
>  systemd-ask-password-wall.service
>  systemd-backlight@.service
>  systemd-battery-check.service
>  systemd-binfmt.service
>  systemd-boot-check-no-failures.service
>  systemd-confext.service
>  systemd-exit.service
>  systemd-firstboot.service
>  systemd-fsckd.service
>  systemd-fsckd.socket
>  systemd-fsck-root.service
>  systemd-fsck@.service
>  systemd-growfs-root.service
>  systemd-growfs@.service
>  systemd-halt.service
>  systemd-hibernate.service
>  systemd-hostnamed.service
>  systemd-hwdb-update.service
>  systemd-hybrid-sleep.service
>  systemd-initctl.service
>  systemd-initctl.socket
>  systemd-journal-catalog-update.service
>  systemd-journald-audit.socket
>  systemd-journald-dev-log.socket
>  systemd-journald.service
>  systemd-journald@.service
>  systemd-journald.socket
>  systemd-journald@.socket
>  systemd-journald-varlink@.socket
>  systemd-journal-flush.service
>  systemd-kexec.service
>  systemd-localed.service
>  systemd-localed.service.d
>  systemd-logind.service
>  systemd-machine-id-commit.service
>  systemd-modules-load.service
>  systemd-networkd.service
>  systemd-networkd.socket
>  systemd-networkd-wait-online.service
>  systemd-networkd-wait-online@.service
>  systemd-network-generator.service
>  systemd-pcrfs-root.service
>  systemd-pcrfs@.service
>  systemd-pcrmachine.service
>  systemd-pcrphase-initrd.service
>  systemd-pcrphase.service
>  systemd-pcrphase-sysinit.service
>  systemd-poweroff.service
>  systemd-pstore.service
>  systemd-quotacheck.service
>  systemd-random-seed.service
>  systemd-reboot.service
>  systemd-remount-fs.service
>  systemd-repart.service
>  systemd-rfkill.service
>  systemd-rfkill.socket
>  systemd-soft-reboot.service
>  systemd-suspend.service
>  systemd-suspend-then-hibernate.service
>  systemd-sysctl.service
>  systemd-sysext.service
>  systemd-sysupdate-reboot.service
>  systemd-sysupdate-reboot.timer
>  systemd-sysupdate.service
>  systemd-sysupdate.timer
>  systemd-sysusers.service
>  systemd-timedated.service
>  systemd-time-wait-sync.service
>  systemd-tmpfiles-clean.service
>  systemd-tmpfiles-clean.timer
>  systemd-tmpfiles-setup-dev-early.service
>  systemd-tmpfiles-setup-dev.service
>  systemd-tmpfiles-setup.service
>  systemd-udevd-control.socket
>  systemd-udevd-kernel.socket
>  systemd-udevd.service
>  systemd-udevd.service.d
>  systemd-udev-settle.service
>  systemd-udev-trigger.service
>  systemd-update-done.service
>  systemd-update-utmp-runlevel.service
>  systemd-update-utmp.service
>  systemd-user-sessions.service
>  systemd-volatile-root.service
> 'system-systemd\x2dcryptsetup.slice'
> 'system-systemd\x2dveritysetup.slice'
>  system-update-cleanup.service
>  system-update-pre.target
>  system-update.target
>  timers.target
>  timers.target.wants
>  time-set.target
>  time-sync.target
>  tor@default.service
>  tor.service
>  tor@.service
>  udev.service
>  udisks2.service
>  ufw.service
>  umount.target
>  upower.service
>  usb-gadget.target
>  usb_modeswitch@.service
>  usbmuxd.service
>  user@0.service.d
>  user-runtime-dir@.service
>  user@.service
>  user@.service.d
>  user.slice
>  user-.slice.d
>  uuidd.service
>  uuidd.socket
>  veritysetup-pre.target
>  veritysetup.target
>  vgauth.service
>  virtualbox-guest-utils.service
>  vpnc@.service
>  wacom-inputattach@.service
>  wpa_supplicant-nl80211@.service
>  wpa_supplicant.service
>  wpa_supplicant@.service
>  wpa_supplicant-wired@.service
>  x11-common.service
>  xplico.service



Also I can't recover snapshots listed in grub. I'll open another issue for that, but thought it's worth mentioning here because its maybe related?

**Comment by Schievel1** [comment]
It seems like parrot OS is having an older version of grub-btrfs in their repository. 
This looks like 4.11, although I am not sure. So maybe refer to the README of this version on how to activate the service (https://github.com/Antynea/grub-btrfs/tree/79ae25ea5d35a9252ab399aee569d70c3a9f1ee2) or upgrade.
