### ISSUE TITLE
initramfs-* not found

### ISSUE THREAD

**Issue by akha666** [Antynea/grub-btrfs#32]
Currently, I've deployed with Ubuntu 17.10.
After reboot to from "Ubuntu Snapshot" I've got this error
```
Loading Snapshot: 2017-11-22 14:00:14 ~/.snapshots/2/snapshot
Loading Kernel: vmlinuz-4.13.0-16-generic ...
Loading Initfamfs: initramfs-* ...
error: file '/@/.snapshots/2/snapshot/boot/initramfs-*' not found.

Press any key to continue ...
```
Any help ??

**Comment by Antynea** [comment]
for all delian like distribution
please put in the file `/etc/default/grub`
`GRUB_BTRFS_CREATE_ONLY_HARMONIZED_ENTRIES="true"`
then re-generate your grub-menu (`update-grub2` in ubuntu 17.10)

**Comment by akha666** [comment]
Thank you, now I can boot with any snapshot number.
I have another issue can I post here or open a new one?

**Comment by Antynea** [comment]
Close this one and open a new
