### ISSUE TITLE
systemd-boot support

### ISSUE THREAD

**Issue by kalos** [Antynea/grub-btrfs#322]
Hi, congratulations for the project!

Have you ever considered supporting systemd-boot?
I understand the project is called **GRUB**-btrfs, but they may share some of the codebase

**Comment by Schievel1** [comment]
Not really. I never used it and I don't even know if it has some menu functionality like grub does. 
The Script in grub-btrfs generates a grub menu directly from a snapshot list that comes from btrfs-utils. 
I don't think that codebase can be used for systemd-boot unless it is using the same syntax for its menues. (which I doubt)
