### ISSUE TITLE
Subvolume.IO Error

### ISSUE THREAD

**Issue by akha666** [Antynea/grub-btrfs#33]
Hello,
I've configured grub-btrfs to boot my snapshot, but when I execute :
`# snapper rollback`
I've got this error
`Creating read-only snapshot of default subvolume.IO Error (.snapshots is not a btrfs subvolume).`
Also, I'm working with Kubuntu 17.10 and Plasma Desktop not loaded when booting any snapshots, only boot to text mode.
I'll appreciate if help me to fix this.
Thanks

**Comment by Antynea** [comment]
it's not a bug of my script
get closer to the snapper community
closed.
