### ISSUE TITLE
Feature Request: Support NO microcode option in config.

### ISSUE THREAD

**Issue by bkmo** [Antynea/grub-btrfs#335]
Arch now defaults to adding the microcode to iniramfs with mkinitcpio. Can we have a config option for grub-btrfs to not add it via grub? Thanks

**Comment by cinnamonmatexfce** [comment]
Add these onto your `etc/default/grub`:

```
GRUB_EARLY_INITRD_LINUX_CUSTOM=""
GRUB_EARLY_INITRD_LINUX_STOCK=""
```

**Comment by bkmo** [comment]
Please explain why you think this will disable grub-btrfs from adding the microcode to initrd? It may keep Grub from adding it, but then grub-btrfs will add it anyway to grub-btrfs.cfg. I am going to close this request as I have added a config option to my own fork.
