### ISSUE TITLE
Use snapper's snapshot description if available

### ISSUE THREAD

**Issue by maximbaz** [Antynea/grub-btrfs#34]
This is one specific request for much nicer support of snapper's snapshots, originally mentioned in #23:

Make the script run `snapper list`, and use the description column for the snapshot in the GRUB menu instead of the current one. The script should not require any configuration (contrary to #28), just run `snapper list` and fallback to the current implementation if the command returned with a non-zero exit code or didn't produce a table of entries to parse. If only some of the discovered snapshots are not mentioned in the output of `snapper list`, again fallback and name those snapshots with the current naming scheme.

PR #28 should be closed because #23 is an invalid issue, but some bits and pieces of the PR can be reused to implement this feature.

I can make a PR, @Antynea are you still around to review and merge?

**Comment by Antynea** [comment]
hi,
i've closed PR #28 
you can make your own.
Thanks for your time.
