### ISSUE TITLE
Systematic failure in generating the GRUB configuration file

### ISSUE THREAD

**Issue by marco-palmiotto** [Antynea/grub-btrfs#346]
Hi all, each time I update with pacman, I have the following error. Sorry for the length, but I think it's better to show it completely. Moreover, if I manually run `grub-mkconfig -o /boot/grub/grub.cfg` after pacman finishes, the menu is correctly created. Otherwise I will find the menu without the timeshift snapshots. Here's the output:

    
    :: Running pre-transaction hooks...
    (1/1) Creating Timeshift snapshot before upgrade...
    Using system disk as snapshot device for creating snapshots in BTRFS mode
    Mounted '/dev/dm-0 (nvme0n1p4)' at '/run/timeshift/3363/backup'
    btrfs: Quotas are not enabled
    Creating new backup...(BTRFS)
    Saving to device: /dev/dm-0, mounted at path: /run/timeshift/3363/backup
    Created directory: /run/timeshift/3363/backup/timeshift-btrfs/snapshots/2024-08-11_18-21-33
    Created subvolume snapshot: /run/timeshift/3363/backup/timeshift-btrfs/snapshots/2024-08-11_18-21-33/@
    Created control file: /run/timeshift/3363/backup/timeshift-btrfs/snapshots/2024-08-11_18-21-33/info.json
    BTRFS Snapshot saved successfully (0s)
    Tagged snapshot '2024-08-11_18-21-33': ondemand
    ------------------------------------------------------------------------------
    Mounted '/dev/dm-0 (nvme0n1p4)' at '/run/timeshift/3742/backup'
    btrfs: Quotas are not enabled
    ------------------------------------------------------------------------------
    Removing snapshot: 2024-08-09_20-56-20
    Deleting subvolume: @ (Id:385)
    Deleted subvolume: @ (Id:385)
    
    Deleted directory: /run/timeshift/3742/backup/timeshift-btrfs/snapshots/2024-08-09_20-56-20
    Removed snapshot: 2024-08-09_20-56-20
    ------------------------------------------------------------------------------
    Generating grub configuration file ...
    Found linux image: /boot/vmlinuz-linux-lts
    Found initrd image: /boot/initramfs-linux-lts.img
    Found fallback initrd image(s) in /boot:  initramfs-linux-lts-fallback.img
    Found linux image: /boot/vmlinuz-linux
    Found initrd image: /boot/initramfs-linux.img
    Found fallback initrd image(s) in /boot:  initramfs-linux-fallback.img
    Warning: os-prober will be executed to detect other bootable partitions.
    Its output will be used to detect bootable binaries on them and create new boot entries.
    find: ‘/var/lib/os-prober/mount/efi’: No such file or directory
    Adding boot menu entry for UEFI Firmware Settings ...
    Detecting snapshots ...
    Found snapshot: 2024-08-11 18:21:33 | timeshift-btrfs/snapshots/2024-08-11_18-21-33/@ | ondemand | {timeshift-autosnap} {created before upgrade}         |
    Found snapshot: 2024-08-10 15:24:51 | timeshift-btrfs/snapshots/2024-08-10_15-24-51/@ | ondemand | {timeshift-autosnap} {created before upgrade}         |
    Found snapshot: 2024-08-09 21:04:02 | timeshift-btrfs/snapshots/2024-08-09_21-04-02/@ | ondemand | {timeshift-autosnap} 
    [all the others...]
    Found 26 snapshot(s)
    error: syntax error.
    error: Incorrect command.
    error: syntax error.
    Syntax error at line 658
    Syntax errors were detected in generated /boot/grub/grub-btrfs.new file. The old grub-btrfs.cfg file (if present) have been restored.
    If you think an error has occurred, please file a bug report at "https://github.com/Antynea/grub-btrfs"
    Unmount /tmp/grub-btrfs.cA39MT5Xho .. Success
    cannot open `/boot/grub/grub.cfg.new': No such file or directoryUsage: /usr/bin/grub-script-check [OPTION...] [PATH]
    Try '/usr/bin/grub-script-check --help' or '/usr/bin/grub-script-check
    --usage' for more information.
    Syntax errors are detected in generated GRUB config file.
    Ensure that there are no errors in /etc/default/grub
    and /etc/grub.d/* files or please file a bug report with
    /boot/grub/grub.cfg.new file attached.

I also attach the ` /boot/grub/grub-btrfs.new ` file here:

      menuentry '|         Date        |                     Snapshot                    |   Type   |                      Description                      |' { echo }
      menuentry '|         Date        |                     Snapshot                    |   Type   |                      Description                      |' { echo }
      submenu '| 2024-08-11 18:21:33 | timeshift-btrfs/snapshots/2024-08-11_18-21-33/@ | ondemand | {timeshift-autosnap} {created before upgrade}         |' {
          submenu '| 2024-08-11 18:21:33 | timeshift-btrfs/snapshots/2024-08-11_18-21-33/@ | ondemand | {timeshift-autosnap} {created before upgrade} |' { echo }
      
          menuentry '  vmlinuz-linux & initramfs-linux-fallback.img' --class snapshots --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-snapshots-08C6-F075' {
              if [ x$feature_all_video_module = xy ]; then
              insmod all_video
              fi
              set gfxpayload=keep
              insmod fat
              if [ x$feature_platform_search_hint = xy ]; then
                  search --no-floppy --fs-uuid  --set=root  08C6-F075
              else
                  search --no-floppy --fs-uuid  --set=root 08C6-F075
              fi
              echo 'Loading Snapshot: 2024-08-11 18:21:33 timeshift-btrfs/snapshots/2024-08-11_18-21-33/@'
              echo 'Loading Kernel: vmlinuz-linux ...'
              linux "/vmlinuz-linux" root=UUID=0e76070f-d589-4401-9cac-4ee609541f99  loglevel=3 quiet cryptdevice=UUID=4b5f42aa-44bf-4bef-acd7-b0230ac001a0:linuxroot root=/dev/mapper/linuxroot rootflags=subvol=@ nvidia_drm.modeset=1 NVreg_EnableGpuFirmware=0 NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp NVreg_DynamicPowerManagement=0x02  rootflags=rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol="timeshift-btrfs/snapshots/2024-08-11_18-21-33/@"
              echo 'Loading Initramfs: initramfs-linux-fallback.img ...'
              initrd "/initramfs-linux-fallback.img"
          }
      
          menuentry '  vmlinuz-linux & initramfs-linux.img' --class snapshots --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-snapshots-08C6-F075' {
              if [ x$feature_all_video_module = xy ]; then
              insmod all_video
              fi
              set gfxpayload=keep
              insmod fat
              if [ x$feature_platform_search_hint = xy ]; then
                  search --no-floppy --fs-uuid  --set=root  08C6-F075
              else
                  search --no-floppy --fs-uuid  --set=root 08C6-F075
              fi
              echo 'Loading Snapshot: 2024-08-11 18:21:33 timeshift-btrfs/snapshots/2024-08-11_18-21-33/@'
              echo 'Loading Kernel: vmlinuz-linux ...'
              linux "/vmlinuz-linux" root=UUID=0e76070f-d589-4401-9cac-4ee609541f99  loglevel=3 quiet cryptdevice=UUID=4b5f42aa-44bf-4bef-acd7-b0230ac001a0:linuxroot root=/dev/mapper/linuxroot rootflags=subvol=@ nvidia_drm.modeset=1 NVreg_EnableGpuFirmware=0 NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp NVreg_DynamicPowerManagement=0x02  rootflags=rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol="timeshift-btrfs/snapshots/2024-08-11_18-21-33/@"
              echo 'Loading Initramfs: initramfs-linux.img ...'
              initrd "/initramfs-linux.img"
          }
      
          menuentry '  vmlinuz-linux-lts & initramfs-linux-lts-fallback.img' --class snapshots --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-snapshots-08C6-F075' {
              if [ x$feature_all_video_module = xy ]; then
              insmod all_video
              fi
              set gfxpayload=keep
              insmod fat
              if [ x$feature_platform_search_hint = xy ]; then
                  search --no-floppy --fs-uuid  --set=root  08C6-F075
              else
                  search --no-floppy --fs-uuid  --set=root 08C6-F075
              fi
              echo 'Loading Snapshot: 2024-08-11 18:21:33 timeshift-btrfs/snapshots/2024-08-11_18-21-33/@'
              echo 'Loading Kernel: vmlinuz-linux-lts ...'
              linux "/vmlinuz-linux-lts" root=UUID=0e76070f-d589-4401-9cac-4ee609541f99  loglevel=3 quiet cryptdevice=UUID=4b5f42aa-44bf-4bef-acd7-b0230ac001a0:linuxroot root=/dev/mapper/linuxroot rootflags=subvol=@ nvidia_drm.modeset=1 NVreg_EnableGpuFirmware=0 NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp NVreg_DynamicPowerManagement=0x02  rootflags=rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol="timeshift-btrfs/snapshots/2024-08-11_18-21-33/@"
              echo 'Loading Initramfs: initramfs-linux-lts-fallback.img ...'
              initrd "/initramfs-linux-lts-fallback.img"
          }
      
          menuentry '  vmlinuz-linux-lts & initramfs-linux-lts.img' --class snapshots --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-snapshots-08C6-F075' {
              if [ x$feature_all_video_module = xy ]; then
              insmod all_video
              fi
              set gfxpayload=keep
              insmod fat
              if [ x$feature_platform_search_hint = xy ]; then
                  search --no-floppy --fs-uuid  --set=root  08C6-F075
              else
                  search --no-floppy --fs-uuid  --set=root 08C6-F075
              fi
              echo 'Loading Snapshot: 2024-08-11 18:21:33 timeshift-btrfs/snapshots/2024-08-11_18-21-33/@'
              echo 'Loading Kernel: vmlinuz-linux-lts ...'
              linux "/vmlinuz-linux-lts" root=UUID=0e76070f-d589-4401-9cac-4ee609541f99  loglevel=3 quiet cryptdevice=UUID=4b5f42aa-44bf-4bef-acd7-b0230ac001a0:linuxroot root=/dev/mapper/linuxroot rootflags=subvol=@ nvidia_drm.modeset=1 NVreg_EnableGpuFirmware=0 NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp NVreg_DynamicPowerManagement=0x02  rootflags=rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol="timeshift-btrfs/snapshots/2024-08-11_18-21-33/@"
              echo 'Loading Initramfs: initramfs-linux-lts.img ...'
              initrd "/initramfs-linux-lts.img"
          }
      }
      submenu '| 2024-08-10 15:24:51 | timeshift-btrfs/snapshots/2024-08-10_15-24-51/@ | ondemand | {timeshift-autosnap} {created before upgrade}         |' {
          submenu '| 2024-08-10 15:24:51 | timeshift-btrfs/snapshots/2024-08-10_15-24-51/@ | ondemand | {timeshift-autosnap} {created before upgrade} |' { echo }
      
          menuentry '  vmlinuz-linux & initramfs-linux-fallback.img' --class snapshots --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-snapshots-08C6-F075' {
              if [ x$feature_all_video_module = xy ]; then
              insmod all_video
              fi
              set gfxpayload=keep
              insmod fat
              if [ x$feature_platform_search_hint = xy ]; then
                  search --no-floppy --fs-uuid  --set=root  08C6-F075
              else
                  search --no-floppy --fs-uuid  --set=root 08C6-F075
              fi
              echo 'Loading Snapshot: 2024-08-10 15:24:51 timeshift-btrfs/snapshots/2024-08-10_15-24-51/@'
              echo 'Loading Kernel: vmlinuz-linux ...'
              linux "/vmlinuz-linux" root=UUID=0e76070f-d589-4401-9cac-4ee609541f99  loglevel=3 quiet cryptdevice=UUID=4b5f42aa-44bf-4bef-acd7-b0230ac001a0:linuxroot root=/dev/mapper/linuxroot rootflags=subvol=@ nvidia_drm.modeset=1 NVreg_EnableGpuFirmware=0 NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp NVreg_DynamicPowerManagement=0x02  rootflags=rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol="timeshift-btrfs/snapshots/2024-08-10_15-24-51/@"
              echo 'Loading Initramfs: initramfs-linux-fallback.img ...'
              initrd "/initramfs-linux-fallback.img"
          }
      
          menuentry '  vmlinuz-linux & initramfs-linux.img' --class snapshots --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-snapshots-08C6-F075' {
              if [ x$feature_all_video_module = xy ]; then
              insmod all_video
              fi
              set gfxpayload=keep
              insmod fat
              if [ x$feature_platform_search_hint = xy ]; then
                  search --no-floppy --fs-uuid  --set=root  08C6-F075
              else
                  search --no-floppy --fs-uuid  --set=root 08C6-F075
              fi
              echo 'Loading Snapshot: 2024-08-10 15:24:51 timeshift-btrfs/snapshots/2024-08-10_15-24-51/@'
              echo 'Loading Kernel: vmlinuz-linux ...'
              linux "/vmlinuz-linux" root=UUID=0e76070f-d589-4401-9cac-4ee609541f99  loglevel=3 quiet cryptdevice=UUID=4b5f42aa-44bf-4bef-acd7-b0230ac001a0:linuxroot root=/dev/mapper/linuxroot rootflags=subvol=@ nvidia_drm.modeset=1 NVreg_EnableGpuFirmware=0 NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp NVreg_DynamicPowerManagement=0x02  rootflags=rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol="timeshift-btrfs/snapshots/2024-08-10_15-24-51/@"
              echo 'Loading Initramfs: initramfs-linux.img ...'
              initrd "/initramfs-linux.img"
          }
      
          menuentry '  vmlinuz-linux-lts & initramfs-linux-lts-fallback.img' --class snapshots --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-snapshots-08C6-F075' {
              if [ x$feature_all_video_module = xy ]; then
              insmod all_video
              fi
              set gfxpayload=keep
              insmod fat
              if [ x$feature_platform_search_hint = xy ]; then
                  search --no-floppy --fs-uuid  --set=root  08C6-F075
              else
                  search --no-floppy --fs-uuid  --set=root 08C6-F075
              fi
              echo 'Loading Snapshot: 2024-08-10 15:24:51 timeshift-btrfs/snapshots/2024-08-10_15-24-51/@'
              echo 'Loading Kernel: vmlinuz-linux-lts ...'
              linux "/vmlinuz-linux-lts" root=UUID=0e76070f-d589-4401-9cac-4ee609541f99  loglevel=3 quiet cryptdevice=UUID=4b5f42aa-44bf-4bef-acd7-b0230ac001a0:linuxroot root=/dev/mapper/linuxroot rootflags=subvol=@ nvidia_drm.modeset=1 NVreg_EnableGpuFirmware=0 NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp NVreg_DynamicPowerManagement=0x02  rootflags=rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol="timeshift-btrfs/snapshots/2024-08-10_15-24-51/@"
              echo 'Loading Initramfs: initramfs-linux-lts-fallback.img ...'
              initrd "/initramfs-linux-lts-fallback.img"
          }
      
          menuentry '  vmlinuz-linux-lts & initramfs-linux-lts.img' --class snapshots --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-snapshots-08C6-F075' {
              if [ x$feature_all_video_module = xy ]; then
              insmod all_video
              fi
              set gfxpayload=keep
              insmod fat
              if [ x$feature_platform_search_hint = xy ]; then
                  search --no-floppy --fs-uuid  --set=root  08C6-F075
              else
                  search --no-floppy --fs-uuid  --set=root 08C6-F075
              fi
              echo 'Loading Snapshot: 2024-08-10 15:24:51 timeshift-btrfs/snapshots/2024-08-10_15-24-51/@'
              echo 'Loading Kernel: vmlinuz-linux-lts ...'
              linux "/vmlinuz-linux-lts" root=UUID=0e76070f-d589-4401-9cac-4ee609541f99  loglevel=3 quiet cryptdevice=UUID=4b5f42aa-44bf-4bef-acd7-b0230ac001a0:linuxroot root=/dev/mapper/linuxroot rootflags=subvol=@ nvidia_drm.modeset=1 NVreg_EnableGpuFirmware=0 NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp NVreg_DynamicPowerManagement=0x02  rootflags=rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol="timeshift-btrfs/snapshots/2024-08-10_15-24-51/@"
              echo 'Loading Initramfs: initramfs-linux-lts.img ...'
              initrd "/initramfs-linux-lts.img"
          }
      }
      submenu '| 2024-08-09 21:04:02 | timeshift-btrfs/snapshots/2024-08-09_21-04-02/@ | ondemand | {timeshift-autosnap} {created before upgrade}         |' {
          submenu '| 2024-08-09 21:04:02 | timeshift-btrfs/snapshots/2024-08-09_21-04-02/@ | ondemand | {timeshift-autosnap} {created before upgrade} |' { echo }
      
          menuentry '  vmlinuz-linux & initramfs-linux-fallback.img' --class snapshots --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-snapshots-08C6-F075' {
              if [ x$feature_all_video_module = xy ]; then
              insmod all_video
              fi
              set gfxpayload=keep
              insmod fat
              if [ x$feature_platform_search_hint = xy ]; then
                  search --no-floppy --fs-uuid  --set=root  08C6-F075
              else
                  search --no-floppy --fs-uuid  --set=root 08C6-F075
              fi
              echo 'Loading Snapshot: 2024-08-09 21:04:02 timeshift-btrfs/snapshots/2024-08-09_21-04-02/@'
              echo 'Loading Kernel: vmlinuz-linux ...'
              linux "/vmlinuz-linux" root=UUID=0e76070f-d589-4401-9cac-4ee609541f99  loglevel=3 quiet cryptdevice=UUID=4b5f42aa-44bf-4bef-acd7-b0230ac001a0:linuxroot root=/dev/mapper/linuxroot rootflags=subvol=@ nvidia_drm.modeset=1 NVreg_EnableGpuFirmware=0 NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp NVreg_DynamicPowerManagement=0x02  rootflags=rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol="timeshift-btrfs/snapshots/2024-08-09_21-04-02/@"
              echo 'Loading Initramfs: initramfs-linux-fallback.img ...'
              initrd "/initramfs-linux-fallback.img"
          }
      
          menuentry '  vmlinuz-linux & initramfs-linux.img' --class snapshots --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-snapshots-08C6-F075' {
              if [ x$feature_all_video_module = xy ]; then
              insmod all_video
              fi
              set gfxpayload=keep
              insmod fat
              if [ x$feature_platform_search_hint = xy ]; then
                  search --no-floppy --fs-uuid  --set=root  08C6-F075
              else
                  search --no-floppy --fs-uuid  --set=root 08C6-F075
              fi
              echo 'Loading Snapshot: 2024-08-09 21:04:02 timeshift-btrfs/snapshots/2024-08-09_21-04-02/@'
              echo 'Loading Kernel: vmlinuz-linux ...'
              linux "/vmlinuz-linux" root=UUID=0e76070f-d589-4401-9cac-4ee609541f99  loglevel=3 quiet cryptdevice=UUID=4b5f42aa-44bf-4bef-acd7-b0230ac001a0:linuxroot root=/dev/mapper/linuxroot rootflags=subvol=@ nvidia_drm.modeset=1 NVreg_EnableGpuFirmware=0 NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp NVreg_DynamicPowerManagement=0x02  rootflags=rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol="timeshift-btrfs/snapshots/2024-08-09_21-04-02/@"
              echo 'Loading Initramfs: initramfs-linux.img ...'
              initrd "/initramfs-linux.img"
          }
      
          menuentry '  vmlinuz-linux-lts & initramfs-linux-lts-fallback.img' --class snapshots --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-snapshots-08C6-F075' {
              if [ x$feature_all_video_module = xy ]; then
              insmod all_video
              fi
              set gfxpayload=keep
              insmod fat
              if [ x$feature_platform_search_hint = xy ]; then
                  search --no-floppy --fs-uuid  --set=root  08C6-F075
              else
                  search --no-floppy --fs-uuid  --set=root 08C6-F075
              fi
              echo 'Loading Snapshot: 2024-08-09 21:04:02 timeshift-btrfs/snapshots/2024-08-09_21-04-02/@'
              echo 'Loading Kernel: vmlinuz-linux-lts ...'
              linux "/vmlinuz-linux-lts" root=UUID=0e76070f-d589-4401-9cac-4ee609541f99  loglevel=3 quiet cryptdevice=UUID=4b5f42aa-44bf-4bef-acd7-b0230ac001a0:linuxroot root=/dev/mapper/linuxroot rootflags=subvol=@ nvidia_drm.modeset=1 NVreg_EnableGpuFirmware=0 NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp NVreg_DynamicPowerManagement=0x02  rootflags=rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol="timeshift-btrfs/snapshots/2024-08-09_21-04-02/@"
              echo 'Loading Initramfs: initramfs-linux-lts-fallback.img ...'
              initrd "/initramfs-linux-lts-fallback.img"
          }
      
          menuentry '  vmlinuz-linux-lts & initramfs-linux-lts.img' --class snapshots --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-snapshots-08C6-F075' {
              if [ x$feature_all_video_module = xy ]; then
              insmod all_video
              fi
              set gfxpayload=keep
              insmod fat
              if [ x$feature_platform_search_hint = xy ]; then
                  search --no-floppy --fs-uuid  --set=root  08C6-F075
              else
                  search --no-floppy --fs-uuid  --set=root 08C6-F075
              fi
              echo 'Loading Snapshot: 2024-08-09 21:04:02 timeshift-btrfs/snapshots/2024-08-09_21-04-02/@'
              echo 'Loading Kernel: vmlinuz-linux-lts ...'
              linux "/vmlinuz-linux-lts" root=UUID=0e76070f-d589-4401-9cac-4ee609541f99  loglevel=3 quiet cryptdevice=UUID=4b5f42aa-44bf-4bef-acd7-b0230ac001a0:linuxroot root=/dev/mapper/linuxroot rootflags=subvol=@ nvidia_drm.modeset=1 NVreg_EnableGpuFirmware=0 NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp NVreg_DynamicPowerManagement=0x02  rootflags=rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvol="timeshift-btrfs/snapshots/2024-08-09_21-04-02/@"
              echo 'Loading Initramfs: initramfs-linux-lts.img ...'
              initrd "/initramfs-linux-lts.img"
          }
      }
    ...

**Comment by bkmo** [comment]
Do you also have the grub-btrfsd.service enabled with timeshift-autosnap?  If this is the case then this has been fixed

**Comment by marco-palmiotto** [comment]
Hi! Thanks for the reply! Yes, it is enabled: so, I will try by installing via the AUR package that compiles from git and see what happens.

**Comment by bkmo** [comment]
That should pick up the commit that fixes the issue. It eliminates the conflict with both timeshift-autosnap and grub-btrfsd.service running grub-mkconfig at the same instant.

**Comment by marco-palmiotto** [comment]
Yes! it works :) Thanks a lot!
