### ISSUE TITLE
Unable to install on Fedora 40

### ISSUE THREAD

**Issue by amethystgosling163** [Antynea/grub-btrfs#352]
Install is using default automatic partitioning.

Downloaded the latest release. cd'd into it and ran `sudo make install`

Gave ** this error**:
`/etc/grub.d/41_snapshots-btrfs: line 589: /boot/grub/grub-btrfs.new: No such file or directory
make: *** [Makefile:56: install] Error 1
`

How do I fix it?

**Comment by Skilly146** [comment]
This error is because you didn't uncomment the lines in the config file specified in the readme. On fedora systems you have to uncomment lines 103 and 141 since fedora has grub2 in the command and folder names instead of grub
