### ISSUE TITLE
Snapper id too long

### ISSUE THREAD

**Issue by re1** [Antynea/grub-btrfs#36]
Sadly I could not find more information on how and why the error occurs but while creating the grub config with `grub-mkconfig -o /boot/grub/grub.cfg`, `/etc/grub.d/41_snapshots-btrfs` tells me that on lines `296` and `309`, `0882080592106262008919021151341962250` is `too large for the current base` and blames char `\"0882080592106262008919021151341962250\"`.

**Mentioned lines actually contain the same code:**
``` sh
296: if [[ "$snapper_id" -eq "$id" ]]; then
```
``` sh
309: if [[ "$snapper_id" -eq "$id" ]]; then
```

### System
```
OS: Arch Linux
Kernel: x86_64 Linux 4.14.10-1-ARCH
CPU: Intel Core i7-3630QM @ 8x 3.4GHz
Grub: grub-2:2.02-4
Snapper: snapper-0.5.0-3
Snap-Pac: snap-pac-1.1-1
```

**Comment by Antynea** [comment]
i can reproduce this bug
stupid bash who interpret the number as octal.
it's not a fatal mistake, so you can ignore it for the moment
I'll fix this mistake soon

**Comment by Antynea** [comment]
please, test this patch, and let me now

**Comment by re1** [comment]
Thanks a lot :+1: You are fast :wink:
