### ISSUE TITLE
Syntax error when snapshot description contains '

### ISSUE THREAD

**Issue by Nierenstein23** [Antynea/grub-btrfs#39]
The title basically. The '-character is not escaped in the submenu entry, resulting in a syntax error.

**Comment by maximbaz** [comment]
I cannot reproduce this:

![image](https://user-images.githubusercontent.com/1177900/38173954-f4d62b56-35c5-11e8-9175-4490db13ed64.png)

**Comment by Nierenstein23** [comment]
Sorry, seems to have been a (now fixed) problem with snapper itself, since I can no longer reproduce it with new snapshots, but had to change descriptions of very old ones. My apologies for not checking more thoroughly.
