### ISSUE TITLE
grub-btrfs by default can create astounding number of menu entries, making system unbootable

### ISSUE THREAD

**Issue by billwanjohi** [Antynea/grub-btrfs#42]
I have version 1.11-2 of grub-btrfs which I installed from an [archlinux user repository PKGBUILD](https://aur.archlinux.org/packages/grub-btrfs/) on my Manjaro linux installation on an EFI laptop. I left everything as-is, with the default 100 snapshot limit.

In the meantime, I installed a few kernels and used my system as I pleased. Today I had to reboot after a considerable uptime in which snapper had been dutifully storing lots of snapshots, and I ended up with a system that would not boot, or at least into GRUB. What I found after thrashing aimlessly for a couple of hours was that my `grub.cfg` had grown to over **22000 lines**, almost entirely as a result of these snapshot entries.

At first I thought that there was no limit being applied at all, but I now realize that I did have exactly 100 "Snapshot" submenus in the bloated file. There are big problems, though:

### grub-btrfs does not limit the number of raw menu entries it will create, which is what will ultimately kill your bootloader

While the number of snapshots under consideration is certainly _correlated_ to the resultant number of entries, the latter is what makes the boot menu unwieldly, and ultimately inoperable. 

### grub-btrfs is very greedy in its generation of menu entries

My distribution (manjaro) has a bash script at `/etc/grub.d/10_linux` which dictates the logic to create  menu entries from every valid pair of `initramfs-*` and `vmlinu[z|x]` files it finds in `/boot`. grub-btrfs by contrast just makes entries for every product of the two filetypes, whether or not they make sense.

My machine currently has two vmlinuz kernel files, one each for 4.14 and 4.15. It also has initramfs files for both of those, with fallback variants, and (for reasons I have yet to determine) a couple of leftover initramfs files for a kernel that I had removed. These files result in **1** default and **4** "advanced" entries in the 10_linux section, but _**12** per snapshot_ (=1200 total) in the `41_snapshots-btrfs` section, because grub-btrfs mashes, e.g., initramfs-4.14-rt-x86_64.img and vmlinuz-4.15-x86_64 together, even though that doesn't make sense. It's honestly questionable whether we need anything more than just the latest available kernel-ramdisk pair for these snapshot entries, but certainly very few people are could have any purpose for options to boot kernel version X with ramdisk version Y.

------

To close, I'd like to thank you for your contributions, but to also emphasize the seriousness of this kind of failure state. Inability to launch the bootloader is a really difficult problem for anyone without serious GRUB chops to diagnose; there was no interface, no output, and no logging. This way leads desperation.

Preventing the de facto corruption of `grub.cfg` should be priority number 1, over and above the functionality that you're trying to deliver here (which is very appreciated!).

Thanks for reading.

**Comment by maximbaz** [comment]
Hello, thanks for reporting a well described issue! I agree that we should strive for keeping grub in working state.

I'm trying to see what actions can we do to solve the problem you described. 

I agree that it probably doesn't make sense mixing different kernel and ramdisk versions. So in your example, we would decrease from 12 advanced entries down to 4.

However, I cannot find any documented limits for grub, do you know of something that says "there cannot be more than X lines in `grub.cfg`" or "there cannot be more than Y entries in total"?

Because of that, I'm not sure what we can actually do, besides not mixing kernel and ramdisk versions.

**Comment by Antynea** [comment]
Hello,
thank you for your detailed story.

What initially was a simple personal script made available to the community, has become over time a tool appreciated by many people.

I agree that we should work to keep usable grub.

This limitation, 100 entries, was a little protection to avoid what you experienced.
Obviously that wasn't enough, and we should work on that.
I didn't find anything that indicates a limitation on `grub.cfg` file size. 
(22000 lines, ~ 20MB?)
we should ask on the GRUB mailing list.

by default, the script mixes different kernels and initramfs, which isn't ideal, according to the feedback of several users.
We should fix that.
"GRUB_BTRFS_CREATE_ONLY_HARMONIZED_ENTRIES" option, already deals with this but is not enabled by default.

**Comment by maximbaz** [comment]
Can we just enable it by default then? 😉

**Comment by Antynea** [comment]
@anyc worked on this option. (cf: #22 )
I think it should work as expected
If ok we should enable it by default.

**Comment by billwanjohi** [comment]
Oh wow, that option is very good, yes and as hoped it drastically cuts the number of entries being populated. As far as what length of configuration works and does not, I have only my one laptop to report:

Bytes | Lines | Entries | Result
------------ | ------------- | -- | --
1546819 | 22299 | 1204 | :-1:
917596 | 13279 | 712 | :-1:
318595 | 4699 | 244 | :+1:
11294 | 294 | 4 | :+1:

Turning HARMONIZED_ENTRIES on by default would be fantastic. Reducing the default snapshot limit might be appropriate. Having an option like `GRUB_BTRFS_LIMIT_TOTAL_ENTRIES` with a default of ~250 would also help.

**Comment by Antynea** [comment]
Thanks for your feedback.

Now this option will be enabled by default :)

`GRUB_BTRFS_LIMIT="100"`
(Limit the number of snapshots populated in the GRUB menu.)

by default, this option limits the number of snapshots present in the GRUB menu to "100".
100 snaps with 4 entries for boot differents kernel and initramfs = 400 entries.

This limit seems too high, maybe we should reduce it, right? Maybe reduce to 50 ....

**Comment by maximbaz** [comment]
How about `50` for a new default number of snapshots? A random fact, `50` is the default number of snapshots that snapper keeps.

I have a hard time imagining how `GRUB_BTRFS_LIMIT_TOTAL_ENTRIES` would be implemented - should it abruptly stop generating "advanced" for a snapshot and just exit? 

I'd like to propose a different approach, the script could count the total number of entries it generated, and if this number is way too big (e.g. bigger than 250, doesn't even have to be configurable), print a warning in the end, something like "Generated 712 total GRUB entries. You might experience issues loading GRUB. Consider defining `GRUB_BTRFS_LIMIT` with a smaller value, or removing unnecessary kernels".

**Comment by billwanjohi** [comment]
> print a warning in the end

FWIW, warnings would not have saved me, as snapper and pacman routinely call `grub-mkconfig` on their own and automatically write the results.

**Comment by maximbaz** [comment]
They are not swallowing the output though, you can still see the output made by `grub-btrfs` 😉

**Comment by billwanjohi** [comment]
That's true if I don't use a GUI to install/upgrade kernels, or the snapper-timeline systemd unit, to name a couple of contexts where this is silently applied.

**Comment by maximbaz** [comment]
#43 is part one, everything except the counting with the warning.

**Comment by maximbaz** [comment]
For visibility, reposting https://github.com/Antynea/grub-btrfs/pull/43#issuecomment-379256845:

> `GRUB_BTRFS_CREATE_ONLY_HARMONIZED_ENTRIES` doesn't work as expected, `initramfs-linux-fallback` isn't included
Devs of arch use this patch [0003-10_linux-detect-archlinux-initramfs.patch](https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/grub) to include `initramfs-linux-fallback`
We should works on this part.

**Comment by Antynea** [comment]
I have some ideas
but little time to contribute
forgive my delay
hopes to work on this part this weekend

here my todo list :
1. improve kernel and initramfs detection by testing the existence of files before using them ,
 and display an error message if not found and exit cleanly
2. harmonized the grub menu by matching the kernel version and initramfs including fallback
3. think about changing the snapshot entry launch to match the new version
in the future clean the code, and use only this feature

**Comment by billwanjohi** [comment]
While there are lots of other improvements to be made, #43 would definitely have prevented my issues, by creating 100 versus 1200 entries in my grub.cfg. It's true that if I install 6+ kernels at a time, even these settings might cause me problems, but that's probably a fairly uncommon choice among the casual consumer. Thanks to both of you for taking my report so seriously; you've probably saved some future users a lot of grief.

**Comment by Antynea** [comment]
An elegant way that I found:
Send the script result to a specific file (e.g /boot/grub/grub.cfg)

GRUB will start normally, then when we select the submenu containing the sansphots, GRUB will load the file.
I tested successfully, be patient, it happens :)

loading time :
VM with 4 core assigned (intel i7 3960x)
a file of 600Kb, about 10 825 lines, 33 snapshots, 18 entries by snaps
6 seconds

**Comment by Antynea** [comment]
This hotfix bundle includes:
- All snapshots are now created in an external configuration file `/boot/grub-btrfs.cfg`
- Loading this file only starts when entering the submenu
- Due to these changes, GRUB shouldn't break anymore

Loading time:
GRUB = instant
Sub-menu =  6sec
(50 snapshots, 7 entries per snapshots, 350 entries in total)

**Comment by maximbaz** [comment]
Shall we close this since the fix is released?
