### ISSUE TITLE
UUID=X does not exist

### ISSUE THREAD

**Issue by RandomReaper** [Antynea/grub-btrfs#47]
I'm trying to use your script on ubuntu and the snapshots won't boot, the initrd does not finds the filesystem.

I replaced UUID with X, but the UUID of the partition and the UUID from the command line matches.

Here are some info:
/proc/cmdline with snapshot : 
BOOT_IMAGE=/@/.snapshots/5/snapshot/boot/vmlinuz-4.15.0-15-generic root=UUID=X rw rootflags=suvbol=@/.snapshots/5/snapshot

/proc/cmdline on normal boot:
BOOT_IMAGE=/@/boot/vmlinuz-4.15.0-15-generic root=/dev/mapper/root-root ro rootflags=subvol=@

**Comment by RandomReaper** [comment]
Is seems that your script does not honor GRUB_DISABLE_LINUX_UUID=true

**Comment by Antynea** [comment]
Hello,
forgive my late answer.

This script is based on UUID.
If you need to disable them in order to boot your system,  so this script isn't suitable for your system.

I suspect you are using LVM or something like that.
In that case, this script should not work ...

**Comment by RandomReaper** [comment]
As you may have seen, I have edited my comment about GRUB_DISABLE_LINUX_UUID. The problem is not really linked to this configuration option, but rather to the fact that grub does not uses UUID for RAID+LVM setups.

**Comment by Antynea** [comment]
Interesting,
can you show me your `grub.cfg` ?
I think the script doesn't use the GRUB detection features properly.

The parts 00_header and 10_linux should be enough.

**Comment by RandomReaper** [comment]
Here is my `grub.cfg` and a log of what happens when selecting a snapshot (stopping at initramfs shell):

[grub.cfg.txt](https://github.com/Antynea/grub-btrfs/files/2083422/grub.cfg.txt)
[boot-test-snapshot-failing.txt](https://github.com/Antynea/grub-btrfs/files/2083432/boot-test-snapshot-failing.txt)

**Comment by Antynea** [comment]
Thanks for report.
Patch available [in a new branch](https://github.com/Antynea/grub-btrfs/blob/47-UUID%3DX-does-not-exist/41_snapshots-btrfs).
Let met know your feedback.

**Comment by RandomReaper** [comment]
Tested 7883db704ab644c9ad003752566ed4094df2c76c on my LVM+RAID system and working.
Not tested for regression on systems using UUIDs...
