### ISSUE TITLE
Enhancement: GRUB_BTRFS_TITLE_FORMAT

### ISSUE THREAD

**Issue by cmonty14** [Antynea/grub-btrfs#50]
Hi!
Could you consider to enhance the GRUB_BTRFS_TITLE_FORMAT to include snapper type "single, pre, post"?
This could simplify identification of relevant snapshot in Grub.

Regards
Thomas

**Comment by Antynea** [comment]
Hello,
forgive my late answer.

Currently, it is a tricky thing to integrate the functionality you are requesting.
I hope to be able to integrate this later.

N.B: `GRUB_BTRFS_TITLE_FORMAT`, this feature, although it is operational, is only a patch and needs to be better integrated with the script

**Comment by ckotte** [comment]
I think this ticket can be closed!? This feature was probaby implemented in the meantime. I can see pre and post in the boot menu.

![image](https://user-images.githubusercontent.com/8488565/91657673-1cbea580-eac3-11ea-8cf0-fff543423d57.png)

**Comment by Antynea** [comment]
Maybe
