### ISSUE TITLE
Enhancement: subvolumes representing multiple Linux distribution available in GRUB

### ISSUE THREAD

**Issue by 74cmonty** [Antynea/grub-btrfs#51]
Hi,
this is certainly not an issue but rather an enhancement request, or at least a question to the developers.
So, I like the software you developed in the context of BTRFS + GRUB.

However, I don't know if GRUB menu will display multiple Linux installations in dedicated BTRFS subvolumes of the same BTRFS partition.

What is needed for this?

THX

**Comment by Antynea** [comment]
Hello,
I didn't understand the meaning of your question, so I can't answer it correctly.
Could you be more explicit? (think of providing examples)

**Comment by Antynea** [comment]
Relevant question.

I dunno how GRUB reacts in this configuration.
It would be interesting to do a test.

**Comment by 74cmonty** [comment]
OK. I build a system with 2 Linux distros.
The issue is that GRUB generates a wrong entry pointing to subvolume @parabola:
menuentry 'Linux Multi-boot GNU/Linux, 4.15.0-kali2-amd64 kernel' --class linux --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.15.0-kali2-amd64-advanced-faf5fb57-6c77-42bc-88aa-b66c0fbea945' {
        load_video
        set gfxpayload=keep
        insmod gzio
        insmod part_msdos
        insmod ext2
        set root='hd0,msdos1'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-ieee1275='ieee1275//sas/disk@0,msdos1' --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1  7873da82-dd49-4d92-97ab-2040a26a97ab
        else
          search --no-floppy --fs-uuid --set=root 7873da82-dd49-4d92-97ab-2040a26a97ab
        fi
        echo    'Loading 4.15.0-kali2-amd64 kernel ...'
        linux   /vmlinuz-4.15.0-kali2-amd64 root=UUID=faf5fb57-6c77-42bc-88aa-b66c0fbea945 rw rootflags=subvol=@parabola
        echo    'Initiale Ramdisk wird geladen …'
        initrd  /initrd.img-4.15.0-kali2-amd64
}

Instead this menu should have this line:
linux   /vmlinuz-4.15.0-kali2-amd64 root=UUID=faf5fb57-6c77-42bc-88aa-b66c0fbea945 rw rootflags=subvol=@kalilinux
(I can boot Kalilinx w/o issue once this line is modified.)

What must be modified in /etc/grub.d/ files to allow grub-mkconfig -o /boot/grub/grub.cfg generating the correct GRUB config file?

**Comment by Antynea** [comment]
hum,

Try this:

1 - 
* boot on `@parabola`
* chroot in `@Kalilinux`
* Install `Grub `package
* use `grub-mkconfig -o /boot/grub/grub-kalilinux.cfg `for generate a grub.cfg to another name (e.g grub-kalilinux.cfg)
* exit chroot

2 -
* in `@parabola` :
* Create 40_kalilinux (`/etc/grub.d/40_kalilinux`)
* Add this : 
> #! /usr/bin/env bash
> #
> 
> prefix="/usr"
> exec_prefix="/usr"
> datarootdir="/usr/share"
> sysconfdir="/etc"
> . "${sysconfdir}/default/grub"
> . "$datarootdir/grub/grub-mkconfig_lib"
> 
> cat << EOF
> submenu 'Kalilinux' {
>         configfile "$(make_system_path_relative_to_its_root /boot/grub/grub.cfg)"
> }
> EOF
* Use grub-mkconfig -o /boot/grub/grub.cfg
* Reboot and test

**Comment by 74cmonty** [comment]
Unfortunately there's an error when executing grub-mkconfig -o /boot/grub/grub.cfg in @parabola:
`[thomas@vm4-multiboot ~]$ sudo grub-mkconfig -o /boot/grub/grub.cfg
GRUB-Konfigurationsdatei wird erstellt …
Linux-Abbild gefunden: /boot/vmlinuz-linux-libre
initrd-Abbild gefunden: /boot/initramfs-linux-libre.img
Found fallback initramfs image: /boot/initramfs-linux-libre-fallback.img
Linux-Abbild gefunden: /boot/vmlinuz-4.16.0-kali2-amd64
initrd-Abbild gefunden: /boot/initrd.img-4.16.0-kali2-amd64
Linux-Abbild gefunden: /boot/vmlinuz-4.15.0-kali2-amd64
initrd-Abbild gefunden: /boot/initrd.img-4.15.0-kali2-amd64
Fehler: syntax error.
Fehler: Incorrect command.
Fehler: syntax error.
Syntaxfehler in Zeile 190
In der erzeugten GRUB-Konfigurationsdatei wurden
Syntaxfehler entdeckt. Stellen Sie sicher, das die Dateien
/etc/default/grub und /etc/grub.d/* fehlerfrei sind oder
erstellen Sie einen Fehlerbericht mit /boot/grub/grub.cfg.new als Anhang.
`

This is the content of /etc/grub.d/40_kalilinux:
`[thomas@vm4-multiboot ~]$ cat /etc/grub.d/40_kalilinux
#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

prefix="/usr"
exec_prefix="/usr"
datarootdir="/usr/share"
sysconfdir="/etc"
. "${sysconfdir}/default/grub"
. "$datarootdir/grub/grub-mkconfig_lib"

cat << EOF
submenu 'Kalilinux' {
configfile "$(make_system_path_relative_to_its_root /boot/grub/grub.cfg)"
}
EOF

`

**Comment by Antynea** [comment]
Your 40_kalilinux is wrong.
Corrected it.

Must look like [that](https://pastebin.com/pyxuDy8E)

**Comment by 74cmonty** [comment]
OK.
Using the correct syntax there's no error when creating new grub.cfg.

Verifying the content I can find these new lines:
`### BEGIN /etc/grub.d/40_kalilinux ###
submenu 'Kalilinux' {
configfile "/grub/grub.cfg"
}
### END /etc/grub.d/40_kalilinux ###
`

After reboot there's a new menu in Grub, however there's no action when selecting this item.

**Comment by Antynea** [comment]
Sorry, my bad.
Replace `configfile "/grub/grub.cfg"` by `configfile "/grub/grub-kalilinux.cfg"` or other name you have used when you have generate grub-mkconfig in your chroot.

**Comment by 74cmonty** [comment]
Hi,
I have created 2 screencast.
The short one documents the error when booting.

The other one documents that booting is working after modifying grub menu.

However, I think there's another issue:
Parabola is based on Arch Linux, Kali is based on Debian.
Both distributions use different scripts to create Grub menu.
When both distributions share the same boot partition, Grub will be overwritten once a Kernel update is installed.
This could be avoided when using dedicated boot partitions for each distribution.
However Grub loader would then fail I guess because Grub can manage only 1 boot loader.

[Screencasts.zip](https://github.com/Antynea/grub-btrfs/files/2094369/Screencasts.zip)

**Comment by 74cmonty** [comment]
I think I have to bury this project due to missing EFI support on my PC.
Thanks for your support!

**Comment by Antynea** [comment]
I took the time to watch your screencast,
so the code provided works, but impossible to start, strange ...

You have indicated that you can start by replacing '@parabola:' with '@kalilinux'
So just create a custom file like this:

`menuentry 'Linux Multi-boot GNU/Linux, 4.15.0-kali2-amd64 kernel' --class linux --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.15.0-kali2-amd64-advanced-faf5fb57-6c77-42bc-88aa-b66c0fbea945' { 
	load_video 
	set gfxpayload=keep 
	insmod gzio 
	insmod part_msdos 
	insmod ext2 
	set root='hd0,msdos1' 
	if [ x$feature_platform_search_hint = xy ]; then 
		search --no-floppy --fs-uuid --set=root --hint-ieee1275='ieee1275//sas/disk@0,msdos1' --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1 7873da82-dd49-4d92-97ab-2040a26a97ab 
	else search --no-floppy --fs-uuid --set=root 7873da82-dd49-4d92-97ab-2040a26a97ab 
	fi 
	echo 'Loading 4.15.0-kali2-amd64 kernel ...' 
	linux /vmlinuz-4.15.0-kali2-amd64 root=UUID=faf5fb57-6c77-42bc-88aa-b66c0fbea945 rw rootflags=subvol=@kalilinux 
	echo 'Initiale Ramdisk wird geladen …' 
	initrd /initrd.img-4.15.0-kali2-amd64
}`

correct code here : https://pastebin.com/zWApQZs3

**Comment by Antynea** [comment]
Once again, sorry for waiting

For your project, you don't need an EFI system.
However, having a common boot partition is problematic.
Do you really need it?

Here is a first approach to what you are looking for:

* Create a "50_multi_distro_btrfs" file in /etc/grub.d
* Add this : [50_multi_distro_btrfs](https://gist.github.com/Antynea/4582076565e2242aa95d06675c413211)
* Make it executable `chmod + x /etc/grub.d/50_multi_distro_btrfs`
* Generate the grub menu 'grub-mkconfig - /boot/grub/grub.cfg'

My test system:
/dev/sda1 = /boot (ext2)
/dev/sda2 = / (btrfs)
Btrfs partition contains :
* `@archlinux`
* `@kalilinux`
* `@snapshot`

The proposed script, list all subvolumes on the btrfs partition.
Discards those that aren't bootable distributions.
Create a menu for each distribution

[Screencast](https://github.com/Antynea/grub-btrfs/files/2119330/multi-distro-btrfs.zip) available 

Looking forward to hearing from you,
Regards.

**Comment by johnr14** [comment]
@Antynea I am trying out the 50_multi_distro_btrfs file. Seems cool. On first try, it will not chroot into individual distribution to update the grub and all. I think your script is a must to do system upgrades !

Here is how I did it.
1) On a fresh 18.04 Ubuntu, created GPT, created multiple ext4 for /boot(s), created a large btrfs; installed ubuntu & moved `@` to `@bionic`; booted and all is fine.
2) Made `@eoan` sub
3) Moved eoan from other drive's xfs to btrfs sub
4) Fixed fstab & cryptab
5) Updated grub

> ` ###### `- Multi-distro-btrfs: subvolume detection started - ######
> `#` Found distro: Ubuntu 18.04.2 LTS
> `#` Found distro: Ubuntu Eoan Ermine (development branch)
> `######` - Multi-distro-btrfs: subvolume detection ended   - ######

So while in Bionic, I was hoping that Eoan would install to it's new boot to it's fstab : 
`/dev/disk/by-partlabel/wks_boot_eoan /boot ext4 defaults,noatime `

So I had to do this next : 
```
cd /mnt/wks_system/@eoan 
sudo mount --bind /dev dev &&
sudo mount --bind /dev/pts dev/pts &&
sudo mount --bind /proc proc &&
sudo mount --bind /sys sys 
sudo chroot .
mount /boot
mkdir -p /boot/efi
mount /boot/efi
mount /
grub-install /dev/disk/by-partlabel/wks_boot_bleed # script must figure this from fstab
update-grub # check errors ?
exit 
sudo umount sys &&
sudo umount proc &&
sudo umount dev/pts &&
sudo umount dev 
```
Afterward it broke my grub somehow. Will play around some more to get it right. I think I should just have copied the boot of `/dev/disk/by-partlabel/wks_boot_bionic` to `/dev/disk/by-partlabel/wks_boot_eoan`

**Comment by johnr14** [comment]
In the `/boot/grub/multi-distro-grub-btrfs.cfg`, there seems to be an error that get's in. There is 2 rootflags.

linux "/vmlinuz-4.15.0-52-generic" root=UUID=10872060-339d-4f94-9938-3bdacf7195c1 rw **rootflags=subvol="@eoan**" cryptopts=target=wks_system,source=/dev/disk/by-partlabel/wks_system **rootflags=subvol=@bionic** quiet splash amdgpu.ppfeaturemask=0xffffffff

**Comment by johnr14** [comment]
It seems the script parse `/etc/default/grub`  and appends : 
`GRUB_CMDLINE_LINUX="cryptopts=target=wks_system,source=/dev/disk/by-partlabel/wks_system rootflags=subvol=@bionic"
` on line 24 in kernel_parameters

Trying to parse with : 
`cat /etc/default/grub | sed -n -e 's/GRUB_CMDLINE_LINUX=\"//p' | sed -n -e 's/rootflags=subvol=@.*\S//p'`
It should remove only the rootflags...
resulting in `cryptopts=target=wks_system,source=/dev/disk/by-partlabel/wks_system `

Also, copied files in wks_boot_bionic to wks_boot_eoan
Will try out.

**Comment by johnr14** [comment]
It also seems that 50_multi_distro_btrfs doesn't get the right fs_uuid as I made a few different boot partitions to host different versions of ubuntu as well as fedora.

Should I have done a single big /boot for all distributions ? Will try changing fstab to same /boot and reinstall kernel and update-grub.
