### ISSUE TITLE
41_snapshots-btrfs dosen't run

### ISSUE THREAD

**Issue by SONE1986** [Antynea/grub-btrfs#58]
Hi,

When I try to run "sh 41_snapshots-btrfs" nothing happens, no output, nothing :(

`[demo@btrfs01 grub.d]$ sh 41_snapshots-btrfs`
`[demo@Abemisser grub.d]$`

My EFI is mounted at /boot/efi and my grub.cfg is located in /boot/efi/grub/ I don't if this has something to say?

Linux 4.19.1-arch1-1-ARCH #1 SMP PREEMPT Sun Nov 4 16:49:26 UTC 2018 x86_64 GNU/Linux

Is it possible to enable some kind of debug log?

Best Regards
Soren

**Comment by maximbaz** [comment]
Hi there, it is not intended to be run as a script I think :)

But to answer your question, try commenting the first line `set -e` and re-running it, I believe it will start printing some errors.

**Comment by Antynea** [comment]
Hi

> When I try to run "sh 41_snapshots-btrfs"
It's a bash script, not a shell script. Use `bash` instead of `sh`

> Is it possible to enable some kind of debug log?
`bash -x 41_snapshots-btrfs`

**Comment by SONE1986** [comment]
Thanks for quick reply :)

Know it's not meant to be run as a scripts, this was only to find out what went wrong.

With `set -e` comment out, i now gets this:

`###### - Grub-btrfs: Snapshot detection started - ######`
`mount: /tmp/tmp.zXBWyTrSwz: /dev/disk/by-uuid is not a block device.`

I can't figure out of this have something to do with my fstab?
`UUID=7a808fcf-2332-44e2-b28f-1518f5774c8f       /               btrfs           rw,noatime,compress=lzo,space_cache,subvolid=258,subvol=@root   0 0`

`UUID=69EE-0FEE          /boot/efi       vfat            rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro       0 2`

Running it with bash -x, I get this output:

+ prefix=/usr
+ exec_prefix=/usr
+ datarootdir=/usr/share
+ sysconfdir=/etc
+ grub_btrfs_config=/etc/grub.d/41_snapshots-btrfs_config
+ . /etc/default/grub
++ GRUB_DEFAULT=0
++ GRUB_TIMEOUT=5
++ GRUB_DISTRIBUTOR=Arch
++ GRUB_CMDLINE_LINUX_DEFAULT=quiet
++ GRUB_CMDLINE_LINUX=
++ GRUB_PRELOAD_MODULES='part_gpt part_msdos'
++ GRUB_TERMINAL_INPUT=console
++ GRUB_GFXMODE=auto
++ GRUB_GFXPAYLOAD_LINUX=keep
++ GRUB_DISABLE_RECOVERY=true
+ [[ -f /etc/grub.d/41_snapshots-btrfs_config ]]
+ . /etc/grub.d/41_snapshots-btrfs_config
+ . /usr/share/grub/grub-mkconfig_lib
++ prefix=/usr
++ exec_prefix=/usr
++ datarootdir=/usr/share
++ datadir=/usr/share
++ bindir=/usr/bin
++ sbindir=/usr/bin
++ '[' x = x ']'
++ pkgdatadir=/usr/share/grub
++ test x = x
++ grub_probe=/usr/bin/grub-probe
++ test x = x
++ grub_file=/usr/bin/grub-file
++ test x = x
++ grub_mkrelpath=/usr/bin/grub-mkrelpath
++ which gettext
++ :
++ grub_tab='	'
+ grub_btrfs_disable=false
+ [[ false == \t\r\u\e ]]
+ submenuname='Arch Linux snapshots'
+ prefixentry=Snapshot:
+ path_snapshot=true
+ title_format=p/d/n
+ nkernel=("${GRUB_BTRFS_NKERNEL[@]}")
+ ninit=("${GRUB_BTRFS_NINIT[@]}")
+ microcode=("${GRUB_BTRFS_INTEL_UCODE[@]}")
+ limit_snap_show=50
+ snap_list_sort=descending
+ case "${snap_list_sort}" in
+ btrfssubvolsort=("--sort=-rootid")
+ show_snap_found=true
+ show_total_snap_found=true
+ ignore_specific_path=("${GRUB_BTRFS_IGNORE_SPECIFIC_PATH[@]}")
+ snapper_config=root
+ override_boot_partition_detection=false
+ grub_directory=grub
+ export TEXTDOMAIN=grub-btrfs-git
+ TEXTDOMAIN=grub-btrfs-git
+ export TEXTDOMAINDIR=/usr/share/locale
+ TEXTDOMAINDIR=/usr/share/locale
++ /usr/bin/grub-probe --target=device /boot
+ boot_device='/dev/sda2
/dev/sdb2'
++ /usr/bin/grub-probe --device '/dev/sda2
/dev/sdb2' --target=hints_string
+ boot_hs=
++ /usr/bin/grub-probe --device '/dev/sda2
/dev/sdb2' --target=fs_uuid
+ boot_uuid=
++ /usr/bin/grub-probe --target=fs /boot
+ boot_fs=btrfs
++ /usr/bin/grub-probe --target=device /
+ root_device='/dev/sda2
/dev/sdb2'
++ /usr/bin/grub-probe --device '/dev/sda2
/dev/sdb2' --target=fs_uuid
+ root_uuid=
+ kernel_parameters=' quiet'
++ mktemp -d
+ gbgmp=/tmp/tmp.Fgwm0M5e4A
+ CLASS='--class snapshots --class gnu-linux --class gnu --class os'
+ oldIFS=' 	
'
+ printf '###### - Grub-btrfs: Snapshot detection started - ######\n'
###### - Grub-btrfs: Snapshot detection started - ######
+ test_btrfs
+ set +e
+ type btrfs
+ [[ 0 -ne 0 ]]
+ set -e
+ [[ ! -d /tmp/tmp.Fgwm0M5e4A ]]
+ mount -o subvolid=5 /dev/disk/by-uuid/ /tmp/tmp.Fgwm0M5e4A/
mount: /tmp/tmp.Fgwm0M5e4A: /dev/disk/by-uuid is not a block device.

Any ideas?

**Comment by Antynea** [comment]
`/usr/bin/grub-probe --target=device /boot`
`boot_device='/dev/sda2
/dev/sdb2'`

Something goes wrong with your system
`grub-prob` detect "two boot device"

Need more info on your system

**Comment by SONE1986** [comment]
My /boot is located on my btrfs subvol and is combined by /dev/sda2 /dev/sdb2 in a raid0

<- Arch installation process ->
`mkfs.btrfs -L Arch -d raid0 /dev/sda2 /dev/sdb2`
`btrfs subvolume create /mnt/_root` 
`umount /mnt`
`mount -o noatime,compress=lzo,space_cache,commit=120,subvol=_root /dev/sda2 /mnt`
`pacstrap /mnt base`

Have I done anything wrong here?

What kind of information do you need?

Best Regards

**Comment by Antynea** [comment]
Thanks
Can you post the output of `findmnt`
And what directory have you specify when you use `grub-install` ? (/boot or /boot/efi or other)

**Comment by SONE1986** [comment]
findmnt:
TARGET                                SOURCE            FSTYPE     OPTIONS
/                                     /dev/sda2[/@root] btrfs      rw,noatime,compress=lzo,space_cache,subvolid=258,subvol=/@root
├─/proc                               proc              proc       rw,nosuid,nodev,noexec,relatime
│ └─/proc/sys/fs/binfmt_misc          systemd-1         autofs     rw,relatime,fd=25,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14425
├─/sys                                sys               sysfs      rw,nosuid,nodev,noexec,relatime
│ ├─/sys/firmware/efi/efivars         efivarfs          efivarfs   rw,nosuid,nodev,noexec,relatime
│ ├─/sys/kernel/security              securityfs        securityfs rw,nosuid,nodev,noexec,relatime
│ ├─/sys/fs/cgroup                    tmpfs             tmpfs      ro,nosuid,nodev,noexec,mode=755
│ │ ├─/sys/fs/cgroup/unified          cgroup2           cgroup2    rw,nosuid,nodev,noexec,relatime,nsdelegate
│ │ ├─/sys/fs/cgroup/systemd          cgroup            cgroup     rw,nosuid,nodev,noexec,relatime,xattr,name=systemd
│ │ ├─/sys/fs/cgroup/cpu,cpuacct      cgroup            cgroup     rw,nosuid,nodev,noexec,relatime,cpu,cpuacct
│ │ ├─/sys/fs/cgroup/freezer          cgroup            cgroup     rw,nosuid,nodev,noexec,relatime,freezer
│ │ ├─/sys/fs/cgroup/blkio            cgroup            cgroup     rw,nosuid,nodev,noexec,relatime,blkio
│ │ ├─/sys/fs/cgroup/devices          cgroup            cgroup     rw,nosuid,nodev,noexec,relatime,devices
│ │ ├─/sys/fs/cgroup/net_cls,net_prio cgroup            cgroup     rw,nosuid,nodev,noexec,relatime,net_cls,net_prio
│ │ ├─/sys/fs/cgroup/cpuset           cgroup            cgroup     rw,nosuid,nodev,noexec,relatime,cpuset
│ │ ├─/sys/fs/cgroup/pids             cgroup            cgroup     rw,nosuid,nodev,noexec,relatime,pids
│ │ ├─/sys/fs/cgroup/perf_event       cgroup            cgroup     rw,nosuid,nodev,noexec,relatime,perf_event
│ │ ├─/sys/fs/cgroup/hugetlb          cgroup            cgroup     rw,nosuid,nodev,noexec,relatime,hugetlb
│ │ ├─/sys/fs/cgroup/memory           cgroup            cgroup     rw,nosuid,nodev,noexec,relatime,memory
│ │ └─/sys/fs/cgroup/rdma             cgroup            cgroup     rw,nosuid,nodev,noexec,relatime,rdma
│ ├─/sys/fs/pstore                    pstore            pstore     rw,nosuid,nodev,noexec,relatime
│ ├─/sys/fs/bpf                       bpf               bpf        rw,nosuid,nodev,noexec,relatime,mode=700
│ ├─/sys/kernel/config                configfs          configfs   rw,relatime
│ └─/sys/kernel/debug                 debugfs           debugfs    rw,relatime
├─/dev                                dev               devtmpfs   rw,nosuid,relatime,size=484692k,nr_inodes=121173,mode=755
│ ├─/dev/shm                          tmpfs             tmpfs      rw,nosuid,nodev
│ ├─/dev/pts                          devpts            devpts     rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000
│ ├─/dev/mqueue                       mqueue            mqueue     rw,relatime
│ └─/dev/hugepages                    hugetlbfs         hugetlbfs  rw,relatime,pagesize=2M
├─/run                                run               tmpfs      rw,nosuid,nodev,relatime,mode=755
│ └─/run/user/1000                    tmpfs             tmpfs      rw,nosuid,nodev,relatime,size=98356k,mode=700,uid=1000,gid=1000
├─/tmp                                tmpfs             tmpfs      rw,nosuid,nodev
└─/boot/efi                           /dev/sda1         vfat       rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro

grub-install:
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=arch --boot-directory=/boot/efi --recheck --no-floppy

I had an early installation where my EFI(vfat) was mounted directly to /boot, which worked great with grub-btrfs. The reason I have my EFI mounted in /boot/efi, is because I will have the full benefit of snaps + btrfs-grub, so I can go back on kernel upgrade :)

Best Regards

**Comment by Antynea** [comment]
ok, 
you have install grub in `/boot/efi`

I think I know why the script doesn't work.

I have to rewrite certain things.
I can not do it now.
please be patient :)

**Comment by SONE1986** [comment]
OK, cool :D This is just my test environment, no rush.

**Comment by Antynea** [comment]
Hi,
Can you provide me your grub.cfg please?

Can you test this [file,](https://gist.github.com/Antynea/3bbf49b0531483e688c8fd8e588d7b9c) with ` bash -x` and post result. (Errors must be different)

**Comment by SONE1986** [comment]
Sure :) 
[grub.cfg.zip](https://github.com/Antynea/grub-btrfs/files/2591972/grub.cfg.zip)

I'll test later tonight ;)

**Comment by SONE1986** [comment]
I just ran a quick test on your new file and yes, the result differ from the last one.

50_test: line 506: /boot/grub/grub-btrfs.cfg: No such file or directory <- makes sense since my grub.cfg is located in /boot/efi/grub/

Result:

[demo@Abemisser grub.d]$ sudo bash -x 50_test 
+ set -e
+ prefix=/usr
+ exec_prefix=/usr
+ datarootdir=/usr/share
+ sysconfdir=/etc
+ grub_btrfs_config=/etc/grub.d/41_snapshots-btrfs_config
+ . /etc/default/grub
++ GRUB_DEFAULT=0
++ GRUB_TIMEOUT=5
++ GRUB_DISTRIBUTOR=Arch
++ GRUB_CMDLINE_LINUX_DEFAULT=quiet
++ GRUB_CMDLINE_LINUX=
++ GRUB_PRELOAD_MODULES='part_gpt part_msdos'
++ GRUB_TERMINAL_INPUT=console
++ GRUB_GFXMODE=auto
++ GRUB_GFXPAYLOAD_LINUX=keep
++ GRUB_DISABLE_RECOVERY=true
+ [[ -f /etc/grub.d/41_snapshots-btrfs_config ]]
+ . /etc/grub.d/41_snapshots-btrfs_config
+ . /usr/share/grub/grub-mkconfig_lib
++ prefix=/usr
++ exec_prefix=/usr
++ datarootdir=/usr/share
++ datadir=/usr/share
++ bindir=/usr/bin
++ sbindir=/usr/bin
++ '[' x = x ']'
++ pkgdatadir=/usr/share/grub
++ test x = x
++ grub_probe=/usr/bin/grub-probe
++ test x = x
++ grub_file=/usr/bin/grub-file
++ test x = x
++ grub_mkrelpath=/usr/bin/grub-mkrelpath
++ which gettext
++ :
++ grub_tab='	'
+ grub_btrfs_disable=false
+ [[ false == \t\r\u\e ]]
+ submenuname='Arch Linux snapshots'
+ prefixentry=Snapshot:
+ path_snapshot=true
+ title_format=p/d/n
+ nkernel=("${GRUB_BTRFS_NKERNEL[@]}")
+ ninit=("${GRUB_BTRFS_NINIT[@]}")
+ microcode=("${GRUB_BTRFS_INTEL_UCODE[@]}")
+ limit_snap_show=50
+ snap_list_sort=descending
+ case "${snap_list_sort}" in
+ btrfssubvolsort=("--sort=-rootid")
+ show_snap_found=true
+ show_total_snap_found=true
+ ignore_specific_path=("${GRUB_BTRFS_IGNORE_SPECIFIC_PATH[@]}")
+ snapper_config=root
+ override_boot_partition_detection=false
+ grub_directory=grub
+ export TEXTDOMAIN=grub-btrfs-git
+ TEXTDOMAIN=grub-btrfs-git
+ export TEXTDOMAINDIR=/usr/share/locale
+ TEXTDOMAINDIR=/usr/share/locale
++ /usr/bin/grub-probe --target=device /boot
+ boot_device='/dev/sda2
/dev/sdb2'
++ /usr/bin/grub-probe --device /dev/sda2 /dev/sdb2 --target=hints_string
+ boot_hs='--hint-ieee1275='\''ieee1275//disk@0,gpt2'\'' --hint-bios=hd0,gpt2 --hint-efi=hd0,gpt2 --hint-baremetal=ahci0,gpt2  --hint-ieee1275='\''ieee1275//disk@0,gpt2'\'' --hint-bios=hd1,gpt2 --hint-efi=hd1,gpt2 --hint-baremetal=ahci1,gpt2 '
++ /usr/bin/grub-probe --device /dev/sda2 /dev/sdb2 --target=fs_uuid
+ boot_uuid=7a808fcf-2332-44e2-b28f-1518f5774c8f
++ /usr/bin/grub-probe --target=fs /boot
+ boot_fs=btrfs
++ /usr/bin/grub-probe --target=device /
+ root_device='/dev/sda2
/dev/sdb2'
++ /usr/bin/grub-probe --device /dev/sda2 /dev/sdb2 --target=fs_uuid
+ root_uuid=7a808fcf-2332-44e2-b28f-1518f5774c8f
+ kernel_parameters=' quiet'
++ mktemp -d
+ gbgmp=/tmp/tmp.2Qemipkl13
+ CLASS='--class snapshots --class gnu-linux --class gnu --class os'
+ oldIFS=' 	
'
+ printf '###### - Grub-btrfs: Snapshot detection started - ######\n'
###### - Grub-btrfs: Snapshot detection started - ######
+ test_btrfs
+ set +e
+ type btrfs
+ [[ 0 -ne 0 ]]
+ set -e
50_test: line 506: /boot/grub/grub-btrfs.cfg: No such file or directory

**Comment by Antynea** [comment]
ok nice :)

- next: correct path

line 91, replace `grub_directory=${GRUB_BTRFS_DIRNAME:-"grub"}` by
`grub_directory=${GRUB_BTRFS_DIRNAME:-"efi/grub"}`

or edit `41_snapshots-btrfs_config`
line 17, replace `# GRUB_BTRFS_DIRNAME=grub ` by
`GRUB_BTRFS_DIRNAME=efi/grub`

**Comment by SONE1986** [comment]
You nailed it :) Everything are working so great now. Adding to grub-btrfs.cfg and booting snapshots :D 

[demo@Abemisser grub.d]$ sudo bash 41_snapshots-btrfs
###### - Grub-btrfs: Snapshot detection started - ######
# Info: Separate boot partition not detected 
# Found snapshot: 2018-11-18 09:35:27 | @root/.snapshots/20/snapshot | post | archlinux-keyring libsystemd linux nano patch systemd systemd-sysvcompat
# Found snapshot: 2018-11-18 09:34:51 | @root/.snapshots/19/snapshot | pre  | pacman -Syyu
# Found snapshot: 2018-11-18 09:23:34 | @root/.snapshots/18/snapshot | post | snap-pac-grub
# Found snapshot: 2018-11-18 09:23:34 | @root/.snapshots/17/snapshot | pre  | /usr/bin/pacman -U /home/demo/snap-pac-grub/snap-pac-grub-1.0.4-4-any.pkg...
# Found snapshot: 2018-11-15 20:46:08 | @root/.snapshots/16/snapshot | post | grub-btrfs
# Found snapshot: 2018-11-15 20:46:08 | @root/.snapshots/15/snapshot | pre  | /usr/bin/pacman -U /home/demo/grub-btrfs/grub-btrfs-3.5-2-any.pkg.tar.xz
# Found snapshot: 2018-11-15 20:26:15 | @root/.snapshots/14/snapshot | post | grub-btrfs snap-pac-grub
# Found snapshot: 2018-11-15 20:26:15 | @root/.snapshots/13/snapshot | pre  | pacman -Rc grub-btrfs snap-pac-grub
# Found snapshot: 2018-11-14 22:42:12 | @root/.snapshots/12/snapshot | post | gptfdisk
# Found snapshot: 2018-11-14 22:42:12 | @root/.snapshots/11/snapshot | pre  | pacman -S gdisk
# Found snapshot: 2018-11-14 22:31:57 | @root/.snapshots/10/snapshot | post | apr apr-util libutf8proc serf subversion
# Found snapshot: 2018-11-14 22:31:55 | @root/.snapshots/9/snapshot  | pre  | pacman -S subversion
# Found snapshot: 2018-11-14 22:28:19 | @root/.snapshots/8/snapshot  | post | apr apr-util libutf8proc serf subversion
# Found snapshot: 2018-11-14 22:28:19 | @root/.snapshots/7/snapshot  | pre  | pacman -Rsc subversion
# Found snapshot: 2018-11-14 22:22:31 | @root/.snapshots/6/snapshot  | post | apr apr-util libutf8proc serf subversion
# Found snapshot: 2018-11-14 22:22:29 | @root/.snapshots/5/snapshot  | pre  | pacman -S subversion
# Found snapshot: 2018-11-14 22:21:47 | @root/.snapshots/4/snapshot  | post | snap-pac-grub
# Found snapshot: 2018-11-14 22:21:47 | @root/.snapshots/3/snapshot  | pre  | /usr/bin/pacman -U /home/demo/snap-pac-grub/snap-pac-grub-1.0.4-4-any.pkg...
# Found snapshot: 2018-11-14 22:17:46 | @root/.snapshots/2/snapshot  | post | snap-pac
# Found snapshot: 2018-11-14 22:17:45 | @root/.snapshots/1/snapshot  | pre  | pacman -S snap-pac
# Found 20 snapshot(s)
submenu 'Arch Linux snapshots' {
	configfile "/grub/grub-btrfs.cfg"
}
###### - Grub-btrfs: Snapshot detection ended   - ######

Only thing that needs update is "snap-pac-grub" because `/usr/share/libalpm/scripts/grub-mkconfig`
points to /boot/grub/grub.cfg, but that's nothing to do with you. Thanks mate :)

Best Regards
Soren

**Comment by maximbaz** [comment]
It is me who maintains `snap-pac-grub`, I want to see how @Antynea gets this solved in this repo and I'll do the same.

But I'm still confused about your location of `grub.cfg`, can you explain in more details why you made this layout?

> I had an early installation where my EFI(vfat) was mounted directly to /boot, which worked great with grub-btrfs. The reason I have my EFI mounted in /boot/efi, is because I will have the full benefit of snaps + btrfs-grub, so I can go back on kernel upgrade :)

This sounds correct to mount EFI to `/boot/efi`, so that `/boot` remains on btrfs and can be snapshotted — I do it too. But why did you install grub into EFI and not into btrfs? Having grub installed on btrfs partition will allow you to snapshot it too.

**Comment by SONE1986** [comment]
Hi Maximbaz,

The reason that i put my grub.cfg in /boot/efi/grub/, is that my system was unable to boot when i had my grub.cfg in /boot/grub/. If my grub.cfg didn't resist on the EFI(FAT) vol, it was unable to locate the grub.cfg, and i was instantly dropped to the grub rescue shell. I can't tell why, because what i read, grub should be able to boot from btrfs subvol, in my case `@root/boot/grub/grub.cfg` but no matter what i did, I wasn't able to accomplish. I hope it makes sense? :)

**Comment by maximbaz** [comment]
This is strange, it definitely works for me. Personally, I recommend you looking into it once more, of course making path configurable in a few projects would "solve" the issue, but it hides the fact that you aren't snapshotting grub...

When I installed Arch, I [documented my every step](https://github.com/maximbaz/dotfiles/blob/master/INSTALL_ARCH.md) for future reference, if you want to investigate you can compare how you setup your system and how I do it, to find the difference.

**Comment by SONE1986** [comment]
Actually, I had another strange experience for some days ago [https://bbs.archlinux.org/viewtopic.php?id=241886](url), I wasn't able to boot my system, I just got the error message in the link, but after I did a new Arch installation on my NUC PC instead of my VMWare Fusion - Suddenly, i could boot my system with the same settings etc. And now to the fun part, I just tried to do the same with my grub.cfg in `/boot/grub/` and now it boots! I can't tell why, but maybe there are something with the EFI emulation in VMWare Fusion. But everything is now working as I should :)

**Comment by maximbaz** [comment]
Congrats on making it work 😉 

In this case @Antynea I suggest we don't make it configurable and close this issue for now, no need to have code that nobody is using anyway.

**Comment by Antynea** [comment]
@maximbaz, 
there is actually only one bug reported in this issue.
"grub-btrfs don't recognize the raid 0 array made by btrfs"
my pull request corrects that.

"Grub path" is configurable since version [3.3,](https://github.com/Antynea/grub-btrfs/releases/tag/3.3) so I have nothing to do :)

I think I can push my fix and close this issue.

**Comment by SONE1986** [comment]
For me everything works perfectly now ;) grub.cfg in /boot/grub after install to Bare Metal (Intel NUC) and grub-btrfs is working with the changes you made @Antynea :)

Best Regards
