### ISSUE TITLE
Debian: Failure when booting after rollback (Kernel panic)

### ISSUE THREAD

**Issue by 74cmonty** [Antynea/grub-btrfs#61]
Hi,
I have setup BTRFS snapshots successfully and can boot any snapshot from Grub.
However I have identified an issue related to snapshot rollback.

Steps to reproduce the issue (with Debian 9.6):
1. Boot snapshot X
2. After system is loaded it is read-only and not fully usable
3. Rollback snapshot X with command `snapper rollback X`
4. `snapper rollback` will create additional snapshots, of which one is a read-write snapshot Y of snapshot X; in addition this snapshot Y will be set as default snapshot (corresponding to `btrfs subvolume set-default Y`)
5. reboot and select default entry

The system will not boot and run into Kernel panic.

A workaround to boot w/o errors is to edit the entry related to default by means of modifying the line starting with "linux"; here the string `rootflags=...` must be deleted.

Do you have an idea for a permanent fix?

**Comment by Antynea** [comment]
hello,
Thanks for your feedback.

I don't use snapper software
but what you describe makes me think of[ this video.](https://www.youtube.com/watch?v=sIBgVWf5hd8)
Maybe @maximbaz can help you.

While waiting for an answer from him.

>2. After system is loaded it is read-only and not fully usable

According to my knowledge, snapper creates "snapshots read only by default"
The systemd software needs to write its log on a write file system.
To start on a read-only file system is a problem.
However you can fine tune the systemd setting and avoid this inconvenience :)

> A workaround to boot w/o errors is to edit the entry related to default by means of modifying the line starting with "linux"; here the string rootflags=... must be deleted.

I don't understand.
If you start on the default entry, my script has nothing to do with your problem.
your default entry is wrong, and i think after rollback you must launch grub-mkconfig for update grub.

Sorry, i can take the time to install debian 9.6 on vm
and test your setup, jsut tell me how is your setup :)

**Comment by maximbaz** [comment]
It's on my list to actually try out and document the rollback procedure, but I'm not sure when I'll get to this... However I agree this isn't really an issue with `grub-btrfs` project, since you managed to boot into a snapshot and execute some commands, `grub-btrfs` has successfully accomplished its mission 🙂 It's a question about how to properly rollback, with snapper or default btrfs commands.

**Comment by Antynea** [comment]
@maximbaz 
That's what I thought,
and that's why I opened a new branch for version4.
I removed any indication about a rollback on the readme,
because grub-btrfs doesn't do that. it just boot on "btrfs snapshots"

**Comment by Antynea** [comment]
If I summarize your request.
Your snapshots are available in the Grub menu
You are able to start from the menu on a snapshot
Your request doesn't concern grub-btrfs project....

How can we help you?

**Comment by 74cmonty** [comment]
This is not totally correct.

Snapper is setting a new default subvolume that is the RW snapshot of the rollback.
In order to boot this RW snapshot I must select is from Grub menu. This is inconvenient in particular if the PC reboots and I cannot interrupt default boot sequence.

If the default boot entry in Grub menu would not include this string `rootflags=subvol=@` the system would boot like charm, means the new default subvolume would be started.

**Comment by Antynea** [comment]
The default boot entry is managed by Grub (not grub-btrfs) ...

However here is the solution to your request : 
##
### Warning
### modify a system file is dangerous.
### I can not be held responsible for consequences that flow
## 
Edit `/etc/grub.d/10_linux`
Replace 
`GRUB_CMDLINE_LINUX="rootflags=subvol=${rootsubvol} ${GRUB_CMDLINE_LINUX}"`
by
`GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX}"`

then update Grub

Ps: contact [Grub mailing list](https://www.gnu.org/software/grub/grub-mailinglist.html), I don't support it.

**Comment by 74cmonty** [comment]
Many thanks.
Basically you confirm my assumption for the required modification.

I will now reach out to Grub and report this issue and the proposed solution.

**Comment by 74cmonty** [comment]
Hi André,
I have reopened this issue because I want to address another question related to this issue.

After setting up a new Debian 9.9 installation I noticed an inconsistency in Grub Menu vs. _/boot/grub/grub.cfg_.

If you compare the attached screenshot with the current _/boot/grub/grub.cfg_ the lines "linux" and "initrd" are different **and** the header header displays another Grub version than installed (grub-common = 2.02).
![2019-05-21_17-16-41](https://user-images.githubusercontent.com/12523591/58234569-247b9000-7d3f-11e9-9a38-575742ec892e.jpg)
`#
# DO NOT EDIT THIS FILE
#
# It is automatically generated by grub-mkconfig using templates
# from /etc/grub.d and settings from /etc/default/grub
#

### BEGIN /etc/grub.d/00_header ###
if [ -s $prefix/grubenv ]; then
  set have_grubenv=true
  load_env
fi
if [ "${next_entry}" ] ; then
   set default="${next_entry}"
   set next_entry=
   save_env next_entry
   set boot_once=true
else
   set default="0"
fi

if [ x"${feature_menuentry_id}" = xy ]; then
  menuentry_id_option="--id"
else
  menuentry_id_option=""
fi

export menuentry_id_option

if [ "${prev_saved_entry}" ]; then
  set saved_entry="${prev_saved_entry}"
  save_env saved_entry
  set prev_saved_entry=
  save_env prev_saved_entry
  set boot_once=true
fi

function savedefault {
  if [ -z "${boot_once}" ]; then
    saved_entry="${chosen}"
    save_env saved_entry
  fi
}
function load_video {
  if [ x$feature_all_video_module = xy ]; then
    insmod all_video
  else
    insmod efi_gop
    insmod efi_uga
    insmod ieee1275_fb
    insmod vbe
    insmod vga
    insmod video_bochs
    insmod video_cirrus
  fi
}

if [ x$feature_default_font_path = xy ] ; then
   font=unicode
else
insmod part_gpt
insmod btrfs
set root='hd0,gpt3'
if [ x$feature_platform_search_hint = xy ]; then
  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt3
--hint-efi=hd0,gpt3 --hint-baremetal=ahci0,gpt3  9bffc581-bb88-4aa3-b8da-1a6
a1054bd0a
else
  search --no-floppy --fs-uuid --set=root
9bffc581-bb88-4aa3-b8da-1a6a1054bd0a
fi
    font="/@snapshots/36/snapshot/usr/share/grub/unicode.pf2"
fi

if loadfont $font ; then
  set gfxmode=auto
  load_video
  insmod gfxterm
  set locale_dir=$prefix/locale
  set lang=de_DE
  insmod gettext
fi
terminal_output gfxterm
if [ "${recordfail}" = 1 ] ; then
  set timeout=30
else
  if [ x$feature_timeout_style = xy ] ; then
    set timeout_style=menu
    set timeout=5
  # Fallback normal timeout code in case the timeout_style feature is
  # unavailable.
  else
    set timeout=5
  fi
fi
### END /etc/grub.d/00_header ###

### BEGIN /etc/grub.d/05_debian_theme ###
set menu_color_normal=cyan/blue
set menu_color_highlight=white/blue
### END /etc/grub.d/05_debian_theme ###

### BEGIN /etc/grub.d/10_linux ###
function gfxmode {
        set gfxpayload="${1}"
}
set linux_gfx_mode=
export linux_gfx_mode
menuentry 'Proxmox Virtual Environment GNU/Linux' --class proxmox
--class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-s
imple-9bffc581-bb88-4aa3-b8da-1a6a1054bd0a' {
        load_video
        insmod gzio
        if [ x$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
        insmod part_gpt
        insmod btrfs
        set root='hd0,gpt3'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt3
--hint-efi=hd0,gpt3 --hint-baremetal=ahci0,gpt3  9bffc581-bb88-4aa3-
b8da-1a6a1054bd0a
        else
          search --no-floppy --fs-uuid --set=root
9bffc581-bb88-4aa3-b8da-1a6a1054bd0a
        fi
        echo    'Linux 4.15.18-14-pve wird geladen …'
        linux   /@snapshots/36/snapshot/boot/vmlinuz-4.15.18-14-pve
root=UUID=9bffc581-bb88-4aa3-b8da-1a6a1054bd0a ro
        echo    'Initiale Ramdisk wird geladen …'
        initrd  /@snapshots/36/snapshot/boot/initrd.img-4.15.18-14-pve
}
submenu 'Erweiterte Optionen für Proxmox Virtual Environment GNU/Linux'
$menuentry_id_option 'gnulinux-advanced-9bffc581-bb88-4aa3-b8da-1a6
a1054bd0a' {
        menuentry 'Proxmox Virtual Environment GNU/Linux, mit Linux
4.15.18-14-pve' --class proxmox --class gnu-linux --class gnu --class o
s $menuentry_id_option
'gnulinux-4.15.18-14-pve-advanced-9bffc581-bb88-4aa3-b8da-1a6a1054bd0a' {
                load_video
                insmod gzio
                if [ x$grub_platform = xxen ]; then insmod xzio; insmod
lzopio; fi
                insmod part_gpt
                insmod btrfs
                set root='hd0,gpt3'
                if [ x$feature_platform_search_hint = xy ]; then
                  search --no-floppy --fs-uuid --set=root
--hint-bios=hd0,gpt3 --hint-efi=hd0,gpt3 --hint-baremetal=ahci0,gpt3 
9bffc581-bb
88-4aa3-b8da-1a6a1054bd0a
                else
                  search --no-floppy --fs-uuid --set=root
9bffc581-bb88-4aa3-b8da-1a6a1054bd0a
                fi
                echo    'Linux 4.15.18-14-pve wird geladen …'
                linux  
/@snapshots/36/snapshot/boot/vmlinuz-4.15.18-14-pve
root=UUID=9bffc581-bb88-4aa3-b8da-1a6a1054bd0a ro
                echo    'Initiale Ramdisk wird geladen …'
                initrd 
/@snapshots/36/snapshot/boot/initrd.img-4.15.18-14-pve
        }
}

### END /etc/grub.d/10_linux ###

### BEGIN /etc/grub.d/20_linux_xen ###

### END /etc/grub.d/20_linux_xen ###

### BEGIN /etc/grub.d/30_os-prober ###
### END /etc/grub.d/30_os-prober ###

### BEGIN /etc/grub.d/30_uefi-firmware ###
menuentry 'System setup' $menuentry_id_option 'uefi-firmware' {
        fwsetup
}
### END /etc/grub.d/30_uefi-firmware ###

### BEGIN /etc/grub.d/40_custom ###
# This file provides an easy way to add custom menu entries.  Simply
type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
### END /etc/grub.d/40_custom ###

### BEGIN /etc/grub.d/41_custom ###
if [ -f  ${config_directory}/custom.cfg ]; then
  source ${config_directory}/custom.cfg
elif [ -z "${config_directory}" -a -f  $prefix/custom.cfg ]; then
  source $prefix/custom.cfg;
fi
### END /etc/grub.d/41_custom ###

### BEGIN /etc/grub.d/41_snapshots-btrfs ###
submenu 'Debian Snapshots' {
        configfile "/@snapshots/36/snapshot/boot/grub/grub-btrfs.cfg"
}
### END /etc/grub.d/41_snapshots-btrfs ###`

Could you please share some information on this finding?
Is my assumption that Grub Menu must display the same content as _/boot/grub/grub.cfg_ wrong?

THX

**Comment by Antynea** [comment]
Hello,

The version of "grub-common" available in debian 9 is this one
[2.02 ~ + beta3-5 deb9u1](https://packages.debian.org/search?keywords=grub2-common
)

If you think, you have a different version installed, update your source list and reinstall grub.
If you have an old grub install on this hdd, and the mbr is not up to date, reinstall grub.

> Is my assumption that Grub Menu must display the same content as /boot/grub/grub.cfg wrong?

It is possible in the case of multiple subvolume that files started by grub do not match the default subvolume. Reinstall grub.

I think the screenshot is correct but the `grub.cfg` provided is out of date.
So you shouldn't have to reinstalled grub.
Check in your fstab that no invalid entries are registered corresponding to `/boot` then correct it.
You can easily check this with the `findmnt `command available in [util-linux](https://packages.debian.org/search?keywords=util-linux)

If you don't find an error, please put the `findmnt `output here.

**Comment by 74cmonty** [comment]
Thanks for your advise.
I finally fixed the issue by re-installing Grub in the MBR of the relevant device.

Now all issues, means inconsistency in Grub menu and booting snapshots, works as expected.
