### ISSUE TITLE
Systemd service fails to access config

### ISSUE THREAD

**Issue by Kr1ss-XD** [Antynea/grub-btrfs#64]
:+1:  Graz for making it into the Arch community repo !
Today I've got the update to 4.0, and I like the new design with the systemd path-unit and service. 

Unfortunately, `grub-btrfs.service` tries to access the old config file, `/etc/grub.d/41_snapshots-btrfs_config`, rather than `/etc/default/grub-btrfs/config`, and fails.

**Comment by Antynea** [comment]
Fixed !
[New release 4.0.1 available](https://github.com/Antynea/grub-btrfs/releases/tag/v4.0.1)
We have to wait for @maximbaz to be here and update the version in the community repository

**Comment by Kr1ss-XD** [comment]
Thx for the quick response !

**Comment by maximbaz** [comment]
Updated, thanks again 😉
