### ISSUE TITLE
subvolume name problem with awk gsub regex

### ISSUE THREAD

**Issue by sdothum** [Antynea/grub-btrfs#7]
It a subvolume with the characters in the gsub(/^["&lt;FS_TREE&gt;/"]+/,"",$NF) exists, the subvolume name generated for grub is incorrect. In my case, the use of the underscore in a subvolume name required changing the expression to

gsub(/^.*&lt;FS_TREE&gt;/,"",$NF)

**Comment by Antynea** [comment]
hi,

Thanks for you comment.

i performed more test with multiple names of subvolume and snapshot.

you are right, with gsub(/^["<FS_TREE>/"]+/,"",$NF), does not work with a underscore in a subvolume name.

i test your suggestion, it's work, but the "/" at the beginning is not cut.

**Comment by Antynea** [comment]
ok,
i replace with gsub(/^.*<FS_TREE>\//,"",$NF)
it work.

Please test with that

**Comment by sdothum** [comment]
That seems to work.. without the leading slash (or with as I originally had).

**Comment by Antynea** [comment]
Thanks for you feedback,
i update script with `gsub(/^.*<FS_TREE>\//,"",$NF)`

`/` should not appear, otherwise your grub cfg look like this : 
`linux   //_test/snap/boot/vmlinuz-linux `

twice `/` is not good, and not be able to boot.
