### ISSUE TITLE
unclutter the menu with AMD microcode

### ISSUE THREAD

**Issue by viogq** [Antynea/grub-btrfs#71]
I modified grub-btrfs to work with AMD microcode only (comment out the business about the intel file {the microcode filename just has "amd" instead of "intel" prefixed }) and with timeshift. Maybe I make a pull-request one time.

It would be nice to have the config option to see AMD microcode only. So the menu gets uncluttered on a AMD machine.

for timeshift, just the path line must be changed from  .snapshots  to  **/mnt/timeshift/backup/timeshift-btrfs/snapshots/**

snapper-gui  work great in SUSE but breaks on most other distros unfortunately.

**Comment by Antynea** [comment]
hello,
I didntt know that this package existed.
I found his creation here :
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux-firmware&id=7601fbe28bba45df626edefc9604aacdb1166bac

When this project started, this package didn't exist.
This project requires an update.

> I modified grub-btrfs to work with AMD microcode
where's your work?

Don't hesitate to contribute to this project.
I would be happy to check your contribution and add your code.

**Comment by Antynea** [comment]
An option already exists in the configuration file :
`GRUB_BTRFS_INTEL_UCODE=("intel-ucode.img")`

replace with your microcode name
Ps: `This option requires renaming`

**Comment by Antynea** [comment]
1 month without answer
closed
