### ISSUE TITLE
Submenu empty

### ISSUE THREAD

**Issue by 74cmonty** [Antynea/grub-btrfs#72]
Hi,
I have installed and configured _grub-btrfs_ w/o issues.
And I can see in screen that existing BTRFS snapshots are found when new Grub Menu is generated.

However, when I check the submenu in Grub there are no entries.

Could you please advise how to troubleshoot this issue?

THX

**Comment by Antynea** [comment]
Hi,
Which OS ? (Arch Linux, debian, others ...)
Which version of grub-btrfs ? [version 4.1 is latest](https://github.com/Antynea/grub-btrfs/releases/tag/v4.1)
Your grub.cfg file
Your grub-btrfs.cfg file

And a screen of your Grub menu with snapshot menu of grub-btrfs.

**Comment by 74cmonty** [comment]
Hi,
I'm running Arch Linux with multiple kernels (LTS + stable) installed (not knowing if this is relevant though).
[thomas@pc7-cubi3 ~]$ trizen -Ss grub-btrfs
community/grub-btrfs 4.1-1 [Installiert]

My _/etc/default/grub-btrfs/config_ is [here](https://pastebin.com/ZSXZq47P).
My _/boot/grub/grub.cfg_ is [here](https://pastebin.com/y4DFqwBV).
My _/boot/grub/grub-btrfs.cfg_ file is 104k; is this normal?
I've attached it [here](https://pastebin.com/TXZHuKVu).

There's a Grub submenu for snapshots, but when I enter it I get redirected to main menu.

THX for your support!

**Comment by Antynea** [comment]
Hello,

> My /boot/grub/grub-btrfs.cfg file is 104k; is this normal?

Yes, your file contains 25 snapshots with 4 entries
(Linux kernel with fallback and Lts kernel with fallback)

I tested the file, it loads properly.
The problem is elsewhere.

> There's a Grub submenu for snapshots, but when I enter it I get redirected to main menu.

What you say indicates a wrong path to the `grub-btrfs.cfg` file in your `grub.cfg`
Your root subvolume is `@` ?
and your /boot directory is in the same subvolume ?

If yes
Can you edited your `grub.cfg` and modify it like that :

```
### BEGIN /etc/grub.d/41_snapshots-btrfs ###
submenu 'Arch Linux snapshots' {
    configfile "/@/boot/grub/grub-btrfs.cfg"
}
### END /etc/grub.d/41_snapshots-btrfs ###
```

After modification
don't use `grub-mkconfig`, otherwise it will overwrite the changes.
Restart and try again to enter the menu.

**Comment by 74cmonty** [comment]
Hi,
the configuration of /boot/grub/grub.cfg already included this parameter + a search command.
Anyway I commented out the search command and now the submenu is displayed:
```### BEGIN /etc/grub.d/41_snapshots-btrfs ###
submenu 'Arch Linux snapshots' {
	#search -f --set=root --no-floppy /grub/grub-btrfs.cfg
	configfile "/@/boot/grub/grub-btrfs.cfg"
}
### END /etc/grub.d/41_snapshots-btrfs ###
```
But what happens after next `grub-mkconfig`?

**Comment by Kodehawa** [comment]
This happens to me too, and even if I comment the search command it doesn't work :(

**Comment by Antynea** [comment]
hello,
There seems to be a problem with the search command.
I don't know why.
@daiaji had requested this addition.

The command works for some people but not for everyone, it's strange.

If daiaji understand what is worrying, we will make a correction.
Otherwise, I will pass this command as an available option.

**Comment by daiaji** [comment]
> hello,
> There seems to be a problem with the search command.
> I don't know why.
> @daiaji had requested this addition.
> 
> The command works for some people but not for everyone, it's strange.
> 
> If daiaji understand what is worrying, we will make a correction.
> Otherwise, I will pass this command as an available option.
In fact, I have a boot partition, and not everyone will have a boot partition. I am afraid that the compatible method is to search for the uuid of the partition containing the boot folder. In fact, this should be done, at least the default kernel boot entry will search the partition where the kernel is located  uuid, I guess you should also use the grub-btrfs.cfg path in the correct location.  But it's strange, why doesn't archlinux create a subvolume for the boot folder?  It appears that the boot folder is under a subvolume in the root directory and there is no separate boot subvolume, which usually means that the contents of the snapshot will include the kernel.
It seems that you can add judgments. When the configfile /grub/grub-btrfs.cfg fails to run, execute the configfile /@/boot/grub/grub-btrfs.cfg, the if command should be able to do it.

**Comment by daiaji** [comment]
> hello,
> There seems to be a problem with the search command.
> I don't know why.
> @daiaji had requested this addition.
> 
> The command works for some people but not for everyone, it's strange.
> 
> If daiaji understand what is worrying, we will make a correction.
> Otherwise, I will pass this command as an available option.

![IMG_20191207_232424750](https://user-images.githubusercontent.com/25875791/70376868-d2036900-1948-11ea-9df5-60c8853e4887.jpg)
I found a nice variable. He's very interesting, isn't it?  You don't even have to search for the location of the grub folder.😜

**Comment by Antynea** [comment]
Thanks for your time.

If I understood correctly,
using this:
```
### BEGIN /etc/grub.d/41_snapshots-btrfs ###
submenu 'Arch Linux snapshots' {
    configfile "\${prefix}/grub-btrfs.cfg"
}
### END /etc/grub.d/41_snapshots-btrfs ###
```

It should work for everyone.

**Comment by daiaji** [comment]
> Thanks for your time.
> 
> If I understood correctly,
> using this:
> 
> ```
> ### BEGIN /etc/grub.d/41_snapshots-btrfs ###
> submenu 'Arch Linux snapshots' {
>     configfile "\${prefix}/grub-btrfs.cfg"
> }
> ### END /etc/grub.d/41_snapshots-btrfs ###
> ```
> 
> It should work for everyone.

Since my manjaro is damaged, I can't test it now, but someone else should be able to.😜

**Comment by Antynea** [comment]
I will push a request.
Re-open this issue if the problem persists.

**Comment by 74cmonty** [comment]
Hi,
I want to confirm that the solution delivered with version 4.2-1 (for Arch Linux) works perfectly.

THX

**Comment by daiaji** [comment]
@74cmonty Why not give it a try?☺️
