### ISSUE TITLE
[Enhancement] Allow config option for boot partition and kernel location

### ISSUE THREAD

**Issue by bbaserdem** [Antynea/grub-btrfs#73]
I have been trying to hack this in, but grub configuration is a bit over my head. I'll describe my usercase;

* I have an ESP (/dev/nvme1n1p1), and a LUKS container (/dev/nvme1n1p2), with an LVM on top of the luks installation. My root partition is a btrfs logical partition on the LVM.
* I have / as a btrfs snapshot
* I have /boot as a regular folder
* Arch installs the kernel to /boot/vmlinuz-* 
* I mount the ESP at /boot/efi, and my grub configuration folder is found in /boot/efi/grub
* I have a tool that automatically signs my kernel after an update, and places them in /boot/efi/EFI/Arch (and grub)

I want to use grub only to boot into my other snapshots. Currently, grub-btrfs expects the kernel location to be /boot (as hard coded). It picks up the unsigned kernel at the root of my file-system, which then cannot be found because they are encrypted. I want to be able to change the kernel location to my signed copies under the ESP, in the directory EFI/Arch/vmlinuz-*. I was wondering how to add in a config option that can change the default boot partition location, and the location for the kernels.

**Comment by Antynea** [comment]
Hello,
I will take the time to look at that

**Comment by Antynea** [comment]
Can you share your grub.cfg file please ?

**Comment by Antynea** [comment]
Closing for lack of signs of life
