### ISSUE TITLE
Ignoring the /var/lib/docker directory has no effect.

### ISSUE THREAD

**Issue by Kodehawa** [Antynea/grub-btrfs#74]
Title. I ignored the /var/lib/docker directory on `/etc/default/grub-btrfs/config` and docker subvolumes still get detected as snapshots.

![image](https://user-images.githubusercontent.com/20606963/69923074-85b7b500-1480-11ea-9b29-fc0096861ee5.png)

On grub-mkconfig (on the pacman hook, but running `grub-mkconfig -o /boot/grub/grub.cfg` yields the same)
![image](https://user-images.githubusercontent.com/20606963/69923083-9ec06600-1480-11ea-82fb-7f3991be2b9a.png)
![image](https://user-images.githubusercontent.com/20606963/69923114-f4950e00-1480-11ea-83b2-8b4bf1748816.png)

Using `/var/lib/docker` or `var/lib/docker` has exactly the same effect.
edit: for the record, var is on a different subvolume

**Comment by Kodehawa** [comment]
Nevermind. Ignoring @var/lib/docker worked just fine. I think you could add this to docs?

**Comment by Antynea** [comment]
hello,
As you have seen,
you have to use the exact pathname

Ok, Ok, I will improve the description
