### ISSUE TITLE
Parser errors while detecting snapshots

### ISSUE THREAD

**Issue by ni-ka** [Antynea/grub-btrfs#81]
Hi,

I've been using grub-btrfs for a while now on manjaro without issues, but I recently noticed that whenever I rebuild my grub config the snapshot detection takes about 20min and uses a lot of CPU.

It also throws some errors:

```
###### - Grub-btrfs: Snapshot detection started - ######
# Info: Separate boot partition not detected 
loading 119 failed
:1: parser error : Document is empty

^
loading 526 failed
:1: parser error : Document is empty

^
loading 527 failed
loading 618 failed
loading 675 failed
IO error (open failed path://.snapshots/629 errno:2 (No such file or directory)).
loading 119 failed
:1: parser error : Document is empty

^
loading 526 failed
:1: parser error : Document is empty

^
loading 527 failed
loading 618 failed
loading 675 failed
loading 119 failed
:1: parser error : Document is empty

^
loading 526 failed
:1: parser error : Document is empty

^
loading 527 failed
loading 618 failed
loading 675 failed
```
It then moves on to correctly list snapshots and completes correctly.

Any suggestions how to fix this?

**Comment by maximbaz** [comment]
Hey, this definitely sounds wrong, I wonder if your snapshots are corrupted...

Try to manually follow commands in this function, maybe you can spot which command throws all these errors...

https://github.com/Antynea/grub-btrfs/blob/21df698e04cf0e2e48872e716c3fd9dcdb3c6203/41_snapshots-btrfs#L236-L318

You could also try to add `set -x` in the top of `/etc/grub.d/41_snapshots-btrfs` and then run `# grub-mkconfig -o /boot/grub/grub.cfg`, it will print a TON of output but it will 100% point you to the problem 🙂

**Comment by ni-ka** [comment]
Indeed I had some serious issues with my btrfs and ended up recreating the fs... the document is empty were some orphan snapshots that had been deleted in snapper but the btrfs snapshots still existed so I just deleted those manually

**Comment by maximbaz** [comment]
Great that you found the issue and fixed it :) Let's close this since I think it will be very hard to support detection of broken snapshots, let me know if you disagree and we will reopen.
