### ISSUE TITLE
How to add grub-btrfs snapshot option with grub customizer?

### ISSUE THREAD

**Issue by InvisibleRasta** [Antynea/grub-btrfs#84]
hello guys, does anyone know how i can include btrfs snapshots in GRUB boot options? I usually use grub-customizer to add or edit boot entires.
Grub customizer has various options to add boot entries like  Scripts,Linux,Linux-ISO,Chainloader,Memtest and other..
I guess i can add an entry with grub-customizer, i am not sure on how to do it tho
Thank you

**Comment by Kr1ss-XD** [comment]
Actuallly, you shouldn't need to. `grub-btrfs` installs a grub drop-in file at `/etc/grub.d/41_snapshots-btrfs` which _should_ be automatically picked up and create a submenu everytime you perform a `grub-mkconfig` or `update-grub`.

Not sure if the GRUB customizer messes anything up though.

**Comment by Antynea** [comment]
I never tried "grub-customizer".
"grub-btrfs" is designed in a specific way.
It creates its own file including a list of available snapshots, and adds in "grub.cfg" a link pointing to this file.

I'm just assuming, but "grub-customizer" shouldn't support this type of configuration.

However, if "grub-customizer" is as powerful as it is said, you should be able to take advantage of the work done on "grub-btrfs" to write a custom script for "grub-customizer"

Good Luck...
