### ISSUE TITLE
Get distro name from /etc/os-release

### ISSUE THREAD

**Issue by notramo** [Antynea/grub-btrfs#87]
Instead of hardcoding Arch Linux.

**Comment by maximbaz** [comment]
Would you like to submit a PR? To be honest I don't know how much valueable this is, considering that the menu name is configurable anyway via `GRUB_BTRFS_SUBMENUNAME`

https://github.com/Antynea/grub-btrfs/blob/6ff1fc7127a41abc0275cde532b6efb8e99df760/config#L3-L5

**Comment by darkdragon-001** [comment]
Examples are:
```
NAME="Ubuntu"
NAME=Fedora
NAME="Linux Mint"
NAME="Alpine Linux"
```

Could be parsed with `awk`:

    awk -F "=" '/^NAME=/ {gsub(/"/, "", $2); print $2}' /etc/os-release

You can check various distributions via docker:

    for distro in ubuntu linuxmintd/mint20-amd64 fedora alpine centos clearlinux archlinux; do
        docker run --rm "$distro" awk -F "=" '/^NAME=/ {gsub(/"/, "", $2); print $2}' /etc/os-release
    done

```
Ubuntu
Linux Mint
Fedora
Alpine Linux
CentOS Linux
Clear Linux OS
Arch Linux
```

**Comment by maximbaz** [comment]
Looks good, please submit a PR, and add some default in case parsing fails, maybe just "Linux"

**Comment by darkdragon-001** [comment]
I haven't looked into grub-btrfs code, so I don't know where to add it...
