### ISSUE TITLE
Auto-move child subvolumes

### ISSUE THREAD

**Issue by darkdragon-001** [Antynea/grub-btrfs#89]
Many applications (e.g. docker) create subvolumes (`/var/lib/docker/btrfs/subvolumes/XXX`) which are children of the root subvolume (The number after `top level` when running `btrfs subvolume list /`). These children must be moved the the selected snapshot to keep these applications running.

An approach could be to search for all subvolumes which are children of the default root subvolume. All these children are then moved to the selected subvolume on boot.

**Comment by maximbaz** [comment]
This is an interesting idea, but I checked and I couldn't find any possibility to change parent of a subvolume - do you know of any?

As mentioned in the other thread, this project doesn't really have any script that runs during or after boot, all it does is it prepares boot entries, all the work for managing subvolumes and snapshots is left up to a user.

Having said that, I think you can try the following approach to solve the scenario you describe: in addition to `/` subvolume, create another subvolume for `/var/lib/docker` and explicitly mount both of them via `/etc/fstab`. Then docker will be creating its own subvolumes and their parent will be not root, but the secondary subvolume. Then if you ever break your root subvolume and boot into a snapshot, your `fstab` will still mount `/var/lib/docker` and all its children. 

What do you think, will it solve your use-case?

**Comment by maximbaz** [comment]
I've just tested this approach on my laptop, seems to work pretty well, I could use `docker ps -a` when booted from a snapshot and see some old containers 🙂 

Will close but let me know if you have some questions or comments.

**Comment by darkdragon-001** [comment]
> This is an interesting idea, but I checked and I couldn't find any possibility to change parent of a subvolume - do you know of any?

I think there is none. I was using plain `mv` within the root volume.

Thanks for the idea with the docker subvolume. I will try this!
