### ISSUE TITLE
Option to ignore the "@" system subvolume.

### ISSUE THREAD

**Issue by damian101** [Antynea/grub-btrfs#90]
I would prefer the standard system to not be listed as a snapshot in Grub.

**Comment by maximbaz** [comment]
See `GRUB_BTRFS_IGNORE_SPECIFIC_PATH`, I think it should help

https://github.com/Antynea/grub-btrfs/blob/6ff1fc7127a41abc0275cde532b6efb8e99df760/config#L48-L56

**Comment by maximbaz** [comment]
Apologies, it wasn't possible, but now is 🙂

**Comment by maximbaz** [comment]
I added `@` to the default value of that configuration variable, seems to be a common name that people want to ignore.
