### ISSUE TITLE
Enhancement: speed up calls to the snapper tool

### ISSUE THREAD

**Issue by nephros** [Antynea/grub-btrfs#91]
The script calls `snapper list` three times to collect information about the snapshots.
Depending on how the underlying filesystem and snapper is set up, this may take a long time.

Suggestions:

 - Whenever calling `snapper list`, add the `--disable-used-space` option. This will speed up the listing on configurations using btrfs quota.
 - Perhaps  call `snapper list` once, store the output in e.g. an array or a temp file, and retrieve the information from there
 - Perhaps use the `--columns` option to retrieve all needed information in one go and nothing else

**Comment by maximbaz** [comment]
Good ideas! Would you like to try to submit a PR? I am using snapper and would be happy to review and test 🙂

**Comment by nephros** [comment]
> Good ideas! Would you like to try to submit a PR? I am using snapper and would be happy to review and test

See PR. I did the quickest option, the first from my bullet list above.
The others would probably be smarter but more effort and more risk of breakage.
